### ISSUE TITLE
How to uninstall atuin?

### ISSUE THREAD

**Issue by dingye18** [atuinsh/atuin#111]
I have installed the Atuin successfully. But it seems not usable for me now. So I want to uninstall it. But I did not find any documents about this........

**Comment by conradludgate** [comment]
> Atuin can not load the old history which exist before installation might be a problem

Atuin does provide an import command. `atuin import zsh` will locate your current history file and import it into the local database

**Comment by conradludgate** [comment]
> But I did not find any documents about this........

Thanks for pointing this out by the way, we should provide an uninstall command

**Comment by dingye18** [comment]
> > Atuin can not load the old history which exist before installation might be a problem
> 
> Atuin does provide an import command. `atuin import zsh` will locate your current history file and import it into the local database

Thanks,  and sorry I did not notice it......
