### ISSUE TITLE
Tracking tty in the database

### ISSUE THREAD

**Issue by withnale** [atuinsh/atuin#1113]
Is there any possibility to track the tty in the database?

I often have a dozen shells open and sometimes finding which tab ran a command is a pain. If the tty was tracked, I could write a little script that obtained the tty and send a BELL code to it. It's easy enough then to configure a terminal to flash based on this.

**Comment by arcuru** [comment]
I'm not a decision maker but I don't think it's worth it to track the tty in Atuin. I think it would only be useful for the situation you described, and I don't think that's enough justification for storing it forever in the synced database, or for the engineering effort required to store it only in the current session where it would be usable.

**Comment by ellie** [comment]
I agree with @arcuru here - thanks for the suggestion though
