### ISSUE TITLE
make server sync async

### ISSUE THREAD

**Issue by happysalada** [atuinsh/atuin#1147]
When server sync is enabled, the performance hit of using atuin is noticeable.
It would be great if the sync was done asynchronously so that the user would not even notice the difference between sync mode and local mode.
I know this is harder to do than to say, so just opening an issue to start the discussion.

**Comment by ellie** [comment]
Could you elaborate please?

Sync is already async. It runs in the background and shouldn't slow down shell usage

**Comment by happysalada** [comment]
Happy to do some more testing, but recentky my sync server went down and i had to disable the sync mode, i noticed atuin is much more responsive.

I should get back my server beginning of september, ill be able to test the sync mode again at that time.

**Comment by ellie** [comment]
Thanks!

Responsive in what way? Searching in the UI, or just your shell prompt?

Was there latency selecting commands?

We may not need you to test things if you could just describe where you felt it wasn't responsive

**Comment by happysalada** [comment]
Latency to generate the ui after pressing ctrl-r

**Comment by ellie** [comment]
Perfect thank you! This is totally unrelated to sync, as we don't run any sync process there

It could be the update check, which checks that the client and server are running the same version

`update_check = false`

In your atuin config will disable this. We've had a few issues before, I'll probably disable it

**Comment by happysalada** [comment]
Thank you for the quick feedback. Ill try without the update check.
