### ISSUE TITLE
Update install.sh script for aarch64 assets

### ISSUE THREAD

**Issue by willifehler** [atuinsh/atuin#1148]
Hello,

I saw that Ellie compiled assets for aarch64.

e.g.
https://github.com/atuinsh/atuin/releases/download/v15.0.0/atuin-v15.0.0-aarch64-unknown-linux-gnu.tar.gz.zip

Do we need to update the install.sh script to pickup these assets?

Cheers - Willi

**Comment by ellie** [comment]
We do! See #870
