### ISSUE TITLE
Latest nushell release breaks atuin init config generation

### ISSUE THREAD

**Issue by robbienohra** [atuinsh/atuin#1152]
[Nushell 0.83](https://www.nushell.sh/blog/2023-07-25-nushell_0_83.html) introduced a breaking change with respect to environment variables.

Specifically `let-env` was removed (now use the `$env.FOO = "BAR"` form instead).

This means that `atuin init nu` no longer generates the correct `nushell` configs.

My temporary local fix has been to simply find and replace, within the generated  `init.nu` config, the `let-env` references with `$env`.

This of course would be the fix within the `atuin init nu` call itself.

**Comment by ellie** [comment]
It's currently fixed in main and needs releasing. I'm away for the weekend but will release asap when I'm back.

**Comment by robbienohra** [comment]
Ah that's fantastic, thanks, @ellie !
