### ISSUE TITLE
[Bug] Existing commands are not added to the history when ran again

### ISSUE THREAD

**Issue by RichyHBM** [atuinsh/atuin#1164]
This may quite possibly be a configuration issue on my part, but I'm finding when I use a command I have already ran before (using atuin to search and select the command), the latest run of the command isnt added to the history meaning as time goes by commands I regularly run are getting more and more lost in the beginning of the atuin history

**Comment by kohane27** [comment]
1. In the shell: run the gibberish command `eeifuifazvdf`:

```bash
➜  eeifuifazvdf
zsh: command not found: eeifuifazvdf
```

2. Open another shell and use `C-r` to search `eeifuifazvdf`
3. Could not find it

**Comment by kohane27** [comment]
I updated through the AUR to `atuin-16.0.0-2` and this bug seems to be solved already. Thank you!

**Comment by ellie** [comment]
I'm not entirely sure how/why (I could never replicate this), but glad to hear it
