### ISSUE TITLE
Remove an item from history

### ISSUE THREAD

**Issue by aagha** [atuinsh/atuin#1175]
How do I remove something like this record so it doesn't show up in my history any more?

![image](https://github.com/atuinsh/atuin/assets/5522103/5e1efa43-f13d-48d8-9c98-e4f23681191f)

**Comment by kohane27** [comment]
https://github.com/atuinsh/atuin/issues/413

**Comment by ellie** [comment]
https://atuin.sh/docs/commands/search

Use the --delete flag on a search query

**Comment by aagha** [comment]
Following up.

So lets say I'm trying to delete:

![image](https://github.com/atuinsh/atuin/assets/5522103/160733ac-2a5b-4d4f-acb0-5b9022b2f4cb)

The command I'm executing is:

![image](https://github.com/atuinsh/atuin/assets/5522103/098103ac-9d8c-45a2-ae4b-7847641f07a4)

I can't terminate the command.

**Comment by kohane27** [comment]
I think you missed a closing backtick in the command

**Comment by aagha** [comment]
No, the opening back tick is the error--that's the reason I'm trying to delete that command from my history. I wrapped the entire string I want removed in quotes.

**Comment by lespea** [comment]
It might be nice to be able to hit `delete` when scrolling through the history and have that do the removal (with a verification prompt or something?)

**Comment by ebardie** [comment]
Enter the new Inspector mode by pressing `<ctrl>-o`  on the command you wish to zap, and then press `<ctrl-d>` to delete.

I'm running Atuin v18.2.0, and CBA to look up when Inspector mode landed, so you may need to upgrade.

 Whilst this is a two step process,  it's less of a faff than messing with the sqlite db file, or working out a tight search pattern.
