### ISSUE TITLE
Move the search bar to the top

### ISSUE THREAD

**Issue by evccyr** [atuinsh/atuin#1194]
Having the search bar at the top of the window relieves me from the neck pain on my laptop. It is a huge difference in having to look at the bottom of the screen and at the top.
My fzf window looks like this for example:
![image](https://github.com/atuinsh/atuin/assets/85027668/7357d41a-bb7e-4344-9f8f-e75127273357)

**Comment by ellie** [comment]
```
invert = true 
```

In your config will achieve this! I've updated the docs
