### ISSUE TITLE
[Improvement]: Allow editing a history entry

### ISSUE THREAD

**Issue by soderluk** [atuinsh/atuin#1198]
Great project, thank you for this!

One thing I've been thinking of, is the ability to edit/update a history entry, i.e. run `atuin edit <entry id>` or when using Ctrl+R and choosing the entry, a keybinding for updating the entry.

I typoed one command, and when hitting Ctrl+R or arrow up, it persists in the history, and even if I choose it, and update it to the correct command, the corrected command is not added to the history. I had to go in to the sqlite database and delete the entry and then re-run the correct one to get the history updated.

**Comment by dcarosone** [comment]
This is a (partial) dup of #1039; while I think the enhancement here would be good, and helpful as a workaround for that issue, fixing that issue makes it less important to have this more complex direct editing feature.

**Comment by ellie** [comment]
Agreed with @dcarosone that this would just be a workaround for #1039. I don't think editing past history would be necessary once this is resolved
