### ISSUE TITLE
Deleted Entry Junk in Interactive Search

### ISSUE THREAD

**Issue by mentalisttraceur** [atuinsh/atuin#1207]
Starting from a totally new install of Atuin:

1. I created 4 history entries (using `atuin history start -- ...` and then `atuin history end ...`).
2. I deleted all history entries with `atuin search --delete-it-all`.
3. I created 1 more history entry (recording `:` as the command).

Now `atuin search` only shows the one `:` command from after the delete, but `atuin search -i` shows five entries, the `:` from after the delete and four junk entries from before the delete whose displayed names are hashes but which are not matched by any search.

(Neither `atuin sync` nor `atuin sync --force` seem to fix this.)

![image](https://github.com/atuinsh/atuin/assets/6531708/94a79230-19f3-4872-80a4-55104bd85daf)

![image](https://github.com/atuinsh/atuin/assets/6531708/60e5caea-833a-4d30-b834-26c22ed27cd8)

**Comment by ellie** [comment]
Fixed in #1272
