### ISSUE TITLE
Cannot recall history entries containing backslashes and newlines in fish due to improper expansion

### ISSUE THREAD

**Issue by saulrh** [atuinsh/atuin#1211]
atuin 12.0.0, fish 3.6.1

Repro: Invoke `_atuin_search` by keybinding, navigate with arrow keys to a history entry containing a multiline command with backslashes, press enter to select that history line, it fails to populate with the following error:

```
> commandline: -e @env_vars/dev.yml \: unknown option

- (line 21):
        commandline -r $h
        ^
in function '_atuin_search'

(Type 'help commandline' for related documentation)
```

The function that's failing, which was added to `fish` by an invocation of `atuin init fish | source` by `~/.config/fish/conf.d/atuin.fish`:

```fish
function _atuin_search
    set h (RUST_LOG=error atuin search -i -- (commandline -b) 3>&1 1>&2 2>&3)
    commandline -f repaint
    if test -n "$h"
        commandline -r $h
    end
end
```

**Comment by ellie** [comment]
Could you please update to the latest version of Atuin and ensure it's still reproducible?

**Comment by saulrh** [comment]
Repros on atuin 16.0.0, yes.

**Comment by saulrh** [comment]
It looks like it's specifically the following conditions:
* backslash-newline in the command
* flag-shaped parameter (e.g. `-e`) starts the line following backslash-newline

The following commands can be successfully retrieved:
```fish
echo \
  bar -e bar
echo -e bar
echo \ -e bar
```
The following commands _cannot_ be successfully retrieved:
```fish
echo \
  -e bar
```
The following commands can be successfully retrieved **but are retrieved incorrectly**:
```fish
# Retrieved as just `echo \`; the `-b` is lost because it's parsed by `commandline` instead of being passed through.
echo \
  -b
```
I bet that this is an injection vulnerability of some kind, now that I'm looking at it more closely.

**Comment by saulrh** [comment]
Looks like the fix is just `commandline -r "$h"` at https://github.com/atuinsh/atuin/blob/6d3b14b123e287be0a06dd7e68dacca507480b94/atuin/src/shell/atuin.fish#L21. I'll see about putting in a PR tonight if I have time.
