### ISSUE TITLE
Allow setting search mode by key binding

### ISSUE THREAD

**Issue by pierreprinetti** [atuinsh/atuin#1216]
Hello!
I would like to set up atuin so that ctrl-r gives me fuzzy search, and arrow-up gives me prefix search mode.

Is that possible? Thank you!

**Comment by ellie** [comment]
Hey! This isn't currently possible as we only allow configuring the _filter mode_ used per key and not the _search mode_.

This would be nice to have though! If anybody would like to work on it please let me know

**Comment by deicon** [comment]
Like to work on this as a first issue

**Comment by pierreprinetti** [comment]
Thanks folks for working on this!
