### ISSUE TITLE
Workspaces config option not working as expected based on docs

### ISSUE THREAD

**Issue by alerque** [atuinsh/atuin#1219]
I've been trying to use the "workspace" filter mode, but setting it up does not work as expected.

```toml
workspaces = true
filter_mode = "workspace"
filter_mode_shell_up_key_binding = "directory"
```

First of all, enabling the `workspaces` config option overrides both of the `filter_mode` related settings: no matter what you set them to it will always override the mode. So then I thought to set it to false, and that actually worked. Now my default filer mode is workspace, and the directory mode still works when specifically requested.

This is somewhat unintuitive and could use better documentation on what the flag actually does. It doesn't enable the extra mode, it enables in in preference to all other modes.

This is obnoxious because in the absence of Git workspace, I would like to use the *directory* mode. I can set the `filter_mode` to *directory*, but when a workspace is detected I have to hit <kbd>Ctrl</kbd><kbd>R</kbd> FIVE TIMES to get to directory mode! I wish I could disable or re-arrange the *host* and *global* modes so I don't have to scroll past them every time.

A more useful way to set this up might be to make the modes a list. This would have an advantage of also setting an order:

```toml
filter_mode = "workspace,directory,session,host,global"
filter_mode_shell_up_key_binding = "workspace,directory,session"
```

Alternatively maybe like the `workspaces` key there should be other keys to enable/disable all the modes, or one top level sort setting for what over to try modes.

**Device (please complete the following information):**
 - OS: Linux
 - Shell zsh
 - Version 16.0.0

**Self hosted**
No

**Comment by ellie** [comment]
As per the docs

> This flag enables a pseudo filter-mode named "workspace": the filter is automatically activated when you are in a git repository. Defaults to false.

I'm not 100% sure which part of this is unclear, as the intent behind the flag is to automatically override other settings only when you are in a git repo. That is why it is a separate flag, as it doesn't make sense outside of a git repo

If the issue here is the documentation, then I'd really appreciate any suggestions as to how we could make it more clear

> but when a workspace is detected I have to hit CtrlR **FIVE TIMES** to get to directory mode! I wish I could disable or re-arrange the host and global modes so I don't have to scroll past them every time.

I'm really sorry but the caps-lock here makes it sound like you're shouting at me. Given that you use the software here for free, and I volunteer my time in order to maintain it, that's not very appropriate. 

If you find Atuin "obnoxious" enough to shout at maintainers, then I'd really appreciate it if you didn't use my software.

**Comment by alerque** [comment]
I'm sorry, but please consider that you might have misread my tone. I understand how long batches of all caps is considered shouting, but one or two words in the middle of a sentence can be and usually is just for emphasis, not for shouting at someone. I was already using *italic* text to format value keywords and **bold** was already used for headings (and in my original edit for something else too) and so I used a third way to highlight the note of surprise.

As for the docs, yes I think they are unclear and could be improved. I'd be happy to submit a PR just for that, but before I do I'd also like you to reconsider whether this is a bug. I think I jumped in to fast to my suggestion of setting an ordering and didn't finish explaining why this feels like a bug.

Consider these settings:

```toml
style = "compact"
filter_mode = "directory"
```

I would **expect**:

1. Anywhere it a Git working directory, the first filter mode when entering Atuin would be *workspace* and the second mode if I hit the activation key again to be *directory*.
2. Anywhere outside of a Git working tree the default filter mode would be *directory*.

What **actually** happens:

1. The special filter mode is *workspace* as expected, but then it falls back to *global*, *host, and *session* before I can get to *directory*.
2. This works as expected.
