### ISSUE TITLE
exitstatus missing from cli format options

### ISSUE THREAD

**Issue by MicahElliott** [atuinsh/atuin#1230]
I believe there should be something like an `{exitstatus}` (or `{status}`) in the `history list`. Presently, fields supported are:
```
% atuin help history list 
List all items in history         

Usage: atuin history list [OPTIONS]

Options:
  -c, --cwd              
  -s, --session          
      --human            
      --cmd-only         Show only the text of the command
  -f, --format <FORMAT>  Available variables: {command}, {directory}, {duration}, {user}, {host} and {time}. Example: --format "{time} - [{duration}] - {directory}$\t{command}"
  -h, --help             Print help
```

When trying it I see:
```
% atuin history list --format '{directory}\t{command}\t{status}'
ERROR: History output failed with the following error: formatter error 
```

**Comment by ellie** [comment]
I think something like `{exit}` would be great! Thanks for raising

**Comment by deicon** [comment]
What is the expected behaviour here ? 
`atuin history list --format '{directory}\t{command}\t{exit}'` 
is already showing the exit code of the args. 

what information is expected to be put into the string when using {status} ?

**Comment by deicon** [comment]
Exit was introcuced with #0f139044b4d

**Comment by MicahElliott** [comment]
Ah, I just didn't think to try `{exit}` specifically, and didn't see it in the _help_. Thanks for adding that!
