### ISSUE TITLE
Setting db_path errors "no rows"

### ISSUE THREAD

**Issue by deas** [atuinsh/atuin#1236]
**Describe the bug**
In `config.toml` whenever I set `db_path`, such as

```
db_path = "~/.local/share/atuin/history-nu.db
```

I get errors:

```
Error: no rows returned by a query that expected to return at least one row
```

**To Reproduce**
1. Customize `db_path` in `config.toml`

**Expected behavior**
No error ;)

**Error logs**
n/a

**Device (please complete the following information):**
 - OS: Linux
 - Shell n/a
 - Version : 16.0.0

**Additional context**
I am trying to keep separate histories for `zsh` and `nushell` as I am trying to migrate to the latter - because they are very different.  ;)  I use `ATUIN_CONFIG_DIR` to point the ` nushell` instance to a dedicated config file.

I understand that to maintain separate histories for both shells, I most likely also need to customize `key_path` and `session_path` and create a separate registrations to get sync across machines to work.

**Comment by conradludgate** [comment]
I think I understand why you get this error. I will assume that you edited your config using a terminal based editor:

1. You start your editor. The editor command is saved into the original database and the ID is saved for later
2. You edit the config
3. You exit the editor, the ID for the command is not found in the new database

I don't think this error is very actionable. I'm open to ignoring them
