### ISSUE TITLE
Allow something like: `atuin history list --reverse`

### ISSUE THREAD

**Issue by Janik-Haag** [atuinsh/atuin#1239]
**Is your feature request related to a problem? Please describe.**
Currently `atuin history list` shows `old -> new` and I would like to reverse that order because I'm using that mostly with a custom fzf script for theming and currently reverse the list after atuin is down outputting which gives quite a bit of delay with a large history limit. 

**Describe the solution you'd like**
The same as with `atuin history list` but with a reversed order from `new -> old`

**Comment by kiran-4444** [comment]
I'd like to work on this issue. Can someone help me by giving me some pointers to get started? Thanks!

**Comment by deicon** [comment]
Starting from the List Command Line Argument of the atuin client, this seems to end up here https://github.com/atuinsh/atuin/blob/cea68660fd43ecdefa735f027199000cc6a60aad/atuin-client/src/database.rs#L255
beeing a matter of setting the orderBy statement appropriately. 
But be aware, that this list method is called not only to list but also inside the engine and stats.

**Comment by deicon** [comment]
@ellie can be closed as fixed with #1252

**Comment by ellie** [comment]
Thanks!
