### ISSUE TITLE
Installing in userspace?

### ISSUE THREAD

**Issue by jucor** [atuinsh/atuin#1244]
Dear @ellie 

Is there any way to install Atuin in userspace? 

I am a non-sudo regular user on an academic compute cluster with Ubuntu nodes rights.  I would love to use atuin, but the install script requires sudo.

I see you kindly release the binaries, but am unsure about which parts of the rest of the install process to set-up. Is it just the shell hooks?
Thanks a lot for any pointer to the right doc!

**Comment by jucor** [comment]
Answering to myself in case anyone needs it: yup, it's as simple as downloading the correct binary from [https://github.com/atuinsh/atuin/releases/] then following the Shell setup [documented here](https://atuin.sh/docs/advanced-install#shell-plugin). 
Closing, sorry for the noise :)

**Comment by gigberg** [comment]
> Answering to myself in case anyone needs it: yup, it's as simple as downloading the correct binary from [https://github.com/atuinsh/atuin/releases/] then following the Shell setup [documented here](https://atuin.sh/docs/advanced-install#shell-plugin). Closing, sorry for the noise :)
thanks!

**Comment by gigberg** [comment]
thanks for point out where to download the binary file
