### ISSUE TITLE
state / credential files created with excessive permissions

### ISSUE THREAD

**Issue by dcarosone** [atuinsh/atuin#1250]
(as discussed in Discord)

**Describe the bug**

Files in `.local/share/atuin/`, including keys and session tokens, are created with too-open permissions (ie, world-readable)

**To Reproduce**
1. Install atuin and go through the setup on a new host
2. Look at the file permissions.

**Expected behavior**
A umask set so that all files are created mode 600.  Perhaps also something to fix existing installations.

I'm not sure what the equivalent is on Windows, but that should be checked too.

**Error logs**

```text
❯ l .local/share/atuin/
total 1.1M
drwxr-xr-x  2 dan users   14 Sep 23 17:01 .
drwx------ 55 dan users   57 Sep 23 17:05 ..
-rw-r--r--  1 dan users 260K Sep 23 10:40 history.db
-rw-r--r--  1 dan users  32K Sep 23 17:13 history.db-shm
-rw-r--r--  1 dan users 2.9M Sep 23 17:13 history.db-wal
-rw-r--r--  1 dan users   32 Sep 22 21:49 host_id
-rw-r--r--  1 dan users   72 Sep 23 17:01 key
-rw-r--r--  1 dan users   35 Sep 23 17:04 last_sync_time
-rw-r--r--  1 dan users   35 Sep 23 16:59 last_version_check_time
-rw-r--r--  1 dan users    6 Sep 23 16:59 latest_version
-rw-r--r--  1 dan users  32K Sep 23 17:03 records.db
-rw-r--r--  1 dan users  32K Sep 23 17:13 records.db-shm
-rw-r--r--  1 dan users  53K Sep 22 21:49 records.db-wal
-rw-r--r--  1 dan users   32 Sep 23 17:01 session
```

In this case, the parent directory has permissions that protect everything underneath it, but we shouldn't rely on that being the case on all platforms.

**Device (please complete the following information):**
 - OS: :Linux / NixOS
 - Shell: bash/nu
 - Version: 16.0.0

**Comment by bjornfor** [comment]
Sorry for a "mee too" post, but I'm a 5 minute Atuin user and was about to create a new issue about this. Seeing as there hasn't been any activity here I think a bump is in order.

My setup also has limited access in the parent directories, but that shouldn't be relied on (as OP says).

```
$ namei -l /home/bf/.local/share/atuin/key
f: /home/bf/.local/share/atuin/key
drwxr-xr-x root root  /
drwxr-xr-x root root  home
drwx------ bf   users bf
drwx------ bf   users .local
drwx------ bf   users share
drwxr-xr-x bf   users atuin
-rw-r--r-- bf   users key
```
