### ISSUE TITLE
missing field history when syncing new machine

### ISSUE THREAD

**Issue by janosimas** [atuinsh/atuin#1257]
**Describe the bug**
Probably related to #976 

I'm trying to sync with a local server and I'm getting this error.
- It's a fresh installation of atuin using zsh.
- Docker (compose) for the self hosted server with default configuration
- The pc where the server is running can sync
- The remote pc has this issue

**Error logs**

```
$ atuin sync
Error: error decoding response body: missing field `history` at line 1 column 50

Caused by:
    missing field `history` at line 1 column 50

Location:
    /home/runner/work/atuin/atuin/atuin-client/src/api_client.rs:179:23
```

**Device (please complete the following information):**
 - OS: Ubuntu
 - Shell: zsh
 - Version: 20.04

**Self hosted**
Self hosted using the docker compose instructions and default configuration

**Additional context**
I tried removing the local history from both machines and restart the server but the error continues.

**Comment by janosimas** [comment]
I did some tests and I can only sync with the pc I used to register.
If I delete the account and register with the other pc, that one starts to work but the other starts to fail.

**Comment by conradludgate** [comment]
Actually, I think we saw this error before with self hosted atuin. Can you run the [v16](https://github.com/atuinsh/atuin/pkgs/container/atuin/116334431?tag=16.0) tag instead of `main`? We had a regression recently and I haven't got around to fixing it yet

**Comment by janosimas** [comment]
> What version of atuin are you running on both the clients and the servers?

Both are in the same version:
```
$ atuin --version
atuin 16.0.0
```

**Comment by janosimas** [comment]
> Can you run the [v16](https://github.com/atuinsh/atuin/pkgs/container/atuin/116334431?tag=16.0) tag instead of main?
I'll try this later

**Comment by filviu** [comment]
> Actually, I think we saw this error before with self hosted atuin. Can you run the [v16](https://github.com/atuinsh/atuin/pkgs/container/atuin/116334431?tag=16.0) tag instead of `main`? We had a regression recently and I haven't got around to fixing it yet

Ah, thank you ! I had the same issue and I kept getting to #976 which didn't help. I didn't realize it's my server update triggering this.
