### ISSUE TITLE
docker image not working on armv7l (ODROID-XU4)

### ISSUE THREAD

**Issue by b2ag** [atuinsh/atuin#1275]
When I try to run the atuin docker image on my ODROID-XU4 it fails:
```
> podman run -d ghcr.io/ellie/atuin:latest server start
Error: choosing an image from manifest list docker://ghcr.io/ellie/atuin:latest: no image found in image index for architecture arm, variant "v7", OS linux
```
```
> uname -a
Linux shelly 4.14.180-3-ARCH #1 SMP PREEMPT Sat Jun 5 22:29:47 UTC 2021 armv7l GNU/Linux
```

**Comment by ellie** [comment]
I just merged this PR, which should help: https://github.com/atuinsh/atuin/pull/1276. Thanks @rriski!

If the build ends up being slow + unreliable again however, I will be reverting it once more. Until we have a dedicated ARM builder for docker, that is likely to be the case.

Ref: https://github.com/actions/runner-images/issues/5631

**Comment by b2ag** [comment]
Thanks for you quick response. Problem is I'm talking about ARMv7 32 bit instruction set architecture. The linked pull request talks about 64 bit architecture, I guess AArch64, like in ARMv8 and ARMv9. I run older hardware. 

Any chance you could support linux/arm32 as well?

**Comment by ellie** [comment]
Ah I see. It's very unlikely we will ever build for 32 bit platforms, ARM or otherwise I'm afraid.

**Comment by b2ag** [comment]
Then I have to continue to figure out how to build it myself. No biggy.
