### ISSUE TITLE
Database error UNIQUE Constraint failed code 2067

### ISSUE THREAD

**Issue by ohare93** [atuinsh/atuin#1298]
**Describe the bug**
Trying to sync atuin, and I get the below error. I have been running the server for a few months with no issues until now.

**To Reproduce**
1. Run `atuin sync`

**Expected behavior**
It syncs.

**Error logs**
Linux (in Windows WSL) gets this error:
```
> atuin sync
Error: error returned from database: (code: 2067) UNIQUE constraint failed: history.timestamp, history.cwd, history.command

Caused by:
    (code: 2067) UNIQUE constraint failed: history.timestamp, history.cwd, history.command

Location:
    /home/runner/work/atuin/atuin/atuin-client/src/sync.rs:99:13
```

Yet the command completes successfully on my VSCodeServer docker instance 🤔 I am running zsh on both

**Device (please complete the following information):**
 - OS: Windows (but runing the command on WSL)
 - Shell: zsh
 - Version: 15

**Self hosted**
Atuin server is running in Docker on my Unraid server.

**Additional context**
Seems related to #947. Made a new issue since this happens on a different command at a different part of the code.

**Comment by ohare93** [comment]
Ah my VSCode Server was on version 16. Bumping my other environment from 15 to 16 fixed this 👍 Seems weird though

**Comment by ellie** [comment]
We generally maintain strong backwards compatibility server to client (atuin server v16 supports client 0.7.0!), but you'll need to ensure your server is running the latest version wherever possible. 

Servers do not have a forwards comp ability guarantee

**Comment by ohare93** [comment]
Oh I wasn't referring to the version of my Atuin Server docker image, I never changed that. I have been running latest there. The version of Atuin that was installed on Linux running in my docker container for "VSCode Server" was 16, whereas my Windows machine (but in WSL) had version 15 and bumping that to 16 fixed the issue for me.

Unrelatedly, I just went to make sure my Atuin Server container was pegged to a version rather than latest so it doesn't get updated as a surprise, but I see there is a mismatch:
- https://github.com/atuinsh/atuin/pkgs/container/atuin/versions?filters%5Bversion_type%5D=tagged is the link listed on the packages page of the repo here and it goes up to 16
- But the ghcr.io link for the docker image resolution takes me to https://github.com/users/ellie/packages/container/atuin/versions?filters%5Bversion_type%5D=tagged which only goes as high as 15 🤔 is there no version 16 for the server? Or are they unrelated?

**Comment by ohare93** [comment]
Huh, just did some playing around with deploying different versions of the server image: only the tag "main" works 🙈 all other images just constantly restart in Docker, presumably due to my existing data.
