### ISSUE TITLE
Add shortcut to copy current selection to clipboard

### ISSUE THREAD

**Issue by yuvipanda** [atuinsh/atuin#130]
Often I'm browsing my history to copy paste a command to someone else. Right now, I've to select it, hit enter, then copy paste it with my mouse. Instead, would be great to copy it directly with a keyboard shortcut

**Comment by bl-ue** [comment]
In my terminal (VS Code's integrated terminal), a few minutes ago, I had to right click each word individually because I couldn't even select the full line, so this would be _really_ useful 😆

**Comment by yuvipanda** [comment]
@bl-ue haha, that's *exactly* what made me do this too :D Also on vscode's integrated terminal. I hit 'enter' and then selected the full line from the prompt.

Question is if we should close atuin after a copy is done. I think it should just stay open.

**Comment by ellie** [comment]
I'd go for staying open!
