### ISSUE TITLE
Can't sync on new machines

### ISSUE THREAD

**Issue by ScuttleSE** [atuinsh/atuin#1300]
**Describe the bug**
After installing and "activating" atuin on two machines with bash, I can not sync them

```
0/0 up/down to record store
Error: error decoding response body: missing field `history` at line 1 column 50

Caused by:
    missing field `history` at line 1 column 50

Location:
    /home/runner/work/atuin/atuin/atuin-client/src/api_client.rs:175:23
```

My initial machine was running atuin just fine. Added machines 2 and 3, did "atuin login", then "atuin import bash" and then tried to use "atuin sync" which resulted in the above error

 - Version [16.0.0]

**Self hosted**
Docker instance running ghcr.io/atuinsh/atuin:16.0

**Comment by ellie** [comment]
Please run the server with ATUIN_LOG=debug and share any logs. It is more than likely erroring with some of your input
