### ISSUE TITLE
filter_mode_shell_up_keybinding setting has no effect

### ISSUE THREAD

**Issue by thatguy7** [atuinsh/atuin#1306]
**Describe the bug**
I want to set `filter_mode_shell_up_keybinding = "directory"`, but nothing happens if I do. `filter_mode = "global"` determines what filter mode I start out in - both if I use CTRL+R or Up.

**To Reproduce**
1.  configure `filter_mode_shell_up_keybinding = "directory"`
2.  configure `filter_mode = "global"`
-> mode on Arrow up and CTRL+R is global

1.  configure `filter_mode_shell_up_keybinding = "directory"`
2.  configure `filter_mode = "host"`
-> mode on arrow up and CTRL+R is "host"

**Expected behavior**
I wanted to try the default filter mode on arrow-up to be "directory".

**Error logs**
No error logs.

**Device (please complete the following information):**
 - OS: [WSL2/Ubuntu22.04.3 LTS]
 - Shell [fish]
 - Version [16.0.0]

I tried bash as well - same behaviour.

**Self hosted**
No server at all.

**Comment by conradludgate** [comment]
Can you try `filter_mode_shell_up_key_binding = "directory"`, with the `_` between `key_binding`?

**Comment by ellie** [comment]
https://atuin.sh/docs/config/#filter_mode_shell_up_key_binding

As @conradludgate said, you're missing an _ 😁

**Comment by thatguy7** [comment]
Oh man, that was it. (╯°□°）╯︵ ┻━┻

In my defense, I only uncommented the line in the default settings file - I did not actually type it out. So not sure how that happened.

Anyhow, thank you guys a lot. I install atuin on all my machines ever since I discovered it.
