### ISSUE TITLE
Investigate using BLE instead of bash-preexec

### ISSUE THREAD

**Issue by ellie** [atuinsh/atuin#1321]
Bash does not provide the shell hooks we need out of the box. So, tools like bash preexec fill that gap. We install it as part of our bash install. BLE is a line editor for bash, totally written in bash, and may work better for us than the preexec plugin. We would still need to support both, but could default to BLE.

I haven't tried it out yet (and don't daily drive bash), so I'm not sure what other side effects it may have. There is a possibility it might cause issues with commonly used bash extensions

https://github.com/akinomyoga/ble.sh

Install: https://github.com/atuinsh/atuin/blob/b74ed756e2542d330be81ee841407fe263453d42/install.sh#L194
Shell: https://github.com/atuinsh/atuin/blob/b74ed756e2542d330be81ee841407fe263453d42/atuin/src/shell/atuin.bash#L35

**Comment by akinomyoga** [comment]
I guess this can be closed now?

**Comment by ellie** [comment]
It can indeed, thanks
