### ISSUE TITLE
atuin responds with a 404 if contacted via IP address

### ISSUE THREAD

**Issue by offbyone** [atuinsh/atuin#1322]
**Describe the bug**
When I set my atuin `sync_address` to an IP address, or use `localhost` over ssh remote port forwarding, atuin responds with a 404 instead of the server response.

**To Reproduce**

Set the atuin sync server to `http://100.87.119.29:80` and attempt an `atuin status`: 

```shellsession
$ atuin status
Error: failed to get status (are you logged in?)

Location:
    /tmp/atuin-20230807-6694-2we6xt/atuin-16.0.0/atuin-client/src/api_client.rs:143:13
```

1. Confirm that atuin is working at the expected location: `curl http://atuin/` --> gives the version/homage JSON
2. Attempt to connect using curl at the IP: `curl 100.87.119.29:80` --> gives a 404 error
3. Set the `Host` header with curl: `curl -H 'Host: atuin' 100.87.119.29:80` --> gives the version/homage JSON

**Expected behavior**
Accessing atuin via the 

**Error logs**
Please try and provide error logs where possible

**Device (please complete the following information):**
 - OS: Linux (github codespaces)
 - Shell zsh
 - Version 16.0.0

**Self hosted**

Yep, it's self-hosted; I'm running the docker image behind `tailscale serve` on ports 80 and 443

**Additional context**

```shellsession
$ curl http://atuin/
{"homage":"\"Through the fathomless deeps of space swims the star turtle Great A'Tuin, bearing on its back the four giant elephants who carry on their shoulders the mass of the Discworld.\" -- Sir Terry Pratchett","version":"16.0.0","total_history":35472}
$ curl 100.87.119.29:80
404 page not found
$ curl -H 'Host: atuin' 100.87.119.29:80
{"homage":"\"Through the fathomless deeps of space swims the star turtle Great A'Tuin, bearing on its back the four giant elephants who carry on their shoulders the mass of the Discworld.\" -- Sir Terry Pratchett","version":"16.0.0","total_history":35472}
$ gh codespace ssh -c <codespace> -R 3123:atuin:80
# curl -H "Host: atuin" http://localhost:3123/
{"homage":"\"Through the fathomless deeps of space swims the star turtle Great A'Tuin, bearing on its back the four giant elephants who carry on their shoulders the mass of the Discworld.\" -- Sir Terry Pratchett","version":"16.0.0","total_history":35472}
# curl http://localhost:3123/
404 page not found
```

I can confirm that the request at the IP is coming to the server using logs on the tailscaled that is in front of it.

**Comment by ellie** [comment]
Are you sure this is not an caused by `tailscale serve`?

Eg

```
atuin server start
curl http://127.0.0.1:8888
```

Responds as expected

**Comment by ellie** [comment]
I just started an atuin server on my home server, and tried

```
curl http://minerva:888 
curl http://192.168.1.blah
curl http://100.87.92.2:8888
```

and all succeeded successfully. The latter was running over tailscale, just not `tailscale serve`.

I then tried `tailscale serve`. As expected, `http://minerva` was fine. `http://100.87.92.2` was not. I think this is related to Tailscale, and not Atuin.

`tailscale serve status` shows that it is _only_ listening on `http://minerva`, and not `http://100.87.92.2`

**Comment by offbyone** [comment]
Oh dang... that would make sense.

**Comment by offbyone** [comment]
Confirmed; I can access atuin via its internal port just fine; this is a "whoops, I done it to myself" bug. Thanks!

**Comment by ellie** [comment]
No worries! Glad you got it sorted
