### ISSUE TITLE
[ATUIN 17.0.0] "Error: could not load client settings"

### ISSUE THREAD

**Issue by ShangjinTang** [atuinsh/atuin#1333]
**Describe the bug**

output error:
```plain
Error: could not load client settings

Caused by:
    failed to deserialize: enum SearchMode does not have variant constructor 

Location:
    atuin-client/src/settings.rs:432:26
```

**To Reproduce**
1. download atuin 17.0.0 [atuin-v17.0.0-x86_64-unknown-linux-musl.tar.gz](https://github.com/atuinsh/atuin/releases/download/v17.0.0/atuin-v17.0.0-x86_64-unknown-linux-musl.tar.gz)
2. extract
3. run any autin command, e.g. `atuin --version` or `eval $(atuin init zsh)`, or press Ctrl-R

Also history cannot work properly.

**How to resolve this issue**
Currently I do not figure out how to do resolve this issue.
I've just scrolled back to v16.0.0.

**Expected behavior**
1. No error code
2. history works properly

**Error logs**
No error logs provided

**Device (please complete the following information):**
 - OS: [Ubuntu 22.04 LTS]
 - Shell [zsh 5.8.1]; also I switched to bash 5.1.16, and execute `eval $(atuin init bash)`, same issue on bash
 - Version [17.0.0]

**Self hosted**
I do not use this self hosted feature.

**Comment by conradludgate** [comment]
That was fast

**Comment by ellie** [comment]
Are you able to share your config file please? I can't replicate this

**Comment by ShangjinTang** [comment]
> Are you able to share your config file please? I can't replicate this

I only have these three settings in my configuration.

```bash
> grep -v "^#" ~/.config/atuin/config.toml

style = "compact"
inline_height = 12
search_mode_shell_up_key_binding = ""
```

**Comment by conradludgate** [comment]
I was just about to say "do you have `search_mode = ""`" 😅

**Comment by ellie** [comment]
Could you remove `search_mode_shell_up_key_binding = ""` please? 

What are you trying to configure with that option?

**Comment by conradludgate** [comment]
This only worked incidentally on v16 because v16 doesn't support that configuration

**Comment by ShangjinTang** [comment]
> Could you remove `search_mode_shell_up_key_binding = ""` please?
> 
> What are you trying to configure with that option?

Atuin 17.0.0 works after removing `search_mode_shell_up_key_binding = ""`, thanks.

Also I noticed the UP-Key setting is not bound to history on 17.0.0.

**Comment by conradludgate** [comment]
Hmm, it works for me on zsh. What's your zsh setup?

**Comment by ShangjinTang** [comment]
> Hmm, it works for me on zsh. What's your zsh setup?

Hello, I do not think this issue is related to zsh
1. I disabled all the zsh plugins, the issue still exists.
2. I switched to bash on my same envrionment, the issue also exists if there is configuration `search_mode_shell_up_key_binding = ""`

**Comment by ellie** [comment]
You edited away what Conrad was referring to, unless I'm confused:

> Also I noticed the UP-Key setting is not bound to history on 17.0.0.

Looking at your dotfiles, you are disabling the up arrow binding. This means the up arrow not working is expected behaviour

**Comment by ShangjinTang** [comment]
> You edited away what Conrad was referring to, unless I'm confused:
> 
> > Also I noticed the UP-Key setting is not bound to history on 17.0.0.
> 
> Looking at your dotfiles, you are disabling the up arrow binding. This means the up arrow not working is expected behaviour
> 
> https://github.com/ShangjinTang/dotfiles/blob/3b8d565fa25e3fbe170fd3cd1bd1c3e162639e97/configs/zsh/zshrc.post#L50

Yes, the reason I disabled up-arrow key is:
- When I use `Ctrl-R`, I want to use fuzzy match (as `fzf`)
- When I use `Up`, I want to use prefix-exact-match automatically without manually add `^` before the search word. (as zsh-autosuggestions)

**Comment by ellie** [comment]
> When I use Up, I want to use prefix-exact-match automatically without manually add ^ before the search word. (as zsh-autosuggestions)

```
search_mode_shell_up_key_binding = "prefix"
```

would achieve this.

**Comment by ShangjinTang** [comment]
> search_mode_shell_up_key_binding

Many thanks!
