### ISSUE TITLE
Import get SESSIONS not found

### ISSUE THREAD

**Issue by lucasjinreal** [atuinsh/atuin#1343]
<img width="1015" alt="image" src="https://github.com/atuinsh/atuin/assets/21303438/516b4da9-fc6f-4c87-8d7f-b19eeb725f68">

**Comment by ellie** [comment]
Hey! Have you installed our shell integration? It should look something like this in your zshrc

```
eval "$(atuin init zsh)"
```

You'll need to restart your shell afterwards.

`ATUIN_SESSION` is set when your shell starts, so that we can track commands that originate in the same shell session

**Comment by lucasjinreal** [comment]
@ellie  the readme can not see anywhere clearly bold place says this step, I thought it was done by `atuin import auto`?
if not, should I manually add to zshrc?

BTW, will powershell support in the future?

**Comment by ellie** [comment]
If you're using the install script, your shell will be setup for you and all you need to do is restart it - detailed [here](https://github.com/atuinsh/atuin#with-the-default-sync-server)

If you're not, the [advanced install](https://github.com/atuinsh/atuin#shell-plugin) details setting it up

Our [getting started](https://atuin.sh/docs) guide covers this too!

> BTW, will powershell support in the future?

#84
