### ISSUE TITLE
Many commands do nothing after enabling enter_accept (fish shell)

### ISSUE THREAD

**Issue by mishamsk** [atuinsh/atuin#1353]
**Describe the bug**
After enabling `enter_accept` (existing user), pressing enter on any `which executable_name`, or `pwd`, or `echo "test"` commands in the history returns without actually executing a command

Some commands do work (e.g. `cd`)

**To Reproduce**
1. start a new shell
2. execute `which python`
3. invoke atuin history
4. press enter

**Expected behavior**
Command executes

**Error logs**
Please try and provide error logs where possible

**Device (please complete the following information):**
 - OS: macOS Venture 13.6
 - Shell fish
 - Version 17.0.0

**Additional context**
For other commands that I've tested, the command is printed with spurious prefix (reported in #1335), but for those that do not work nothing is printed at all.

**Comment by arcuru** [comment]
The output is likely being overwritten by the repainting of your prompt, all the commands you listed have a single line of output. #1341 should fix I think.

**Comment by mishamsk** [comment]
@arcuru yeah, it seems so. doing something like `ls -la` with long input has 2 last lines cut, and my prompt is indeed 2 lines high.

I am not a big expert with fish, but looking at #1341 diff - is it even necessary to call repaint after eval? As far as I can tell fish repaints the prompt after executing eval (at least in interactive mode - running `eval cd ..` changes the prompt for me (mine has the path)

**Comment by conradludgate** [comment]
@ellie shall we release a patch?

**Comment by ellie** [comment]
> @ellie shall we release a patch?

Yeah gonna do it tomorrow morning

**Comment by ellie** [comment]
actually I lied might just do it now 🤷‍♀️

**Comment by arcuru** [comment]
> I am not a big expert with fish, but looking at https://github.com/atuinsh/atuin/pull/1341 diff - is it even necessary to call repaint after eval? As far as I can tell fish repaints the prompt after executing eval (at least in interactive mode - running eval cd .. changes the prompt for me (mine has the path)

Running `eval` in interactive mode sends a command that contains eval, so fish runs the command and then repaints for the next one. Running `eval` in this script just shows the output of a command, but doesn't trigger fish's normal "command loop". We're effectively faking a command here. It's odd because this script is called from a binding, which isn't treated the same way as a command by fish.

So the short answer is yes, we need the repaint otherwise the prompt never gets redrawn.
