### ISSUE TITLE
cli-clipboard breaks illumos builds

### ISSUE THREAD

**Issue by papertigers** [atuinsh/atuin#1361]
With the addition of #1249 illumos no longer builds due to the lack of support in `cli-clipboard`.

Would you be opposed to hiding clipboard support behind a feature flag with it being in the default feature list.  That would allow us to easily turn it off in our package build system.

In the meantime I started looking at adding support to the other crate but my initial pass wasn't promising.

**Comment by ellie** [comment]
I didn't know we were building on Illumos in the first place, awesome! Thanks for flagging this.

Totally happy to feature gate this, so long as it's defaulting to enabled. Would you be comfortable making a PR there?

**Comment by papertigers** [comment]
Fixed in #1825
