### ISSUE TITLE
Activity graph stopped working

### ISSUE THREAD

**Issue by PrayagS** [atuinsh/atuin#1369]
As per the instructions given here (https://github.com/atuinsh/atuin?tab=readme-ov-file#opt-in-to-activity-graph), I had generated the URL for my shell activity graph.

It worked fine for a few days but since the last couple of days, the API returns a 404.

```sh
❯ curl https://api.atuin.sh/enable -d 'xxx'
{"detail":"Not found."}
```

The image URL that I previously had also returns the same 404 response now.

**Comment by ellie** [comment]
Ah, it needed restarting following some database work I've been doing 🤦‍♀️ Should be fine now! Sorry about that.

**Comment by philn** [comment]
Hi Ellie, this issue is still happening, I'm afraid :) Same error as in original bug description.

**Comment by PrayagS** [comment]
> Hi Ellie, this issue is still happening, I'm afraid :) Same error as in original bug description.

+1. Seeing issues on my end as well

**Comment by PrayagS** [comment]
@ellie Ping in case this was missed

**Comment by ellie** [comment]
In the end, it was DNS. Ended up pointing at the wrong machines. I've fixed it now and all should be well again. Sorry again for this, took way too long!
