### ISSUE TITLE
Atuin intercepting line feed  (\n) when trying to type a password into the mysql shell and replacing them with carriage return (\r) when enter_accept = true

### ISSUE THREAD

**Issue by daleevans** [atuinsh/atuin#1371]
**Describe the bug**
When trying to type a password into the MySQL shell with a command like

mysql -u myuser -p -h host.domain.com

Somehow, this results in \n characters being replaced by \r.  I verified this by stracing the mysql process, which ends up reading from file descriptor 3 (to avoid echoing characters to the screen I assume).  Oddly, it also seems to read characters one at a time instead of as a whole line.  It also intercepts other special characters that it shouldn't be seeing, like when I hit the up arrow.

**To Reproduce**
Try to log in to a mysql server using the mysql client program with enter_acept = true.  It works fine with enter_accept = false.

**Expected behavior**
It logs in successfully.

**Error logs**

with atuin enabled
```
$ strace -p 423839
strace: Process 423839 attached
read(3, "b", 4096)                      = 1
read(3, "l", 4096)                      = 1
read(3, "a", 4096)                      = 1
read(3, "h", 4096)                      = 1
read(3, "\r", 4096)                     = 1
read(3, 
```

without atuin

```
read(3, "blahblah\n", 4096)             = 9
write(3, "\n", 1)                       = 1
```

Please try and provide error logs where possible

**Device (please complete the following information):**
 - OS: debian
 - Shell bash
 - Version 17.0.1

**Comment by arcuru** [comment]
Hmm, `enter_accept` in all the shells other than `zsh` is basically a hack (See the fish complaint at #1353). I am surprised at that behavior you're seeing though.

Do you see that behavior when you **type** that command or when you use **enter_accept** to run the command out of your history? Or both? When we run from history using `enter_accept` we're running it using `eval` which may be causing problems.

> It also intercepts other special characters that it shouldn't be seeing, like when I hit the up arrow.

This is atuin's up-arrow binding, which you can disable using `atuin init bash --disable-up-arrow`. It applies at basically all times in bash AFAIK. It is more restricted on when it triggers for the other shells but not for bash e.g. https://github.com/atuinsh/atuin/pull/1359

**Comment by daleevans** [comment]
It only happens if I hit enter to run from the history.  If I just type the command in directly, it works fine.

**Comment by ellie** [comment]
We've backed out support for enter_accept on bash in `main`, as honestly it doesn't seem likely we will be able to get it into an acceptable state
