### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by a-b** [atuinsh/atuin#1374]
**Describe the bug**
There is no clear way to change password

**To Reproduce**
1. Register with shitty password
1. You're screwed

**Expected behavior**
Account command let user change or rotate password. This flow is documented

**Error logs**
Please try and provide error logs where possible

**Device (please complete the following information):**
 - OS: [e.g. macOS]
 - Shell [bash/zsh/fish/nu]
 - Version [e.g. 16.0.0]

**Self hosted**
If you are self hosting Atuin server, please detail your setup here. What version are you using, and how is it deployed?

**Additional context**

**Comment by adamryczkowski** [comment]
I believe that there are two potential walkarounds, until a cli supports this:

1. A magic Postgres update query. @ellie  - can you help with that?
2. A way to delete or rename a user on the server side.

**Comment by ellie** [comment]
I won't be running any Postgres queries for this, but you can run

`atuin account delete`

And then re register

I'll try and get this one fixed for the next release, unless anyone else fancies having a go! It should be quite straightforward
