### ISSUE TITLE
Can't take input in ssh

### ISSUE THREAD

**Issue by AlexeyMatskevich** [atuinsh/atuin#1379]
**Describe the bug**
After connecting via ssh to a remote server, I can't enter commands in shell. Sometimes commands are entered, but are not displayed until I press enter.

**To Reproduce**
1. cargo install atuin
2. curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o ~/.bash-preexec.sh
3. echo '[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh' >> ~/.bashrc
4. echo 'eval "$(atuin init bash)"' >> ~/.bashrc
5. source ~/.bashrc and reopen console
6. atuin import auto
7. test that atuin work (success for me)
8. ssh domain.example.com -p 9999

**Expected behavior**
It is expected that input is displayed and entered as normal.

**Error logs**
Please try and provide error logs where possible

**Device (please complete the following information):**
 - OS: Ubuntu 22.04 WSL2 (Windows 11)
 - Shell bash
 - Version 17.0.1

**Additional context**
If I disable atuin, all work
My bashrc
```sh
...
# Some default settings and commands from the system installation are presumed to be bash.
eval "$(~/.rbenv/bin/rbenv init - bash)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
. "$HOME/.cargo/env"

# proto
export PROTO_HOME="$HOME/.proto"
export PATH="$PROTO_HOME/bin:$PATH"
export PATH="$HOME/.moon/bin:$PATH"
# [[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
# eval "$(atuin init bash)"
```

**Comment by ellie** [comment]
Unfortunately we've had issues with our bash implementation, see #1385, #1384, #1372

The solution so far is disabling "enter_accept". In the next version of Atuin this will be disabled for everyone. So

```
enter_accept = false
```

In your Atuin config. If this functionality is something you'd like, it's currently well supported in both ZSH and Fish
