### ISSUE TITLE
emacs shell commands giving output:  bind: Key with name 'up' does not have any mapping

### ISSUE THREAD

**Issue by muralikodali** [atuinsh/atuin#1386]
when i run any shell command in emacs it shows up the following message before giving shell output.

```
bind: Key with name 'up' does not have any mapping
bind: Key with name 'up' does not have any mapping
```

OS: Arch Linux
Shell: fish
Version: 17.0.1

I am not self hosting any atuin server.
 
commenting out ```atuin init fish | source``` giving clean shell output

**Comment by arcuru** [comment]
This is an issue with binding the up keybinding in the emacs terminal, I don't think it supports that. The easiest thing to do is to disable the up arrow keybinding in the "dumb" terminal (or just disable it everywhere):

```fish
if test "$TERM" = "dumb"
    atuin init fish --disable-up-arrow | source
else
    atuin init fish | source
end
```

There are several issues in the fish-shell repo discussing this.

**Comment by muralikodali** [comment]
thanks @arcuru for your suggestion.

with modifying fish configuration as suggested by you, problem is solved.
