### ISSUE TITLE
Activity graph endpoint returns HTTP418 I'm a teapot with a teapot emoji in body instead of link to graph as the docs claim

### ISSUE THREAD

**Issue by BLucky-gh** [atuinsh/atuin#1415]
**Describe the bug**
The docs say to run `curl https://api.atuin.sh/enable -d $(cat ~/.local/share/atuin/session)` to get an activity graph, but the server just responds with a 418

**To Reproduce**
1. run `curl https://api.atuin.sh/enable -d $(cat ~/.local/share/atuin/session)`
2. stare at teapot
3. ponder your and the teapot's existence
4. read the HTCPCP spec

**Expected behavior**
Server should have returned a link to the activity graph

**Device (please complete the following information):**
 - OS: NixOS
 - Shell: any
 - Version: 17.0.1

**Comment by ellie** [comment]
Fixed!

tl;dr is that in moving infra around, some DNS + routing wasn't quite right for the service that generates these. Should now be ok! Sorry about that.
