### ISSUE TITLE
Prometheus metrics should be prefixed with `atuin_`

### ISSUE THREAD

**Issue by onedr0p** [atuinsh/atuin#1434]
Hi 👋🏼 

Thanks so much for adding Prometheus metrics. I have one issue though, it doesn't look like Atuin's metrics are properly prefixed. The below atuin metrics should have an `atuin_` prefix.

<img width="1785" alt="Screenshot_2023-12-10_at_8 27 58_AM" src="https://github.com/atuinsh/atuin/assets/213795/3849f376-872b-4b60-9122-12c5cdbe5d99">

**Comment by ellie** [comment]
Hey! Those metrics are not exposed by Atuin. Our metrics are namespaces either with `atuin`, or with `http`. We should probably label them with a job though :)

You can see the two PRs implementing this

1. https://github.com/atuinsh/atuin/pull/1394
2. https://github.com/atuinsh/atuin/pull/1399

It looks like those metrics are coming from somewhere in your metrics infra

**Comment by onedr0p** [comment]
Ah good call, I was looking in the wrong place. Thanks!
