### ISSUE TITLE
Bug Report: atuin sync -f fails with "missing field hosts" error

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [atuinsh/atuin#1440]
**Summary:**

The `atuin sync -f` command fails with the following error message:

```
Error: error decoding response body: missing field `hosts` at line 1 column 30
Caused by: missing field `hosts` at line 1 column 30
Location: /build/source/atuin-client/src/api_client.rs:265:21
```

**Steps to Reproduce:**

1. Run `atuin sync -f`

**Expected Behavior:**

The `atuin sync -f` command should successfully force the synchronization of the local history with the server.

**Environment:**

* Operating System: Pop!_OS 22.04 LTS
* Atuin Version: 17.0.1

**Comment by ellie** [comment]
A few questions to help sort this

1. Are you self hosting a server? If so, what version is it running + does it have any logs?
2. Have you registered with the server? If so, what's the output of `atuin status`?

**Comment by limaceous-bushwhacker** [comment]
Apologies, I should've mentioned that in OP.

1. No I'm not self-hosting the server.
2. `atuin status` says `Error: failed to get status (are you logged in?)` but `atuin login` says I'm already logged in? (`You are already logged in! Please run 'atuin logout' if you wish to login again`) 

Strange, should I try logging out and then login again?

**Comment by ellie** [comment]
> Strange, should I try logging out and then login again?

Yes please! 

Have you created and deleted an account at any point? If you could let me know what you did after installing atuin that would be super helpful

**Comment by limaceous-bushwhacker** [comment]
Yep, it says `user not found`. Looks like my account got purged or something? I've had this installation for couple months now and ran a manual sync as recent as last week.

**Comment by ellie** [comment]
> Looks like my account got purged or something

No accounts get deleted unless `atuin account delete` is ran or manual deletion is requested. Can you let me know your email/username and I can check what's going on?

Feel free to email (ellie@atuin.sh) or Discord

**Comment by limaceous-bushwhacker** [comment]
DM'd you on Discord yesterday, letting you know in case you missed it.

**Comment by ellie** [comment]
I don't have any DMs from you 😅 Probably best to join the Atuin discord first, then DM me from there

**Comment by matthiasbeyer** [comment]
Okay and what was the issue now?

**Comment by ellie** [comment]
> Okay and what was the issue now?
> 
> 

What do you mean?

**Comment by matthiasbeyer** [comment]
What was the result of your discord discussion about this issue and how is it solved?

**Comment by ellie** [comment]
The author never contacted me
