### ISSUE TITLE
No link for the support forum

### ISSUE THREAD

**Issue by adamryczkowski** [atuinsh/atuin#1442]
**No place to report problems with installation**
I would normally post the problem in the Github issue tracker, except that bug report clearly states that "Unless you are absolutely certain this is a bug, please open a post on the support forum first". 

Searching for "support forum" or even for "support" in the README.md and in the main page atuin.sh returns nothing. 

I suspect the forum used to exist some time ago, got removed, but the reference to it remained.

**Comment by ellie** [comment]
Ah yes! Thanks!

It's a very recent and I thought I'd added it to the README. Will do now.
