### ISSUE TITLE
Error: could not load server settings when following the self-hosted server install

### ISSUE THREAD

**Issue by adamryczkowski** [atuinsh/atuin#1443]
I pulled the vanilla Ubuntu 22.04 image, and tried to follow the self-hosting recipe to the letter. Got the following errors:

```
postgresql_1  | The files belonging to this database system will be owned by user "postgres".
postgresql_1  | This user must also own the server process.
postgresql_1  | 
atuin_1       | Error: could not load server settings
atuin_1       | 
atuin_1       | Caused by:
atuin_1       |    0: failed to create file `/config/server.toml`
atuin_1       |    1: Permission denied (os error 13)
atuin_1       | 
atuin_1       | Location:
atuin_1       |     /app/atuin-server/src/settings.rs:62:28
postgresql_1  | The database cluster will be initialized with locale "en_US.utf8".
postgresql_1  | The default database encoding has accordingly been set to "UTF8".
postgresql_1  | The default text search configuration will be set to "english".
postgresql_1  | 
postgresql_1  | Data page checksums are disabled.
postgresql_1  | 
postgresql_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgresql_1  | creating subdirectories ... ok
postgresql_1  | selecting dynamic shared memory implementation ... posix
postgresql_1  | selecting default max_connections ... 100
postgresql_1  | selecting default shared_buffers ... 128MB
postgresql_1  | selecting default time zone ... Etc/UTC
postgresql_1  | creating configuration files ... ok
postgresql_1  | running bootstrap script ... ok
postgresql_1  | performing post-bootstrap initialization ... ok
postgresql_1  | syncing data to disk ... ok
postgresql_1  | 
postgresql_1  | 
postgresql_1  | Success. You can now start the database server using:
postgresql_1  | 
postgresql_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgresql_1  | 
postgresql_1  | initdb: warning: enabling "trust" authentication for local connections
postgresql_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgresql_1  | --auth-local and --auth-host, the next time you run initdb.
postgresql_1  | waiting for server to start....2023-12-12 21:39:07.671 UTC [50] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgresql_1  | 2023-12-12 21:39:07.681 UTC [50] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql_1  | 2023-12-12 21:39:07.715 UTC [51] LOG:  database system was shut down at 2023-12-12 21:39:07 UTC
postgresql_1  | 2023-12-12 21:39:07.737 UTC [50] LOG:  database system is ready to accept connections
postgresql_1  |  done
postgresql_1  | server started
postgresql_1  | CREATE DATABASE
postgresql_1  | 
postgresql_1  | 
postgresql_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgresql_1  | 
postgresql_1  | 2023-12-12 21:39:08.651 UTC [50] LOG:  received fast shutdown request
atuin_atuin_1 exited with code 1
```

I suspect the problem is caused by the fact, that the server wants to store the configuration in the `/config/server.toml` rather than in the local `~/.config/atuin/server.toml`. If that is the case, how should I re-configure it?

I just want to set up a private instance of the atuin server. Probably I would have been able to fix the problem myself if I knew Docker better. 

## To reproduce:

1. Install vanilla Ubuntu 22.04 image as a start (I used an LXC instance)
2. Install `docker-compose` and some text editor
3. `mkdir -p ~/.config/atuin`
4. Create a file `~/.config/atuin/server.toml` with the following content:
```
host = "0.0.0.0"
port = 8888
open_registration = true
db_uri="postgres://atuin:secret_password@postgress/atuin"
```
5. Clone the atuin repository and enter it
6. Make the file `docker-compose.env` with the following content:
```
ATUIN_DB_USERNAME=atuin
# Choose your own secure password
ATUIN_DB_PASSWORD=secret_password
```
7. Edit the file `docker-compose.yml`, replacing it with the template hosted on https://atuin.sh/docs/self-hosting/docker or just edit the `$ATUIN_DB_USERNAME` and `$ATUIN_DB_PASSWORD`. 
8. Execute `docker-compose up` and watch the error.

For reference, I have recorded my session on https://asciinema.org/a/HE9n40Kp2OaMcawlvcMgHrfJw . 

Is there any easier way to do a server install? There is an `atuin server` sub-command to the atuin. I failed to find any documentation about how to make it work with remote connections and how to let it use the database. I am also confused about who is responsible for setting up the Postgres server. Judging the debug output of the docker-compose, it seems as if the database is boundled with the docker container of the atuin server. On the other hand, running the `docker run -v "$HOME/.config/atuin:/config" ghcr.io/atuinsh/atuin:latest server start` fails with the error 

```
Error: failed to connect to db: PostgresSettings { db_uri: "postgres://atuin:secret_password@postgress/atuin" }
...
```

...just as if the onus to install the database was on me.

**Comment by ellie** [comment]
The docker compose file is mapping `./config` to the path where it is looking for the config

See

```
volumes:
      - "./config:/config"
```

If you check the directory where you ran `docker compose up`, you'll see the files created by the containers.

Please ensure the permissions on that directory are setup OK. You may need to check UID values, but that depends on your system.

> I suspect the problem is caused by the fact, that the server wants to store the configuration in the /config/server.toml rather than in the local ~/.config/atuin/server.toml

/config/server.toml inside of the container, not on your host system. This is mapped onto the host by your volume mounts

> Is there any easier way to do a server install? 

What are you familiar with?

Running `atuin server start` will read the config from `~/.config/atuin/server.toml` on your host machine. It's up to you to setup and maintain a postgres server, rent an RDS machine, whatever. I'd like to support sqlite on the server in the future, but that's not there right now.

I'm really sorry to seem harsh, but I'm going to close this issue as it's self hosting support + neither a bug nor feature request for Atuin. If you need support operating Atuin, please check out the [Discord](https://discord.gg/Fq8bJSKPHh) or the [Forum](https://forum.atuin.sh/).
