### ISSUE TITLE
Error: error sending request for url (https://api.atuin.sh/record)

### ISSUE THREAD

**Issue by fdelacruz** [atuinsh/atuin#1453]
I get this upon first `atuin sync`
Error: error sending request for url (https://api.atuin.sh/record): error trying to connect: Connection reset by peer (os error 54)

Caused by:
   0: error trying to connect: Connection reset by peer (os error 54)
   1: Connection reset by peer (os error 54)

Location:
    /private/tmp/atuin-20231216-31550-968tdd/atuin-17.1.0/atuin-client/src/api_client.rs:264:20

**Comment by fdelacruz** [comment]
If i go to that url directly i then see `{"reason":"missing authorization header"}`

**Comment by fdelacruz** [comment]
What am I missing?

**Comment by ellie** [comment]
>  Error: error sending request for url (https://api.atuin.sh/record): error trying to connect: Connection reset by peer (os error 54)

Does this still happen if you retry? It sounds like some sort of network error.

> If i go to that url directly i then see {"reason":"missing authorization header"}

The URL should only be called by `atuin`, and requires auth

**Comment by fdelacruz** [comment]
I guess it finally syncs if I keep trying. No sure, but it says 0/0 up/down to record store.
<img width="573" alt="Screen Shot 2023-12-16 at 8 10 58 PM" src="https://github.com/atuinsh/atuin/assets/148098/ab88a76c-fb32-457a-ae9f-bcd33436fedb">

**Comment by fdelacruz** [comment]
How would I know for sure?
Would this happens when it syncs auto?
Is there any sort of web interface?

**Comment by ellie** [comment]
> How would I know for sure?

If it completes and says "Sync complete!", as it does in your screenshot, then you're all OK.

> I guess it finally syncs if I keep trying. 

How many times did you have to try? Did you get the same error every time? if not, looks like some sort of network issue on your machine

>  Would this happens when it syncs auto?

It depends on why it happened here

>  Is there any sort of web interface?

No, not yet

**Comment by fdelacruz** [comment]
Would I be able to eventually export my zsh history from this db back into ~/.zsh_history?

**Comment by ellie** [comment]
See #816 

Are you able to provide any more information about the issue here?

**Comment by fdelacruz** [comment]
Ok, I brew uninstalled atuin, but there's  still the process running in the background even after reinstall.
I've searched all the regular locations to no avail:
~/Library/LaunchAgents
/Library/LaunchAgents         
                               
 /Library/LaunchDaemons     

 /System/Library/LaunchAgents   

 /System/Library/LaunchDaemons

**Comment by ellie** [comment]
Probably just a stuck sync process.

killall atuin

Is there anything you're able to tell me about the problem you've had?

**Comment by fdelacruz** [comment]
the only problem i have right now is that i can not uninstall this..it keeps changing process number which is raising all kinds of flags for me

**Comment by ellie** [comment]
Did you try running the command I suggested? 

Please confirm that 

1. The output of "which atuin" is nothing 
2. You do not have the Atuin shell integration in your shell any longer

So far I know

- you've ran sync a whole bunch of times
- you've registered a whole bunch of accounts 
- you had some sort of network issue

Atuin does not run a daemon process, but forks into the background to complete a sync once a command is run. 

> which is raising all kinds of flags for me

I've spent the past few hours trying to follow up on your questions and had nothing but more questions, and now a not-too-nice implication :/

**Comment by ellie** [comment]
Also once you've removed the shell integration, probably best to restart your terminal

**Comment by ellie** [comment]
@fdelacruz that screenshot you just edited the last post to show is only showing the grep process itself. That's not atuin.

**Comment by fdelacruz** [comment]
I'm sorry about that.

> Did you try running the command I suggested?
> 
> Please confirm that
> 
>     1. The output of "which atuin" is nothing
> 
>     2. You do not have the Atuin shell integration in your shell any longer
> 
> 
> So far I know
> 
>     * you've ran sync a whole bunch of times
> 
>     * you've registered a whole bunch of accounts
> 
>     * you had some sort of network issue
> 
> 
> Atuin does not run a daemon process, but forks into the background to complete a sync once a command is run.
> 
> > which is raising all kinds of flags for me
> 
> I've spent the past few hours trying to follow up on your questions and had nothing but more questions, and now a not-too-nice implication :/

I'm sorry about that.
