### ISSUE TITLE
Error: error decoding response body: expected value at line 1 column 1

### ISSUE THREAD

**Issue by azzamsa** [atuinsh/atuin#1462]
Hi. 👋🏼

I am able  to register a new user, login, logout, but when doing `atuin sync` I get the error below.

```bash
~
🦄 atuin sync
Error: error decoding response body: expected value at line 1 column 1

Caused by:
    expected value at line 1 column 1

Location:
    /home/user/.cargo/git/checkouts/atuin-20bcab949c7e5be5/d52e576/atuin-client/src/api_client.rs:318:21

~
🙊
```

I tried to remove my self-hosted database directory, but no luck. Tried to install the CLI from `main` branch but still no luck.

```
~
🦄 atuin --version
atuin 17.1.0

~
🦄 curl 172.104.32.12:8888
{"homage":"\"Through the fathomless deeps of space swims the star turtle Great A'Tuin, bearing on its back the four giant elep
hants who carry on their shoulders the mass of the Discworld.\" -- Sir Terry Pratchett","version":"15.0.0"}⏎
```

Thank you for Atuin! 🎖️

Related:

- https://github.com/atuinsh/atuin/issues/739
- https://github.com/atuinsh/atuin/issues/705
- https://github.com/atuinsh/atuin/issues/504

**Comment by ellie** [comment]
Hey!

Could you upgrade your server please? It's running v15.0.0, and you're running v17.1.0 on the client

It's generally required to keep your server up to date. In the next release, the client will refuse to sync if it is newer than the server

> Thank you for Atuin! 🎖️

Thank you 😊

**Comment by azzamsa** [comment]
I thought `v15` was the latest docker image at the moment, because when I checked https://github.com/users/ellie/packages/container/package/atuin. The recent version is v15

![image](https://github.com/atuinsh/atuin/assets/17734314/83d84a3a-651c-42e5-a05f-a32d3e74673f)

**Comment by ellie** [comment]
Unfortunately when moving a github repo to an org, GitHub doesn't rename or redirect packages

https://github.com/atuinsh/atuin/pkgs/container/atuin

**Comment by azzamsa** [comment]
> Unfortunately when moving a github repo to an org, GitHub doesn't rename or redirect packages
> [atuinsh/atuin/pkgs/container/atuin](https://github.com/atuinsh/atuin/pkgs/container/atuin)

I always thought that the docker image has a different versioning shame, my bad.

```
🦄 atuin sync
0/0 up/down to record store
Sync complete! 41198 items in history database, force: false
```

Thank you so much for your work on Atuin! 🎖️
I hope I can sponsor Atuin in the near future.

**Comment by ellie** [comment]
Glad it's sorted! Thank you 🙏
