### ISSUE TITLE
Forgot my activity graph link

### ISSUE THREAD

**Issue by martynvdijke** [atuinsh/atuin#1471]
I may have forgotten my activity graph link and if I do  `curl https://api.atuin.sh/enable -d $(cat ~/.local/share/atuin/session)` I get a theapot back. 
Am I doing something wrong ?

**Comment by Blonteractor** [comment]
I ran the command for the first time ever and still got a teapot

**Comment by nfacha** [comment]
Also facing the teapot error on the first time
Im either looking on the wrong place, or that route dosent exist: https://github.com/atuinsh/atuin/blob/main/atuin-server/src/router.rs#L110

**Comment by ellie** [comment]
Hey!

It's down atm, and has been for a little while now.

I'll be honest with you - I didn't maintain or scale it as well as the Atuin service. For users with large amounts of history, it often timed out or OOMd.

I'd like to bring it back soon, but it needs more work first - so I won't advertise it on the README until this is sorted

I'm really sorry for the inconvenience

See https://github.com/atuinsh/atuin/pull/1527

**Comment by ellie** [comment]
If there's big demand I'm more than happy to prioritise sorting it!

**Comment by ImSingee** [comment]
@ellie Hope to see this features back👀
