### ISSUE TITLE
fish init error

### ISSUE THREAD

**Issue by cooperspencer** [atuinsh/atuin#1489]
I added `atuin init fish | source` to my ~/.config/fish/config.fish, like it is described in https://atuin.sh/docs/advanced-install#fish

I get the following error:
```
- (line 21): $(...) is not supported. In fish, please use '(ATUIN_SHELL_FIS…)'.
    set -l ATUIN_H "$(ATUIN_SHELL_FISH=t ATUIN_LOG=error atuin search $argv -i -- (commandline -b) 3>&1 1>&2 2>&3)"
                    ^
from sourcing file -
	called on line 3 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
source: Error while reading file “<stdin>”
```

i use atuin version 17.1.0 and fish version 3.3.1

**Comment by cooperspencer** [comment]
just added the official fish repo and updated it to the latest version. now it works.

**Comment by arcuru** [comment]
For others showing up here, the minimum supported fish version is [v3.4.0](https://github.com/fish-shell/fish-shell/releases/tag/3.4.0)
