### ISSUE TITLE
No password recovery flow

### ISSUE THREAD

**Issue by elmarsto** [atuinsh/atuin#1502]
I've spent about 30 minutes struggling to get atuin to work. I managed to `atuin register` with an incorrect password, which I do not know, and I have been unable to find any means of initiating a password recovery flow! What the heck? 

Am I just supposed to add a digit to my preferred username and start from scratch? 

Sorry, I know this is free software, but I'm quite frustrated by this. It's like a beautiful house that you move into only to discover that there is no plumbing.

**Comment by elmarsto** [comment]
Actually, no, that fails as well - presumably because the email address is the same. 

Look, this is a neat product, but if you take a user's password and then lock account creation with duplicate username, you're basically obligated to provide (and most importantly, prominently document) a password recovery flow. This makes me really uncomfortable -- my shell history is now floating off somewhere in the ether, supposedly encrypted, but out of my control. Yikes on bikes.

**Comment by elmarsto** [comment]
Uninstalling.

**Comment by ellie** [comment]
Hey!

> Am I just supposed to add a digit to my preferred username and start from scratch?

Not at all. You can run

```
atuin account delete
```

If you're still logged in on any machine, and then re-register just fine.

If you're not logged in, you can reach out and we can figure something out.

We don't have an email recovery flow as we do not validate emails, and that's a really good way to get your domain blacklisted by email providers.

I'll close this as it sounds like you no longer need help :/

**Comment by ellie** [comment]
I've also deleted all of your data from the server, in case that helps you feel any better
