### ISSUE TITLE
atuin makes the shell unresponsive under high I/O pressure

### ISSUE THREAD

**Issue by ppom0** [atuinsh/atuin#1503]
Hi!
Under high I/O pressure on my system, atuin makes my shell hang for a long period, then fail with this error:
```
Error: pool timed out while waiting for an open connection

Location:
    atuin/src/command/client.rs:50:22
```
or
```
Error: error returned from database: (code: 5) database is locked

Caused by:
    (code: 5) database is locked

Location:
    atuin/src/command/client/history.rs:199:17
```
I'd love to see a `register_timeout` in milliseconds, similar to `network_timeout`. So when `atuin` would register a new entry in history,  if after `register_timeout` it still hasn't successfully registered the entry, it aborts the transaction and quits.

At least for me, better to have a few entries discarded than having a completely unresponsive shell under high IO/pressure.

What do you think?

**Comment by ellie** [comment]
Sure that makes sense to me! We'd have to ensure that `atuin history end` doesn't break after an aborted `atuin history start`, but otherwise sounds good

**Comment by happysalada** [comment]
Just a small question, did you find a way to "unlock" the shell ? After it's locked, how do you restore the system to a state where it responds to terminal commands again ?

**Comment by ppom0** [comment]
@happysalada I don't remember what I did last time... I think I switched to another shell, not configured to use atuin, just while system is under high IO pressure.
