### ISSUE TITLE
After atuin is successfully installed, the up key cannot be used to recall the command history.

### ISSUE THREAD

**Issue by Jackwew** [atuinsh/atuin#1504]
### After successful installation, the up key cannot be used to call up the command history list.

bash version
![image](https://github.com/atuinsh/atuin/assets/50656464/8052652b-1ccd-4c6c-9498-994629a83364)

Environment variable configuration
![image](https://github.com/atuinsh/atuin/assets/50656464/03c94c45-9c90-4524-8a77-3fff961e65cf)

atuin version
atuin 17.2.1

Machine information
![image](https://github.com/atuinsh/atuin/assets/50656464/d1fb8e0e-4123-48b4-898b-4f031979846f)

**Comment by ellie** [comment]
Is there any chance you could upgrade to a newer bash? We can try and debug this for you otherwise, but Atuin will work much better with a newer version of bash (>5 is ideal)

Are you using bash-preexec or blesh?

**Comment by Jackwew** [comment]
@ellie Thank you for your answer. It can now function normally
