### ISSUE TITLE
redraw the UI

### ISSUE THREAD

**Issue by lilydjwg** [atuinsh/atuin#1507]
Sometimes the terminal text is messed up, e.g. by a background process. It's expected that a `Ctrl-L` to redraw the UI. However, it seems that `Ctrl-L` is already used by other functionality.

**Comment by ellie** [comment]
I'm ok with replacing this with redraw: https://github.com/atuinsh/atuin/blob/main/atuin/src/command/client/search/interactive.rs#L187

A bunch of keybindings there are for people used to readline + other tools (though I'm aware readline uses that for clear too).

See this wrt Readline parity, which is a non-goal: https://forum.atuin.sh/t/default-key-binding-changes/41

**Comment by lilydjwg** [comment]
What about the opposite `Ctrl-H` then? Leaving it as it is may confuse users. Do you want it to Backspace (readline-style) or unbound for future use?

**Comment by ellie** [comment]
unbound for future use makes sense here
