### ISSUE TITLE
how to choose one history without execute

### ISSUE THREAD

**Issue by Insua** [atuinsh/atuin#1536]
when I choose one history, I found it has some error,so I just want to edit the command
But after I press ENTER,the command was executed
it's not my excepted,
but how to only show?

**Comment by mbaum0** [comment]
You can set this with the `enter_accept` configuration.
See https://atuin.sh/docs/config/#enter_accept

Just set `enter_accept = false` in your `~/.config/atuin/config.toml` file

**Comment by akinomyoga** [comment]
Or, with `enter_accept` enabled, you can press <kbd>tab</kbd> to edit the line.

**Comment by ellie** [comment]
I added this to the readme in #1538, as I don't think it was clear

**Comment by Insua** [comment]
thanks to all, works fine

**Comment by uuhan** [comment]
Maybe these useful information could show up in the Atuin history list screen.

**Comment by ellie** [comment]
It's mentioned in the README, in the docs, and in the next release will be in the TUI directly as well: https://github.com/atuinsh/atuin/pull/1540
