### ISSUE TITLE
zsh: after selecting command from history, can't go to zsh's vim mode

### ISSUE THREAD

**Issue by mrnugget** [atuinsh/atuin#1539]
Hey! I'm running into a bug/issue where I can't edit a command in ZSH's vim-mode anymore.

I select a command in atuin, with `enter_accept = false` in the config, command is on command line, then I press `Ctrl-[` (which is equivalent to Esc) to edit the command, but it just removes it.

### To reproduce

1. Following `.zshrc` contents:
    ```zsh
    bindkey -v

    if type atuin &> /dev/null; then
    eval "$(atuin init zsh)"
    fi
    ```
2. This in `~/.config/atuin/config.toml`:
    ```toml
    enter_accept = false
    ```
3. Open new zsh
4. Hit `Ctrl+r`, select a command
5. Command is on CLI
6. Hit `Ctrl-[`

**What happens:** Command disappears

**What I expected to happen:** ZSH goes into Vim mode and I can edit the command.

Note: it works if I press `Esc` instead of `Ctrl-[`, which is very weird.

### Video for evidence

https://github.com/atuinsh/atuin/assets/1185253/e0144e91-36e7-43ff-ab7f-bc6e228a3669

**Comment by ellie** [comment]
Hey! Thank you for such a detailed issue 🙏 

I've tried to replicate this in a few different ways and so far have been unable to. As soon as I pretty `Ctrl-[`, zle enters Vim mode.

I'm using:

- atuin v17.2.1 (also tried `main`)
- zsh 5.9, with .zshrc containing only what you listed
- iterm, I tried Terminal too

I remember from your blog you are using Ghostty - does it still happen for you on other terminals? (I don't have access to that one just yet)

**Comment by mrnugget** [comment]
You're right! Sorry about the noise then. It _is_ a Ghostty issue, it seems like. It works in wezterm, Kitty, Alacritty.

**Comment by mrnugget** [comment]
Just to close the loop here: it's technically not a bug in Ghostty 😄 https://github.com/mrnugget/dotfiles/commit/315da3572a07c0b415e0a6b298831076dc87a5de

**Comment by mrnugget** [comment]
Just to close the loop here: it's technically not a bug in Ghostty 😄 https://github.com/mrnugget/dotfiles/commit/315da3572a07c0b415e0a6b298831076dc87a5de

**Comment by ellie** [comment]
TIL some more about terminals. Thanks for sharing 🙏
