### ISSUE TITLE
How to completely uninstall?

### ISSUE THREAD

**Issue by sunglim** [atuinsh/atuin#1546]
![image](https://github.com/atuinsh/atuin/assets/756988/368438ba-dd5a-4002-8b80-a6e9c35b2bbc)

I'm using mac and bash

yesterday I installed atuin, but now the screen is completely broken. I removed atuin via homebrew. but uparrow still blame atuin is not existing.

I searched 'uninstall atuin' on google. and read the https://docs.atuin.sh/.  but couldn't find any document about uninstallation.

**Comment by ellie** [comment]
Dupe of #1529, #649, #111, #372, #671 

I'll add a section to the docs, however:

You need to edit your zshrc/bashrc/fish config to remove the Atuin integration. Uninstalling the binary depends on your system.

**Comment by 12932** [comment]
> Mind if I ask why Atuin didn't work out for you?

If you look at their screenshot the output is sort of messed up. I personally wasn't aware that atuin provided this feature automatically when pressing the up arrow to go through shell history

**Comment by ellie** [comment]
> If you look at their screenshot the output is sort of messed up

Hmm I see. Probably an altscreen issue from tmux/screen/their terminal/whatever. Fixable with a small config change with most. Annoyingly there's seemingly infinite combinations of setups, so making it work for everyone right out of the box is a game of whack-a-mole. 

Looks like I can see some vim/some editor output somewhere in there too

> I personally wasn't aware that atuin provided this feature automatically when pressing the up arrow to go through shell history

Yeah we hear this a lot - mind if I ask which parts of the docs you read for the install? I tried to make sure it's mentioned almost all over, but it's still missed a lot so I'd like to improve that. People feel strongly about the up arrow (both for and against), though there is no consensus as to whether it should be enabled by default or not.

**Comment by foice** [comment]
> Mind if I ask why Atuin didn't work out for you?

Not being able to edit the line I just recovered from this otherwise very smart way to navigating the history. Going back to fuzzy finder fzf ...

**Comment by ellie** [comment]
You can press tab to select the command without executing it, and then edit it there

Or 

enter_accept = false

In your config to make this the default

**Comment by foice** [comment]
This helps a lot to get closer to the desired behavior!
