### ISSUE TITLE
[Feature Request] Edit command while selecting command

### ISSUE THREAD

**Issue by bytemain** [atuinsh/atuin#1548]
When we select history command, we may want to edit the command.

![CleanShot 2024-01-12 at 17 49 31@2x](https://github.com/atuinsh/atuin/assets/13938334/f420a0f4-2a6b-4419-bbcf-7faaa4bbbb2f)

We can add a new mode called edit mode, in this mode we can edit select command, use arrow left or right to move the cursor.

And I have insterests to implement this feature.

**Comment by ellie** [comment]
Hey!

You can already edit the command by pressing tab instead of enter

**Comment by bytemain** [comment]
I think it may be a different experience, and I still hope to explore a new interaction.
