### ISSUE TITLE
Interactive commands not saving to history

### ISSUE THREAD

**Issue by cschloer** [atuinsh/atuin#1550]
Hi,

I'm running a fresh install of `Atuin v17.2.1`, on a relatively fresh install of Ubuntu 22.04.3 LTS, using GNU bash (version 5.1.16(1)-release).

Interactive commands (specifically `vim`, but I also tried `nano`) don't seem to be added to the history. Is this working as expected? 

I found this issue https://github.com/atuinsh/atuin/issues/1003 that mentions this specific problem in the end, but the solutions don't seem to be relevant for this issue.

**Comment by arcuru** [comment]
How are you exiting the interactive commands? If you open vim and then kill the terminal without exiting vim they won't get added.

If that's not the problem, are you using bash-preexec or ble.sh?

**Comment by cschloer** [comment]
I'm exiting the process normally (:q for vim), and not using either bash-preexec or ble.sh.

**Comment by cschloer** [comment]
Closing because I'm realizing it's related to something else.

**Comment by cschloer** [comment]
I realized it was only working for the first command of the session, and it was due to this tool I was using:

https://github.com/jml/undistract-me

**Comment by cschloer** [comment]
This fork fixes it:

https://github.com/jml/undistract-me/pull/68
