### ISSUE TITLE
Please update the ring crate to 17.x

### ISSUE THREAD

**Issue by yurivict** [atuinsh/atuin#1569]
This is needed to prevent failures like [this](https://github.com/briansmith/ring/issues/1904).

**Comment by ellie** [comment]
We don't depend on ring directly, it's a transitive dependency

EG, see the latest version of rusty_paseto: https://github.com/rrrodzilla/rusty_paseto/blob/main/Cargo.toml#L53

**Comment by yurivict** [comment]
Thank you for this info.

I asked rusty_paseto to update ring: https://github.com/rrrodzilla/rusty_paseto/issues/31
