### ISSUE TITLE
Configure "Enter" behaviour like "tab"

### ISSUE THREAD

**Issue by taifu** [atuinsh/atuin#1571]
I'm really fond of the concept of this tool, but as a regular fish shell user, I'm accustomed to the "Enter" key only displaying the entry in the prompt, rather than executing it. Unfortunately, this habit has led to me accidentally executing commands before I've finished editing them. Until there's an option to customise keybindings so that 'Enter' behaves like "Tab", I find myself needing to disable Atuin.
While this isn't a bug, it's definitely an enhancement that would greatly improve usability for users with similar habits.

**Comment by conradludgate** [comment]
There is an option for it. Disable enter_accept in the config <https://docs.atuin.sh/configuration/config/#enter_accept>

**Comment by ellie** [comment]
Otherwise in the FAQ: https://docs.atuin.sh/faq/

Funnily enough, the default used to be the opposite, and lots of people asked for change 🥲🤣

**Comment by taifu** [comment]
Thank you a lot! I already tested it and it works as a charm! 😊
