### ISSUE TITLE
Exact match option

### ISSUE THREAD

**Issue by jonathangreen** [atuinsh/atuin#1599]
I would really love to see a configuration option to reverse the ' operator when using the `fuzzy` search mode, so exact match is the default and I can opt into fuzzy match with the operator.

Similar to the fzf `--exact` flag.

> If you don't prefer fuzzy matching and do not wish to "quote" every word, start fzf with -e or --exact option. Note that when  --exact is set, '-prefix "unquotes" the term.

**Comment by ellie** [comment]
So we have a few other search modes: https://docs.atuin.sh/configuration/config/#search_mode

You can either change the default, and/or use <kbd>ctrl-s</kbd> to toggle through them 

Not quite what you're asking for, but does that solve the problem?

**Comment by jonathangreen** [comment]
I really like the fuzzy search syntax generally. I just find myself using the exact-match operator `'` for almost every search term. 

I'd rather exact-match be the default and apply the `'` operator when I want a fuzzy-match search term. 

If I changed to a different search type I would lose the other features of the fuzzy search syntax like a space acting as an and, a `|` acting as an or, suffix and prefix matching, etc. I find those features really useful.

Thank you for the great project by the way! It is basically the shell search I've always wanted!

**Comment by jonathangreen** [comment]
To give an example of my use case. If I'm searching for a command in my history like:

`curl -u "abc:123" -X POST -v https://foo.bar.com`

My search often looks like:
`^curl 'abc 'bar.com`

I'm asking for a config option so I can type:
`^curl abc bar.com`

But still have `abc` and `bar.com` be exact matches.

**Comment by ellie** [comment]
> Thank you for the great project by the way! It is basically the shell search I've always wanted!

Thank you, glad you like it!

That totally makes sense. If I'm honest, I'm thinking of overhauling the search a bit - see #1455. I'd love to have a single search mode that solves 99% of cases for most people, and can be tweaked. This would be closer to a proper search index/engine than something like `fzf`, though we could get the actual experience to be similar. 

Exact matching would work, as would fuzziness/slop/AND/OR, pretty much everything you'd expect. Except the scoring and sorting could be _much_ better, rather than a bunch of hacky sql queries.

**Comment by jonathangreen** [comment]
Makes sense to me! For my case, returning exact matches before fuzzy matches, would also meet the use case I have. Really the reason I use the exact-match operator as much as I do is that I find the exact matches in my history get drowned out by fuzzy matches, and most of the time the exact match is what I am looking for. Might be a case to keep in mind if your are overhauling the search.

**Comment by Nibodhika** [comment]
I agree with that last comment, I can understand why fuzzy matches are default and all, but exact matches should always be first, it's really annoying looking for a command I know has `gtk` in it and have to navigate through multiple git commands before getting to it. I know I can do `'gtk` but exact matches should be presented first regardless

**Comment by ellie** [comment]
Does setting

`smart_sort=true`

Make things any better for you?

**Comment by Nibodhika** [comment]
It does, a quick test seems to show that this is exactly what I was looking for, hope this becomes stable and gets documented soon, I'll be using it in the meantime and if I find something strange I'll report. Thank you
