### ISSUE TITLE
Select text

### ISSUE THREAD

**Issue by ismith** [atuinsh/atuin#160]
I can't use my mouse to select (and then copy) text in a command - sometimes I don't want to run a command, or get the whole thing, I just want to copy a hash or id or what have you from it.

Right now I do that by finding the command I want, hitting 'enter' to put it in the terminal, and then I can copy/paste/edit/whatever there instead of just hitting enter again to run as-is.  But it'd be less cognitive friction if I could copy-paste from the tui like I expect when I see text on a screen.

**Comment by loggerhead** [comment]
I have the same problem, is there any solution?

**Comment by shoffmeister** [comment]
I am hitting this very use case while trying to document, after the fact, the commands I used for a complex task.

`atuin search | fzf` does not work - as `fzf` does not allow for text selection, either. Whoops. (Same with `skim`)

Am I looking for a glorified history browser? `sqlitebrowser ~/.local/share/atuin/history.db` ?

**Comment by pigfrown** [comment]
I run into this daily.

Being able to highlight text in atuin so it I can paste it elsewhere would be great
