### ISSUE TITLE
zsh import: respect $HISTFILE

### ISSUE THREAD

**Issue by lewurm** [atuinsh/atuin#1607]
https://github.com/atuinsh/atuin/blob/f727d6c8bf34482d11948b114249f2e1523c81ed/atuin-client/src/import/zsh.rs#L22-L24

I just ran into this 😅  would be great if atuin import could check first if `$HISTFILE` is set.

**Comment by ellie** [comment]
It should do - `default_histpath()` returns the default for if HISTFILE is not set

See it being used here

https://github.com/atuinsh/atuin/blob/f727d6c8bf34482d11948b114249f2e1523c81ed/atuin-client/src/import/zsh.rs#L51

and wrapped with get_histpath, which prefers the value of $HISTFILE

https://github.com/atuinsh/atuin/blob/f727d6c8bf34482d11948b114249f2e1523c81ed/atuin-client/src/import/mod.rs#L68-L77

Did you have issues with it working?

**Comment by lewurm** [comment]
ohhh!  This is what happened:

1. I had `HISTFILE=~/.histfile` in my `.zshrc` (note the missing `export`)
2. I also have a `~/.zhistory` with a few entries which `atuin import zsh` picked up 
3. Then I went to the repository found `default_histpath()` and thought that's the problem, and didn't look further.

If I remove `~/.zhistory` I get indeed a useful error message from `atuin import zsh`:
```
Error: Could not find history file. Try setting and exporting $HISTFILE
```

Using `export HISTFILE=...` fixes that then.

So everything is good here I think, sorry for the noise!

**Comment by ellie** [comment]
Ah I see! Glad you got it sorted
