### ISSUE TITLE
Character encoding on bash breaks starship prompt

### ISSUE THREAD

**Issue by blut** [atuinsh/atuin#1617]
Hello

When I select a command in atuin with Enter, my bash prompt is broken, printing all color selectors. (second command on screenshot)
Surprisingly, when I select a command with Tab, the prompt remains intact (first command)
![image](https://github.com/atuinsh/atuin/assets/4506959/2011b9fd-9949-4922-ac69-dee4e3e62bfe)

Is there an encoding configuration that might be incorrect or could you help me debug this?

**Comment by akinomyoga** [comment]
This must be related to the control characters `\001` and `\002` that Bash internally uses to mark the range of the escape sequences (which does not contribute to the prompt width calculation). More specifically,

1) `\[` and `\]` in the prompt string `PS1` is first translated to `\001` and `\002`, respectively, and then
2) the Bash calculates width of the prompt while taking account of `\001` and `\003`.
3) Finally, Bash outputs the prompt after stripping `\001` and `\002`.

When the command execution is requested by pressing <kbd>Enter</kbd> (with the Atuin config `enter_accept` being enabled), Atuin with Bash+bash-preexec tries to emulate the command execution of Bash. Within the emulation, Atuin tries to evaluate the prompt by `"${PS1@P}"`, but `"${PS1@P}"` only performs Step 1 in the above list, which means that its result contains the aforementioned special control characters `\001` and `\002`. Then, Atuin outputs the result of `"${PS1@P}"` to the terminal, which contains `\001` and `\002` that Bash internally uses.

Most terminal emulators ignore those control characters, but some terminal emulators display them as characters with finite width with a certain representation. This is what you observe.

The solution is to strip the control characters from the result of `"${PS1@P}"` before outputting it to the terminal.

**Comment by akinomyoga** [comment]
@blut Can you check if #1620 fixes the problem?

**Comment by blut** [comment]
Hi @akinomyoga, yes, https://github.com/atuinsh/atuin/pull/1620 indeed fixes the behaviour!
