### ISSUE TITLE
Directory switching based on cwd history

### ISSUE THREAD

**Issue by NorfairKing** [atuinsh/atuin#162]
Hi!

I found this project a while ago and it's basically the same as the [hastory](https://github.com/NorfairKing/hastory) I made a few years back. The feature set is very similar except you did it much better :+1: so I'm looking to stop using mine and start using yours.
There's only one feature that I haven't found in `atuin`, which is the frequency-based directory switching.

The idea is that you can learn where the user _probably_ wants to switch to next from the history of `cwd`s.
This is a very simple frequency-based computation, nothing fancy, see https://github.com/NorfairKing/hastory/blob/35abbc79155bc7c5a0f6e0f3618c8b8bcd3889a1/hastory-cli/src/Hastory/Cli/Commands/Recent.hs#L61

**Comment by conradludgate** [comment]
I'm not quite sure I understand this request. Atuin doesn't manage directory switching. If you are looking for a good alternative to smart dir switching, I'd suggest [zoxide](https://github.com/ajeetdsouza/zoxide)

**Comment by mrjones2014** [comment]
@NorfairKing you might also be interested in this project I threw together over the weekend 😁 
https://github.com/mrjones2014/ctrlg

**Comment by ellie** [comment]
You know, on second thoughts, this might actually be a pretty neat thing to have. We do have the data, afterall 🤔
