### ISSUE TITLE
Feature Request: Command Context Preview

### ISSUE THREAD

**Issue by xy-241** [atuinsh/atuin#1651]
**Description:**
Enhance the search functionality by introducing a command context preview option. When users search for a specific command, the system should display not only the relevant command but also include the commands typed immediately before and after it.

**Use Case:**
Users often recall a command's context rather than its exact name. With the command context preview, users can quickly identify the desired command by reviewing its neighboring commands, improving the efficiency of the search process.

**Benefits:**
- **Improved Recall:** Users can more easily locate commands by seeing them in the context of their surrounding commands.
- **Time Savings:** Reduces the time spent searching for commands, especially when users remember the sequence of actions leading up to or following a specific command.
- **Enhanced User Experience:** Adds an extra layer of usability, making the command search feature more intuitive and user-friendly.

**Implementation:**
Introduce a toggle button or checkbox in the search interface labeled "Show Command Context." When enabled, the search results will include the matched command along with the commands typed immediately before and after it.

**Comment by ellie** [comment]
Hey! This is pretty much what the inspector is for, currently merged in `main` and will be released soon.

It allows the user to explore more context around a command
