### ISSUE TITLE
Entering and pasting flags cause atuin to bug out when using the oh-my-zsh's zsh-autosuggestion plugin

### ISSUE THREAD

**Issue by TKperson** [atuinsh/atuin#1652]
After installing zsh-autosuggestion using oh-my-zsh, pasting flags or typing out flags without commands (e.g. `--example`) will trigger atuin command and cause a `error: unexpected argument '--example' found` error.

Bug showcase/reproduce: https://asciinema.org/a/wC6c8nAJsnwg8W8vVNEq9ILSg

**Comment by arcuru** [comment]
See #1582
