### ISSUE TITLE
Delete from history

### ISSUE THREAD

**Issue by kosta** [atuinsh/atuin#1665]
Sometimes I need something gone from my history. Maybe I dont want to auto-complete into the bad command that I wrote. Or I accidentally leaked a secret. Is that possible? I would have expected a key binding but could not find one.

**Comment by dongxuwang** [comment]
I guess you might try search command like here:
https://docs.atuin.sh/reference/search/

**Comment by ellie** [comment]
This is currently possible with the `--delete` flag on search, and will be availble in the UI in the next release.

_However_, from an ops perspective, I would strongly advice that you treat any secret that has ever been committed to any shell history as no longer secret.

**Comment by kosta** [comment]
Should this be documented here? https://docs.atuin.sh/configuration/key-binding/

**Comment by barseghyanartur** [comment]
I suggest to mention (in the docs) yet another way to edit the history. There are tons of decent GUI apps to edit SQLite databases. [DBeaver](https://dbeaver.io/) (open-source, Apache-2.0 licensed) being just one of them. Just open the atuin SQLite database and clean up undesired records. Simple, isn't it?

**Comment by ellie** [comment]
@barseghyanartur if you do that, your history will not sync correctly. It will work only on the machine you edit it with

If you delete history that way, it will just come back.

**Comment by barseghyanartur** [comment]
> @barseghyanartur if you do that, your history will not sync correctly. It will work only on the machine you edit it with
> 
> If you delete history that way, it will just come back.

Wow, that was quick! Thanks. It's exactly my use case. I use this awesome tool only locally. No need to sync with multiple machines.

**Comment by barseghyanartur** [comment]
Hey, just thinking out loud about my most common use case. Sometimes I mistype. I know about it immediately. It would be useful to have a command that would allow removal of the latest executed command from history (something like `atuin remove-previous-command-from-history`).

**Comment by jbellis** [comment]
Was there a regression?  When I delete from my history following the instructions here, it disappears from the history dialog, but if I invoke a new search the "deleted" items are still there.

**Comment by ellie** [comment]
@jbellis which instructions? are you using --delete, or trying to delete from the inspector? 

I'm not able to replicate atm, could you share `atuin doctor` in a new issue please?
