### ISSUE TITLE
Directory mode only when git project is detected FEATURE

### ISSUE THREAD

**Issue by MustCodeAl** [atuinsh/atuin#1682]
Directory mode is nice, but it would be nice if it was possible to keep global as default but make it go to directory mode only if there is a git repo detected, is there a way to do this in zsh?

**Comment by ellie** [comment]
Yep, you can put

```
workspaces = true
```

In your config. It will enable "workspace" mode in a git dir, which will then filter by directory (and all subdirs). It'll be on by default in the future
