### ISSUE TITLE
Could not register user due to version mismatch

### ISSUE THREAD

**Issue by joedborg** [atuinsh/atuin#1692]
I'm getting this error when running a local server:

```
➜ atuin register

Registering for an Atuin Sync account
Please enter username: REDACTED
Please enter email: REDACTED
Please enter password: REDACTED
Atuin version mismatch! In order to successfully sync, the server needs to run a newer version of Atuin
Client: 18.0.0
Server: 17.1.0
Error: could not register user due to version mismatch

Location:
    /private/tmp/atuin-20240209-5225-bhp6i3/atuin-18.0.0/atuin-client/src/api_client.rs:66:9

```

But the server is at 18.0.0:

```
$ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                                       NAMES
2bdec393bad8   ghcr.io/atuinsh/atuin:18.0.0   "/usr/local/bin/atui…"   8 minutes ago   Up 8 minutes   0.0.0.0:8888->8888/tcp, :::8888->8888/tcp   atuin-atuin-1
fd5f1cde4940   postgres:14
```

```
atuin@2bdec393bad8:/app$ atuin --version
atuin 18.0.0
```

**Comment by ellie** [comment]
Hey!

Could you confirm that your server responds with `version: 18.0.0`? 

Eg, https://api.atuin.sh

**Comment by joedborg** [comment]
Hey @ellie!  Thanks for the quick reply!

```json
$ curl localhost:8888
{"homage":"\"Through the fathomless deeps of space swims the star turtle Great A'Tuin, bearing on its back the four giant elephants who carry on their shoulders the mass of the Discworld.\" -- Sir Terry Pratchett","version":"18.0.0","total_history":-1}
```

It seems to be good.

**Comment by ellie** [comment]
If you run your server with both `ATUIN_LOG=debug` and `RUST_LOG=debug`, do you see any activity when your client is syncing with the server? Should be at least one request, even with this error

I'm just wondering if there's a server running elsewhere that's still on 17.1.0

**Comment by joedborg** [comment]
I was thinking that too.

I've set 

```
sync_address = "https://192.168.0.254"
```

in `~/.config/atuin/config.toml` on MacOS

Could the client not be reading that correctly?

**Comment by ellie** [comment]
It should be. Earlier you curl-d localhost, does 

```
curl https://192.168.0.254
```

also say v18.0.0?

**Comment by joedborg** [comment]
Ahhhh, that's shown the issue, I need to use `http` instead of `https`.

I'm assuming the client is falling back on the atuin.sh server if there's an issue with the `sync_address` set?

**Comment by ellie** [comment]
Makes sense!

It doesn't fallback, but just gives a weird error. I'll sort that out - thanks!

**Comment by baymax55** [comment]
I also encountered the same problem and it was solved by replacing https with http
