### ISSUE TITLE
Terminal left in Enhanced Keyboard mode

### ISSUE THREAD

**Issue by candrewlee14** [atuinsh/atuin#1693]
## Behavior:
 - Open a new terminal that supports kitty protocol
 - Type the up arrow to start atuin's history search
 - Open neovim
 - Enter INSERT mode
 - Observe that capital letters print out invalid unicode sequences
    - The `SHIFT` key, for example, prints out a character on its own 

I believe this is because the terminal is left in Enhanced Keyboard mode, which changes the keycodes of characters.
Unfortunately, this totally breaks the functionality of many programs I use.

## Expected Behavior:
 - Open a new terminal that supports kitty protocol
 - Type the up arrow to start atuin's history search
 - Open neovim
 - Enter INSERT mode
 - Observe that capital letters print capital letters
 
It looks like Atuin recently enabled Enhanced Keyboard mode here: e129f7a93eb1bc595201a6ec57ba586b3d9d4419

## Version
`18.0.0`

**Comment by kantord** [comment]
I can confirm that the same thing is happening to me. Same atuin version.

**Comment by ellie** [comment]
@kantord does #1694 fix it for you?

**Comment by kantord** [comment]
@ellie seems like yes!

**Comment by kantord** [comment]
I also faced a similar problem when doing the following steps:

- Open `kitty` terminal
- Search in atuin history
- cd into a git repo
- `tig status`
- Try to navigate in tig status using `j` and `k` keys. When I do this, nothing happens. tig appeared to be entirely frozen


What is different is that I didn't need to use capital letters. But in neovim, I only had trouble with capital letters like @candrewlee14

**Comment by kantord** [comment]
In any case, with the fix I can no longer reproduce that problem either

**Comment by tokyovigilante** [comment]
Confirm #1694 also fixes issues in nano after use with v18.

**Comment by hashworks** [comment]
Same problem with vim in foot. #1694 fixes it for me as well.

In case anyone needs it, [here is an Arch Linux package](https://fb.hash.works/Uyj7o/) with the patch until a new release is out - as far as I understand it, rollbacks to v17 are not possible if all clients switched to the new sync in v18.

**Comment by ellie** [comment]
Thanks for confirming! I'll get 18.0.1 out tomorrow morning

**Comment by ardrigh** [comment]
> I also faced a similar problem when doing the following steps:
> 
>     * Open `kitty` terminal
> 
>     * Search in atuin history
> 
>     * cd into a git repo
> 
>     * `tig status`
> 
>     * Try to navigate in tig status using `j` and `k` keys. When I do this, nothing happens. tig appeared to be entirely frozen
> 
> 
> What is different is that I didn't need to use capital letters. But in neovim, I only had trouble with capital letters like @candrewlee14

In case anyone else searches for this:

I had `config.enable_kitty_keyboard = true` enabled in my `wezterm` config. 

I was getting similar behaviour being unable to scroll up or down in `bat` when it was in pager mode. It felt like the terminal had frozen and I was unable to do exit the process.

The update with this fix appears to have resolved this issue for me also.

**Comment by cstrahan** [comment]
@ardrigh Are you able to get the expected behavior with `config.enable_kitty_keyboard = true` in your `wezterm` config and the latest release of `atuin` (i.e. 18.0.1)?

I'm using `wezterm`, and I find that with the [`terminfo` definition installed](https://wezfurlong.org/wezterm/config/lua/config/term.html) and `$TERM` set to `wezterm`, I find that the shift key seems to have no effect (e.g. I can't use the number keys to type symbols nor can I type upper case letters in `atuin`).

Curious if that's a problem on my end, a bug in `atuin`, or a bug in `wezterm`.

**Comment by ardrigh** [comment]
> @ardrigh Are you able to get the expected behavior with `config.enable_kitty_keyboard = true` in your `wezterm` config and the latest release of `atuin` (i.e. 18.0.1)?

Using Wezterm stable for Fedora 39, and atuin version 18.0.1 (I install Atuin via Cargo), it resolved the problem I was having with `bat`

```shell
> wezterm --version
wezterm 20240203-110809-5046fc22
> atuin --version
atuin 18.0.1
```

> I'm using `wezterm`, and I find that with the [`terminfo` definition installed](https://wezfurlong.org/wezterm/config/lua/config/term.html) and `$TERM` set to `wezterm`, I find that the shift key seems to have no effect (e.g. I can't use the number keys to type symbols nor can I type upper case letters in `atuin`).
> 

I haven't tried setting the terminfo value. Mine is the default. I am also using Fish as my primary shell.

```
> echo $TERM
xterm-256color
```

> Curious if that's a problem on my end, a bug in `atuin`, or a bug in `wezterm`.

I would definitely recommend updating atuin first, if you haven't already.

**Comment by cstrahan** [comment]
@ardrigh Thanks for the reply!

It looks like I'm running up against a bug in `wezterm`'s handling of the kitty keyboard protocol: https://github.com/wez/wezterm/issues/3621#issuecomment-1947721248
