### ISSUE TITLE
Upgrading to atuin 18.0.0 causes panics

### ISSUE THREAD

**Issue by peterjanes** [atuinsh/atuin#1695]
OS: Fedora 39
Shell: bash 5.2.21(1)-release

After upgrading to atuin 18.0.0 using the bash/curl installation method (which prompted me to install via cargo) the atuin execution in the user prompt causes panics to be dumped to the console after every command and when pressing Ctrl-R. (I had previously disabled the up-arrow binding.)

```
thread 'main' panicked at /home/peterj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atuin-client-18.0.0/src/encryption.rs:97:38:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is the trace with `RUST_BACKTRACE=1`:

```
thread 'main' panicked at /home/peterj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atuin-client-18.0.0/src/encryption.rs:97:38:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: atuin_client::encryption::decode_key
   4: atuin_client::encryption::load_key
   5: atuin::command::client::history::Cmd::run::{{closure}}
   6: atuin::command::client::Cmd::run_inner::{{closure}}
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
   8: tokio::runtime::context::runtime::enter_runtime
   9: tokio::runtime::runtime::Runtime::block_on
  10: atuin::command::AtuinCmd::run
  11: atuin::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The only changes I've made to the default configuration are to set `search_mode = "fulltext"`, `show_preview = true`, and `workspaces = true`; I've also added `--disable-up-arrow` to the template in `.bashrc`.

**Comment by ellie** [comment]
Are you using sync at all?

**Comment by peterjanes** [comment]
Yes, I've been syncing with the default server.

**Comment by ellie** [comment]
Does `~/.local/share/atuin/key` exist? and does `atuin key` output anything?

Please don't share that here

**Comment by peterjanes** [comment]
The file exists but is empty; `atuin key` doesn't show anything (as expected, I guess).

**Comment by ellie** [comment]
If you delete the file, does it sort itself out?

**Comment by peterjanes** [comment]
It looks like deleting the key file has resolved the issue, yes. The file is now 68 bytes long and `atuin key` shows a string of random words.

**Comment by ellie** [comment]
Ok great - I'm trying to replicate it but so far haven't managed to. I'll close this for now and re-open should it come up again
