### ISSUE TITLE
Feature request: Ctrl+enter immediately executes command on "enter_accept = false"

### ISSUE THREAD

**Issue by georgemarselis-nvi** [atuinsh/atuin#1699]
It would be nice if we did have a way to immediately execute a command, even if enter_accept is set to false.

my opinion is that should be control+enter

**Comment by ellie** [comment]
I suspect we would strike issues with various terminal control codes here, I'd rather avoid adding this

Most terminal emulators (other than those with enhanced keyboard support) won't properly distinguish between enter, and ctrl-enter

We are pretty limited with what's available
