### ISSUE TITLE
Feature request: hitting left/right arrow on command/meta+number allows editing the underlined command

### ISSUE THREAD

**Issue by georgemarselis-nvi** [atuinsh/atuin#1700]
would be nice to be able to edit a command, regardless if enter_accept is set or not.

my suggestion is is hitting either the left or right arrow.

**Comment by ellie** [comment]
You can already edit a command regardless of that config 

Tab: edit
Enter: execute 

If enter accept is disabled, both keys will edit 

I'd rather not have many ways of doing the same thing

**Comment by georgemarselis-nvi** [comment]
doh, i did not see that in the docs, apologies!

but if i may argue, but isn't the left/right more bash/gnu readline compatible?

**Comment by ellie** [comment]
No worries! As of v18, it should also be at the top of your atuin window 

It would indeed. However, if we concerned ourselves with being fully readline compatible, we would have no keys leftover for anything else

Readline provides many different ways of doing the same thing. I'd rather save the arrow keys for the future

**Comment by ellie** [comment]
Relevant reading: https://forum.atuin.sh/t/default-key-binding-changes/41

**Comment by apoorvkh** [comment]
Hi, just started using `atuin` and am finding it really useful!

I know that we can already use tab to edit the command, but I was wondering if we can bind a different key (e.g. the right arrow key) for editing commands. That would feel even more natural to me in conjunction with the "up arrow" :) Thanks!
