### ISSUE TITLE
[Feature] Allow setting `--disable-up-arrow` in `config.toml`

### ISSUE THREAD

**Issue by arkban** [atuinsh/atuin#1709]
Please allow setting a configuration value equivalent to `--disable-up-arrow` in `atuin/config.toml`.

I appreciate the documentation on ["Disable up arrow"](https://docs.atuin.sh/configuration/key-binding/#disable-up-arrow), that information is unfortunately not as useful if you are using a shell plugin manager that hides the `eval "$(atuin init zsh)"`.

(I am aware I could manually set my own bindings (as described in the same docs), that's less appealing than having all the configurations in the one config file)

NOTE: I think it would also be a good idea to add `--disable-ctrl-r` to the `config.toml`.

P.S.: Thank you for building this plugin!

**Comment by ellie** [comment]
> I appreciate the documentation on ["Disable up arrow"](https://docs.atuin.sh/configuration/key-binding/#disable-up-arrow), that information is unfortunately not as useful if you are using a shell plugin manager that hides the eval "$(atuin init zsh)".

I'm afraid we cannot currently support installation methods outside of what is in the docs. You'll want to set ATUIN_NOBIND and then bind the keys yourself.

For keybinding support in config, see #193

**Comment by ellie** [comment]
Happy to have a discussion around supporting whatever plugin manager you're using however! But as of present, this is not in scope.

**Comment by arkban** [comment]
> Happy to have a discussion around supporting whatever plugin manager you're using however! But as of present, this is not in scope.

I'm using [`zinit`](https://github.com/zdharma-continuum/zinit), BTW which I appreciate you adding instructions for in the [installation docs](https://docs.atuin.sh/guide/installation/#shell-plugin).

Unfortunately since `zinit` obscures the direct plugin loading command -- i.e. the `eval "$(atuin init zsh)"` -- I'm not sure how to apply the `--disable-up-arrow` in the [helpful instructions]((https://docs.atuin.sh/configuration/key-binding/#disable-up-arrow)) you've provided.

I'm sure the solution is somewhere in the [`zinit` wiki](https://zdharma-continuum.github.io/zinit/wiki/), I just haven't had a chance to dive in and figure it out.
