### ISSUE TITLE
`ignore_commands` option for stats

### ISSUE THREAD

**Issue by drmorr0** [atuinsh/atuin#1714]
Would you be open to having an `ignore_commands` option for `atuin stats`?  `cd`, `ls`, and `vi` are my three top commands by nearly an order of  and I don't find this particularly informative; I'd be interested in filtering these out entirely from my stats.

If you're interested in this, I'd be willing to take a stab at a PR for it.

**Comment by ellie** [comment]
I'd be interested! 

Otherwise, you can see more commands with the -c arg, if you find them a waste of space

eg

`atuin stats -c 100` will show the top 100, rather than top 10

**Comment by drmorr0** [comment]
OK I will see how hard this is and take a stab at a PR.

The issue is not so much a waste of space, but that it makes the histogram kindof useless: 

```
> atuin stats
[▮▮▮▮▮▮▮▮▮▮] 890 cd
[▮▮▮▮▮▮▮▮▮ ] 868 vi
[▮▮▮▮▮▮    ] 608 ls
[▮▮        ] 199 kcgp
[▮         ] 165 git stat
[▮         ] 159 kcl
[▮         ] 141 kcapp
[▮         ] 131 kcrm
[▮         ] 130 git co
[▮         ] 119 kcg
```

When all the other commands only have one bar because the top three are so large, it's hard to actually tell "at a glance" the magnitude difference between them all.
