### ISSUE TITLE
emacs ctrl-k does not work in search mode

### ISSUE THREAD

**Issue by rseymour** [atuinsh/atuin#1715]
PR incoming.

ctrl-k truncates a line from the cursor. This was a trivial fix with the `truncate(index)` function on rust strings.

I do think that maybe using a "proper" readline implementation could save a lot of duplicated work, for instance: https://github.com/kkawakam/rustyline

**Comment by ellie** [comment]
See my comment on the PR: https://github.com/atuinsh/atuin/pull/1716#issuecomment-1942133467
