### ISSUE TITLE
Implement ATUIN_CONFIG_PATH environment variable

### ISSUE THREAD

**Issue by cohml** [atuinsh/atuin#1723]
The v18 documentation states

> We store data in `~/.local/share/atuin` (unless overridden by `XDG_*`).

That's great, but overriding core variables used by many programs like `XDG_*` can have many ugly knock-on effects.

More flexible would be the ability to set a custom path to the `atuin` config file (or dir) specifically. To be clear, I'm proposing we have this option *in addition to* the `XDG_*` option that's already implemented, not *instead of* it.

Implementing an environment variable pointing to the `atuin` config (e.g., `ATUIN_CONFIG_PATH`) would follow the well-worn precedent of many other popular projects. Here are a few examples, with references:

1. `bat` ([ref](https://github.com/sharkdp/bat?tab=readme-ov-file#configuration-file))
2. `broot` ([ref](https://dystroy.org/broot/launch/#environment-variables))
3. `conda` ([ref](https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#searching-for-condarc))
4. `ipython` ([ref](https://github.com/ipython/ipython/blob/3d02f18733c0bbf062e8852fdc417609fbf29e51/docs/source/config/intro.rst#the-ipython-directory))
5. `lazygit` ([ref](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#overriding-default-config-file-location))
6. `ripgrep` ([ref](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file))

**Comment by ellie** [comment]
This is already supported with `ATUIN_CONFIG_DIR`. The config files allows you to specify the locations for database storage, though you can also use the env equivalants

**Comment by cohml** [comment]
Fair enough, thank you!
