### ISSUE TITLE
atuin server requires a public schema

### ISSUE THREAD

**Issue by tessus** [atuinsh/atuin#1731]
I've also sent my feedback via the forum, but I believe this needs at least a discussion about it, although I think that this should be fixed.

I created a database `atuin` and a user `atuin`. The user `atuin` has full admin privileges on the database.
I revoked all privileges on the schema `public` from the group `public` in the atuin database, because the user `atuin` has all privileges anyway:

```
\c atuin
REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;
```

atuin abends with:

```
Error: failed to connect to db: PostgresSettings { db_uri: "postgres://atuin:passwordhere@127.0.0.1/atuin" }

Caused by:
    Other(while executing migrations: error returned from database: no schema has been selected to create in

    Caused by:
       0: error returned from database: no schema has been selected to create in
       1: no schema has been selected to create in

    Location:
        /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/convert/mod.rs:757:9)

Location:
    /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/atuin-server-18.0.1/src/lib.rs:141:10
```

The error message is a bit misleading, because connecting to the database works just fine.

I am actually rather puzzled by the “real” error message. The user atuin has all privileges on the database, even for the schema PUBLIC. But I had to grant the group public all privileges to the schema public. 

Why? This makes no sense. Maybe the "fix" is to just create a schema `atuin` and set it as the default schema for the database connection. Another option is to explicitely specify a schema in the sql.

What I don't understand is why the user `atuin` cannot create something in the public schema. I only revoked the privilege for the group public, not for the user `atuin`.

**Comment by underw8** [comment]
I wonder what your Postgres version is, my case is 15, and the recent change is
> PostgreSQL 15 also revokes the CREATE permission from all users except a database owner from the public (or default) schema.

Which would require the database user that being used for atuin must be the owner of the database itself in order for it to create tables in schema public.

This should help:
```
ALTER DATABASE atuin OWNER TO atuin;
```

**Comment by tessus** [comment]
@underw8 yep, thanks. I figured that out [yesterday](https://forum.atuin.sh/t/setting-up-atuin-as-a-server/173/6?u=tessus). GRANT ALL ON DATABASE does not make that user an admin or that they have all privileges on the schema public. 

Thus the best way to handle this is to create the database with an owner or alter the database, as you suggested, to have the atuin user as the owner.

I think I can close this.
