### ISSUE TITLE
[nushell] breaking change coming

### ISSUE THREAD

**Issue by fdncred** [atuinsh/atuin#1733]
Heads-up friendly folks at atuin! At nushell, we're working on a PR that will probably be a breaking change for people who use atuin with nushell integration.

We're breaking up the commandline built-in command into several subcommands. Please see the PR for more details. It will be deprecated for a while. You'll get a warning message, but it should still work in version 0.91.0 but after that we'll probably remove the deprecation.
https://github.com/nushell/nushell/pull/11877

**Comment by ellie** [comment]
Looks like @stevenxxiu just opened a PR to resolve this! Thank you both 🙏 

I'll merge the fix once the next version of Nu is released. By the time the warning is removed, a new version of Atuin will be out with the fix.
