### ISSUE TITLE
Initial set up issue: The system's UTC offset could not be determined

### ISSUE THREAD

**Issue by petty** [atuinsh/atuin#1749]
I couldn't get atuin to work, upon installation this error repeats:
```
Error: could not load client settings

Caused by:
    failed to deserialize: The system's UTC offset could not be determined

Location:
    atuin-client/src/settings.rs:638:26
```

**Comment by arcuru** [comment]
Might be helpful if you provide some info about your setup? The version of atuin? What OS you're on?

**Comment by siddhartpai** [comment]
I'm facing this issue with atuin 18.0.1
Installed on a mac, 
Terminal Zsh

Installed using this command : /bin/bash -c "$(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)"

**Comment by joelburget** [comment]
Same here, MacOS 14.2.1. I tried two install methods: (1) `bash (curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh/ | psub)` and (2) `brew install atuin` (though it looks like (1) uses brew under the hood).

```
> uname -a
Darwin simplex.lan 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 x86_64
> atuin register -u ****** -e ******
Error: could not load client settings

Caused by:
    failed to deserialize: The system's UTC offset could not be determined

Location:
    atuin-client/src/settings.rs:638:26
> atuin --version
atuin 18.0.1
```

**Comment by ellie** [comment]
If you set `timezone` in `~/.config/atuin/config.toml` to be your UTC offset, does the issue resolve?

**Comment by joelburget** [comment]
That fixed it. Without `timezone` or with `timezone = "local"` fails. But `timezone = "-8"` works.

**Comment by ellie** [comment]
Good to know - thank you.

I am unable to replicate it, but there are issues with Rust + getting the current timezone in a multithreaded environment. See more here: https://github.com/atuinsh/atuin/pull/1517

I'll see if there's a specific setup required to trigger this, but otherwise may remove local timezone reading in a future release

**Comment by TomorJM** [comment]
Same here , With MacOS 13.4.1

**Comment by sirbrillig** [comment]
Same here with Mac OS 14.1.2, zsh

**Comment by ellie** [comment]
Possible fix here, currently on `main`. If anyone with the issue is able to test, that would be amazing!

https://github.com/atuinsh/atuin/pull/1810

**Comment by jaseemabid** [comment]
@ellie Can confirm HEAD fixed the issue for me on macOS.

**Comment by ellie** [comment]
> @ellie Can confirm HEAD fixed the issue for me on macOS.

fantastic! I'll release on Monday. Thanks for checking
