### ISSUE TITLE
Atuin sometimes misses commands entered from history and edited

### ISSUE THREAD

**Issue by Samasaur1** [atuinsh/atuin#1750]
I am experiencing the same issue with `!!`, the up-arrow binding, and the ctrl-r binding. If I choose a command from my history and edit it before running it, Atuin only sometimes adds the edited command to my history, and sometimes totally ignores it.

### up-arrow/ctrl-r
1. Use either the up-arrow or control-r to open the Atuin picker
2. Pick a command and press <tab> to move it to the command line without running it
3. Edit the command in some way
4. Run the command
5. Atuin will often not report the edited command in its history

### `!!`

Say I run:
```
$ find . -type f -printf "%T@ %p\n" | sort -n
find: -printf: unknown primary or operator
$ g!!
<blah blah blah>
```
running `history` will show a `find` and `gfind` command, while `atuin history list` will only show the find command. Again, this behavior is inconsistent

**Comment by aidan-gibson** [comment]
⬆️⬆️ drives me mental

**Comment by ellie** [comment]
Could you please confirm

1. Your shell - and if using bash, whether you're using blesh or bash-preexec
2. Your OS/terminal
3. Your version of Atuin

@aidan-gibson I'd appreciate the same from you too

I'm going to assume you're both using bash, so if you're able to try out `main` and lmk if the same issue occurs there for you too, that would be great!

**Comment by Samasaur1** [comment]
Ah, I misunderstood your question. I'm using atuin through home-manager, so I believe bash-preexec

**Comment by ahsandar** [comment]
i think i face commands not getting added after I use a command with space to avoid it showing up in history, after that all future commands also don't show up in history

**Comment by Samasaur1** [comment]
I'm gonna keep this open for now, but updating to main tentatively seems to have fixed my problems

**Comment by arcuru** [comment]
@ahsandar I you're using bash, you need to be using bash-preexec or ble.sh for atuin to get the history, as we need the hooks that they provide. It was likely added to your bashrc by the install script. See the bash section of the [Manual Installation Guide](https://docs.atuin.sh/guide/installation/#manual-install)

**Comment by tessus** [comment]
/ref [Issues and logging with Bash?](https://forum.atuin.sh/t/issues-and-logging-with-bash/156?u=tessus) (Forum post)

**Comment by ahsandar** [comment]
ok thanks @arcuru . I have added the preexec again and also built atuin from source. will check if i come across the issue and update.

**Comment by ellie** [comment]
> This is after updating to 18.0.2 a few minutes ago.

Have you restarted your shell after doing so? v18.0.2 only provided an update to the bash plugin, which takes affect when the shell starts

The only other thing I can suggest is updating bash-preexec

```
curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o ~/.bash-preexec.sh
```

> Curious that this seems to be a bash-specific issue?

Atuin relies on shell hooks to save history. These are called before and after a command runs. All the other shells we support provide these out of the box.

Bash does not. In order to get the same thing on bash, we use a plugin. It's basically some neat hacks on top of PROMPT, that work surprisingly well. However, they will not work as well as a native integration, which all other shells provide.

The enter_accept behaviour is a similar story.

Bash _should_ work fine, but as we're finding, there are a whole bunch of edge cases.

**Comment by james-smith-za** [comment]
> Have you restarted your shell after doing so? v18.0.2 only provided an update to the bash plugin, which takes affect when the shell starts

Genius! This was in fact the issue. Thanks!

> Atuin relies on shell hooks to save history. These are called before and after a command runs. All the other shells we support provide these out of the box.
> 
> Bash does not. In order to get the same thing on bash, we use a plugin. It's basically some neat hacks on top of PROMPT, that work surprisingly well. However, they will not work as well as a native integration, which all other shells provide.
> 
> The enter_accept behaviour is a similar story.
> 
> Bash _should_ work fine, but as we're finding, there are a whole bunch of edge cases.

Very interesting. I will take a look at some alternatives. I've heard good things about zsh...

**Comment by ellie** [comment]
Glad it's sorted!
