### ISSUE TITLE
Is there a way for tmux panes to have different histories?

### ISSUE THREAD

**Issue by bechampion** [atuinsh/atuin#1752]
When you run atuin in tmux , panes histories aren't separated ,  which is a big thing for example
![Screenshot at 2024-02-22 10-41-47](https://github.com/atuinsh/atuin/assets/4983875/20e1a509-02ce-49f8-92a9-054e84269899)
See how `rm -rf "*"` is offered as a previous command  in a different pane , this could be quite catastrophic.

The other thing i notice is that once you press enter in a history element is executed right away instead of printing it in the command line and then leaving up to you to run. (you can edit it with tab ,  i think that's not quite intuitive enough)

This is normally fixed in tmux by using 
```
setopt noincappendhistory
setopt nosharehistory
``` 
But i guess when sqlite is the backend is a bit more problematic , i hope all that makes sense.

**Comment by bechampion** [comment]
I can see the filters now , altho global shouldn't be the first one to come by ,  i think it can be configured

**Comment by ellie** [comment]
Yes, try setting `filter_mode="session"`

Docs: https://docs.atuin.sh/configuration/config/#filter_mode

> (you can edit it with tab , i think that's not quite intuitive enough)

What would work better for you?

The original behaviour was what you describe, however many people asked for the ability to immediately execute a command..

Anyway. You can disable with `enter_accept = false`, in your config

Docs: https://docs.atuin.sh/configuration/config/#enter_accept

**Comment by bechampion** [comment]
Hi @ellie i actually closed the issue cause i found all this was configurable ,  thanks again!

**Comment by ellie** [comment]
I provided the details for anyone coming here from Google - we get asked this a  _lot_, and sometimes people find GitHub issues before they find our docs
