### ISSUE TITLE
Ability to remove headers?

### ISSUE THREAD

**Issue by digital-cuttlefish** [atuinsh/atuin#1754]
Hello folks!
I just discovered Atuin and I quite like it!
I'm trying to make it very compact, and I was wondering if we could remove some of the headers
<img width="1496" alt="Untitled" src="https://github.com/atuinsh/atuin/assets/141751473/562ad552-f745-4e89-85bf-e4f09cf54f91">

Mainly the one in the red rectangle (because it doesn't provide much utility), but if we could also remove the blue one that'd be super.

**Comment by ellie** [comment]
You can do this with `show_help = false` in your config file!

Hope that helps

**Comment by digital-cuttlefish** [comment]
Thanks for the quick reply!
Could we also get something to hide the tabs please :)

https://github.com/atuinsh/atuin/blob/cf2cbd23f03286e8e7d12f47fec1023dd119106c/atuin/src/command/client/search/interactive.rs#L502-L527
