### ISSUE TITLE
Feature Request: Add modified command to appear on the history list.

### ISSUE THREAD

**Issue by sungkim11** [atuinsh/atuin#1762]
When I press UP key to see history then select a command using TAB to modify that command. I want that modified command to appear on the history list.

**Comment by ellie** [comment]
Are you using bash?

It already should be, and the only times I've seen where it doesn't has been a bash issue. We're trying to sort the various problems there, but Bash by default lacks most of the features we need to hook into the shell - so everything there is a bit of a kludge.

**Comment by sungkim11** [comment]
Yes, I am using bash. Should I change shell? If so, which one?

**Comment by ellie** [comment]
We also support fish, zsh, nushell and xonsh. I'd suggest zsh for the most bash-like, but fish is also nice.

**Comment by sungkim11** [comment]
Thank you.
