### ISSUE TITLE
Atuin makes me lose control of the terminal

### ISSUE THREAD

**Issue by arthurazs** [atuinsh/atuin#1771]
Hi!

Sometimes if I inspect a command, atuin "breaks" my terminal when I try exiting. Any key I press is registered as symbols such as `[57442;53u`. The only key I can properly use is the `up-arrow` key. `Ctrl+r` are also registered as weird symbols.

If I press the `up-arrow` key, I get back into atuin and I can type any key normally (they do not register as weird symbols).

Here is the only error output I got with this bug, but I don't know how to replicate it:

![image](https://github.com/atuinsh/atuin/assets/3771055/e5247d5e-e81c-48e2-a375-5875027990a3)

Sometimes, inspecting a command solves the issue, sometimes I have to close the terminal and open a new ssh connection.

### Specs

I'm on Windows 11, connecting to a Debian 12 (bookworm) on a VirtualBox (v7.0) over ssh using Alacritty (v0.13.1). I'm using fish (shell, version 3.6.0) and atuin v18.0.1.

**Comment by ellie** [comment]
Should be resolved by #1768
