### ISSUE TITLE
Installation fails on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by SamCastelain** [atuinsh/atuin#1776]
I'm seeing the same installation failure as in #900 now with v18. Could it be that this issue has accidentally been reintroduced?

**Comment by ellie** [comment]
You happened to run the script a few minutes after a release :D The artifacts are still being built I'm afraid.

If you re-run the command, you should be good to go

**Comment by SamCastelain** [comment]
Ah, sorry, I didn't notice it was just released. I just saw there was an update available and wanted to install it. Thanks for the great tool, it installed fine now. Also noticed now you have sponsoring enabled, will join.

**Comment by ellie** [comment]
Glad it's sorted! Thank you so much!
