### ISSUE TITLE
tab to edit just returns blank line

### ISSUE THREAD

**Issue by aaronhollandplum** [atuinsh/atuin#1800]
ENV:
macOS 14.3.1
iTerm2

Hitting 'tab' on history item just returns a blank line. I have the same outcome if I change enter_accept to false, and use enter instead of tab.

**Comment by akinomyoga** [comment]
Thanks for the report. This is a limitation with Bash 3.2/`bash-preexec`. #1794 and #1533 are related. The recommended solution is to update your Bash to the latest version. Another option is to use `ble.sh` instead of `bash-preexec`.

**Comment by ellie** [comment]
Happy to reopen if this turns out to _not_ be related to an older bash version
