### ISSUE TITLE
Unable to register in atuin after installing it on mac

### ISSUE THREAD

**Issue by shaikhAbuzar** [atuinsh/atuin#1808]
Hi

I tried installing Atuin from the official documentation as mentioned [here](https://docs.atuin.sh/). The installation was successful and I got the thank you prompt as well. 
But when I tried registering it gave me the following error:

```shell
atuin login 
Error: could not load client settings

Caused by:
    failed to deserialize: The system's UTC offset could not be determined

Location:
    atuin-client/src/settings.rs:638:26
```

I am using a Mac Book Pro M2 and Mac OS Sonoma 14.3.1

Please let me know if you need any more info.

Thanks

**Comment by iwahbe** [comment]
I just tried building atuin from master and I'm getting the same result. I'm not getting this on the version I have installed from brew: `atuin 18.0.1`.

**Comment by ellie** [comment]
Hey! Sorry about this - there's a workaround here: https://github.com/atuinsh/atuin/issues/1749#issuecomment-1959634806

I still haven't been able to figure out why this happens or replicate the issue, so will probably remove the timezone detection feature.
