### ISSUE TITLE
AI support.

### ISSUE THREAD

**Issue by hongyi-zhao** [atuinsh/atuin#1843]
Can we add AI, e.g., openai-based tools, support in atuin?

**Comment by ellie** [comment]
We _could_, but what problem do you envision this solving?

I would like to properly classify a problem that users have, and then if LLMs are identified as the optimal solution then it makes sense.

**Comment by hongyi-zhao** [comment]
> We could, but what problem do you envision this solving?

Maybe just like the feature described [here](https://github.com/ddworken/hishtory#advanced-features):

![image](https://github.com/atuinsh/atuin/assets/11155854/2d4ecb67-d391-415d-b20c-b392b6b94c03)

**Comment by ellie** [comment]
No thank you.

Even ignoring any possible moral problems with such a system, I'm against Atuin suggesting anything that is incorrect, that isn't sourced from the users' own history.

The possibility of an LLM hallucinating and suggesting the wrong command is not a risk I'd like to shoulder. I also do not wish to introduce a network round trip to the search, unless it's very very low latency.

There are many CLI tools that are explicitly enable you to use LLMs for suggestions - those would be better suited.
