### ISSUE TITLE
doctor does not detect ble or pre-exec

### ISSUE THREAD

**Issue by tessus** [atuinsh/atuin#1849]
I believe there are 2 issues with the output:

- neither ble nor pre-exec are detected
- the harddisk is shown twice (might be an upstream issue)

This is the current output on git main (c97f2375ad6bd52905308ca22249a6cab97c6bc0):

```
$ ./target/release/atuin doctor
Atuin Doctor
Checking for diagnostics

[Shell] If you are using Bash, Atuin requires that either bash-preexec or ble.sh be installed. Read more here: https://docs.atuin.sh/guide/installation/#bash

Please include the output below with any bug reports or issues

atuin:
  version: 18.0.2
  sync:
    cloud: false
    records: true
    auto_sync: true
    last_sync: 2024-03-10 22:08:50.372056 +00:00:00
shell:
  name: bash
  plugins:
  - atuin
system:
  os: Darwin
  arch: x86_64
  version: '14.4'
  disks:
  - name: Macintosh HD
    filesystem: apfs
  - name: Macintosh HD
    filesystem: apfs
```

**Comment by ellie** [comment]
For the first issue, are either of

- BLE_ATTACHED
- bash_preexec_imported

defined in your shell?

For the second issue, it's likely the recovery partition showing up. What's the output of `diskutil list`?

**Comment by akinomyoga** [comment]
`BLE_ATTACHED` is not exported. Even if it is exported, it's unreliable because the exported variable is not ensured to be exported by the direct parent process. One way is to export `BLE_SESSION_ID` (which contains the value `<START>/<PID>`) and test if `<PID>` matches Atuin's PPID.

**Comment by ellie** [comment]
I'm aware it's not exported. Most plugins we may need to be able to detect don't export useful things to show their presence 

We spawn an interactive subshell and dump the env from there. It's a hack, but so far the most useful way I've found to be able to detect unexported env.

**Comment by ellie** [comment]
The goal of the doctor isn't to be 100% reliable on all systems but to reduce the support load down for the obvious cases of a fairly basic setup done incorrectly. This is the majority of the support I get

Even for those cases, the info dump is still useful  

I suspect there will be a variety of edge cases for complex shell setups, but for users who've customised their system that much, it's unlikely that the problem is that they've not fully read/understood the docs

**Comment by akinomyoga** [comment]
https://github.com/atuinsh/atuin/blob/c97f2375ad6bd52905308ca22249a6cab97c6bc0/atuin/src/command/client/doctor.rs#L30-L32

I see. So it's actually testing the shell variables not just "environment" variables. I'll take a look.

**Comment by akinomyoga** [comment]
The reason that `ble.sh` is not detected is simple. `ble.sh` will not be enabled when it is not a true interactive session. It performs a several checks to detect it. For example, 1) it checks whether it is an interactive Bash session. 2) It checks if the current Bash session receives `-c command` in its arguments (this is not satisfied this time) 3) It checks if the line editing of Readline is enabled  4) Depending on the setup, it attaches to the session when `PROMPT_COMMAND` is called (this is also unsatisfied this time). So it would be hard to trick `ble.sh`.

For `bash-preexec`, as far as I test it, `atuin doctor` seems to correctly detect it.

**Comment by ellie** [comment]
Is there any reliable way to detect that ble is installed and active?

**Comment by akinomyoga** [comment]
I have an idea. I'm now trying to implement it.

**Comment by tessus** [comment]
> For the first issue, are either of
> 
>     BLE_ATTACHED
>     bash_preexec_imported
> 
> defined in your shell?

Yes, they are set, but not exported. I have read all the comments and the comments in the PR.
I was just confused that even when I had `ble.sh` running, doctor showed me a warning in red and ble was not listed under plugins. I thought I read the code correctly and it should show up under plugins.

I agree that this is not an ideal situation and understand the difficulties. 

> What's the output of `diskutil list`?

```
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk0
   1:                        EFI EFI                     314.6 MB   disk0s1
   2:                 Apple_APFS Container disk1         1.0 TB     disk0s2

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +1.0 TB     disk1
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD - Data     941.5 GB   disk1s1
   2:                APFS Volume Preboot                 2.1 GB     disk1s2
   3:                APFS Volume Recovery                1.2 GB     disk1s3
   4:                APFS Volume Macintosh HD            10.2 GB    disk1s4
   5:              APFS Snapshot com.apple.os.update-... 10.2 GB    disk1s4s1
   6:                APFS Volume VM                      2.1 GB     disk1s6
```

Hmm, this is the typical setup when there is one physical HDD or SSD, and one big partition on it. All the other stuff is macOS specific cruft (recovery, preboot for Filevault, ...).

Ok, so it seems that this is an upstream issue. No matter what, there is one physical drive with one de-facto partition - the only partition I can access when I run the OS. And it is none of the above. Because `Macintosh HD - Data     941.5 GB` is named `Macintosh HD` in the OS, but differently in the partition map.
I thought that the doctor would show me the disk that is accessible to me which is `Macintosh HD`. Apparently this is not the case. All good.

**Comment by tessus** [comment]
I think this issue can be closed. Thanks @akinomyoga for the PR.

**Comment by akinomyoga** [comment]
thanks!
