### ISSUE TITLE
`atuin sync` fails with `error decoding response body`

### ISSUE THREAD

**Issue by balsa-sarenac** [atuinsh/atuin#1855]
When running `atuin sync` I have this error message:

```bash
atuin sync
Error: error decoding response body: expected value at line 1 column 1

Caused by:
    expected value at line 1 column 1

Location:
    /private/tmp/atuin-20240226-5245-z9ks0z/atuin-18.0.2/atuin-client/src/api_client.rs:161:21
```

I've looked into similar issues (https://github.com/atuinsh/atuin/issues/1786 and https://github.com/atuinsh/atuin/issues/1462) and upgraded atuin to newest version, but it still doesn't work.

I'm happy to supply any additional information.

**Comment by ellie** [comment]
Are you self hosting?

If so, please provide as much information as possible about your setup

**Comment by ellie** [comment]
Could you let me know the username you signed up with?

**Comment by balsa-sarenac** [comment]
Update, it started working now, I haven't changed anything in the meantime. Thanks for helping out!
