### ISSUE TITLE
Add a systemd service file

### ISSUE THREAD

**Issue by svenstaro** [atuinsh/atuin#1864]
Hey, I think it would make sense to have a systemd service file upstream. It should source environment variables from `/etc/default/atuin`.

I think something like this could work:
```ini
[Unit]
Description=Start the atuin sync service

[Service]
ExecStart=atuin server start
Restart=on-failure
User=atuin
EnvironmentFile=/etc/default/atuin
PrivateTmp=yes
PrivateUsers=yes
PrivateDevices=yes
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=yes
ProtectClock=yes
ProtectControlGroups=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectProc=invisible

[Install]
WantedBy=multi-user.target
```

If you like this, I could make an MR for this along with a sysusers file to create the `atuin` user.

**Comment by ellie** [comment]
Sounds good to me! I'd also really appreciate it if you could update the [docs](https://github.com/atuinsh/docs) with information on how to use this 🙏

**Comment by inglor** [comment]
I tried to do that for Arch Linux package and had issues with atuin server searching for configuration in hardcoded $HOME variable and wanted write access to it. Also it would be nice for DB_URI to support (passwordless) socket in linux - couldnt' figure out how to set this up in sqlx.

For reference my work in progress files:

`atuin.env`
```
ATUIN_CONFIG_DIR=/var/lib/atuin
ATUIN_HOST="127.0.0.1"
ATUIN_PORT=8888
ATUIN_OPEN_REGISTRATION=true
ATUIN_DB_URI="postgres://username:password@localhost/atuin" # socket how?
```
`atuin.service`
```
[Unit]
Description=Atuin server
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
User=atuin
Group=atuin
ExecStart=/usr/bin/atuin server start
ReadOnlyPaths=/etc/atuin

EnvironmentFile=/etc/atuin/atuin.env
ReadWritePaths=/var/lib/atuin

# Hardening options
CapabilityBoundingSet=
AmbientCapabilities=
NoNewPrivileges=true
ProtectHome=true
ProtectSystem=strict
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
PrivateTmp=true
PrivateDevices=true
LockPersonality=true

[Install]
WantedBy=multi-user.target
```
`atuin.sysusers`
```
u atuin - "Atuin user" - -
```
`atuin.tmpfiles`
```
d %L/atuin 750 atuin atuin - -
d %t/atuin 750 atuin atuin - -
d %S/atuin 750 atuin atuin - -
```

**Comment by svenstaro** [comment]
@inglor Wouldn't it be fine to give it ReadWrite access to its own home, then? It has its own user anyway. My question is though: What is actually stored there, given that all data should be put into the DB?

**Comment by svenstaro** [comment]
I opened up drafts in both repos. Happy for reviews/tests/contributions.

**Comment by tessus** [comment]
The problem is that it is not possible to run atuin under a service user that does not have a home dir, because it tries to write a `server.toml` and abends if it can't.

I solved this by settting the `HOME` env var in systemd to the directory where the server config is located.

```
[Unit]
Description=atuin
After=network.target postgresql.service
Requires=postgresql.service
# Remove postgresql.service above, if database is remote

[Service]
Type=simple
User=atuin
Group=atuin
EnvironmentFile=/etc/atuin/atuin.cfg
WorkingDirectory=/etc/atuin
Environment=HOME="/etc/atuin"
ExecStart=/usr/sbin/atuin server start
StandardOutput=append:/var/log/atuin/atuin.log
StandardError=append:/var/log/atuin/atuin.log
Restart=on-failure
RestartSec=3
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

**Comment by ellie** [comment]
> configuration in hardcoded $HOME 

> it is not possible to run atuin under a service user that does not have a home dir

Neither of the above are quite true. If you look at what @heftig has shared, the [docs](https://docs.atuin.sh/configuration/config/), or the [code](https://github.com/atuinsh/atuin/blob/b04fc471deb923937b8ef9aab2f39301f8457894/atuin-server/src/settings.rs#L47), you'll see `ATUIN_CONFIG_DIR`. 

This can be set to something other than $HOME, to solve exactly the problems you raise.

The _only_ time it writes to that directory is to set the default config file. I guess we could have an option to disable this, though it won't do it if the file already exists.

**Comment by tessus** [comment]
Ah, I missed that, even though I read the docs. I hid my previous comment, since it doesn't add any useful info. Thanks for letting me know about the `ATUIN_CONFIG_DIR` env var.

I'll update the guide on the forum accodingly, or better yet a note. It does not matter whether `HOME` or `ATUIN_CONFIG_DIR` is set in the unit file.

**Comment by svenstaro** [comment]
I changed my PRs according to the suggestions in this thread and I think they should now be good to go. I opted to remove the systemd env file and went with letting atuin create its own default config in `/etc/atuin`.
