### ISSUE TITLE
Problems understanding history_format

### ISSUE THREAD

**Issue by Jorres** [atuinsh/atuin#1894]
Hey! I'm loving Atuin this far, happy user for over two years. Thank you for your amazing work!

I'm having difficulties understanding the piece of docs about `history_format`: https://docs.atuin.sh/configuration/config/#history_format

For simplicity, assume I want to make the `duration` field disappear. 

It seems to work when I invoke atuin CLI like this:

```
atuin history list --format "{time} - {directory}$\t{command}"
...
2024-03-19 12:09:10 - /home/jorres$     ls
```

However, I almost never invoke CLI. I almost always use the TUI. The option does not seem to work in the TUI. Specify the config option like this:
```
history_format = "{time}\t{command}"
```

Please see the following screenshot, the format does not seem to have changed:

![image](https://github.com/atuinsh/atuin/assets/26899407/cf1b40b3-1b2c-4458-8a23-b9a1f9f23ce9)

Am I doing something wrong? I would assume that TUI is the primary use case for many users, it would be unexpected that something works in the CLI, exists in the stable documentation, but does not work in the TUI. Thank you for the help!

**Comment by ellie** [comment]
> Hey! I'm loving Atuin this far, happy user for over two years. Thank you for your amazing work!

Thank you, glad Atuin is working well for you!

I've just updated the docs, but history_format only applies to CLI output. The TUI search output is not configurable at this time

**Comment by edte** [comment]
> > Hey! I'm loving Atuin this far, happy user for over two years. Thank you for your amazing work!
> 
> Thank you, glad Atuin is working well for you!
> 
> I've just updated the docs, but history_format only applies to CLI output. The TUI search output is not configurable at this time

<img width="744" alt="截屏2024-04-11 16 18 01" src="https://github.com/atuinsh/atuin/assets/50194671/545c854b-110e-4cc9-b435-5c0c7975c32b">

the docs seems to be no explanation, and I hope TUI will also add this function. I think most people like use TUI much more than CLI.

**Comment by ellie** [comment]
> the docs seems to be no explanation

more than happy to take suggestions as to how it can be written more clearly

I'm closing this issue for now as it's about documentation clarity, and not a request for changing the TUI format

**Comment by N0ciple** [comment]
Hello @Ellie,
Thank you for your work on Atuin!

I recently came across this issue as I had the same misunderstanding as @Jorres. Your explanation in the thread helped me understand that the history_format only applies to the CLI output.

Since you mentioned you’re open to suggestions on how to clarify this in the documentation, perhaps including your sentence:
> `history_format` only applies to CLI output. The TUI search output is not configurable at this time.

would help users grasp this more easily.

Thanks again!

**Comment by electrovir** [comment]
I just spent a considerable amount of time trying to figure out why my `history_format` changes weren't applying to the TUI. A documentation update would be very helpful here. In particular, I didn't even know that there was a CLI vs GUI distinction (until I found and read this).
