### ISSUE TITLE
Add support for KDE Neon

### ISSUE THREAD

**Issue by dacog** [atuinsh/atuin#1909]
Hi, 

I'm using Atuin in several systems, and now I installed KDE Neon with Plasma 6 on a notebook and I noted that it tries to install from cargo.

I checked the install.sh script, and run some parts of if manually.

Because KDE Neon is based on Ubuntu 22.04, it should also use the .deb for Ubuntu IMHO), but the command

`grep -Po '(?<=^ID=).*$' /etc/os-release | tr '[:upper:]' '[:lower:]'`

returns "neon", which is not in the OS list in the script. I also tested installingthe .deb file available in Realeases manually without issues.

I added it and created a PR https://github.com/atuinsh/atuin/pull/1908

If I should change anything else, please let me know.

Best,

Diego

**Comment by ellie** [comment]
PR merged, thanks!
