### ISSUE TITLE
Feature Request: ignore failed commands

### ISSUE THREAD

**Issue by leana8959** [atuinsh/atuin#1912]
Hello,

Before `atuin` I used [this plugin](https://github.com/meaningful-ooo/sponge) for fish, it stops fish from registering the commands that failed into history (using return codes). It also has some settings to change which return codes should be filtered.
This would be a nice feature to have in the future.

Thanks and I appreciate the project =)

**Comment by ellie** [comment]
Sounds good to me! Might make sense to have some sort of filtering section in the settings for grouping all this configuration

**Comment by andrewcrook** [comment]
+1 for this

**Comment by ellie** [comment]
Resolved by #1957 

```
store_failed = false
```

Into your config file. 

I'd still like to add the filtering section, but will likely be redoing the config file soon anyway
