### ISSUE TITLE
Don't know what's wrong I setup using Cargo command "cargo install atuin"

### ISSUE THREAD

**Issue by uuc110** [atuinsh/atuin#1941]
![image](https://github.com/atuinsh/atuin/assets/44457947/0872591e-8285-48d8-a25c-9971eebc0930)
I'm getting this issue anyone know? and also those who are might be using Nushell my whole config seesm to have some issue. whatever i set up like starship shell or atuin, using use" , source ~/.local/share/atuin/init.nu it jsut get reset

**Comment by ellie** [comment]
Resolved in #1913, will be released next week.

Nu makes breaking changes pretty often I'm afraid (it's still under very active development, which is fair).

In future, please use the issue template.
