### ISSUE TITLE
[Bug]: Atuin migration Issue?

### ISSUE THREAD

**Issue by uuc110** [atuinsh/atuin#1944]
### What did you expect to happen?

I installed and it wasn't working. I was facing the issue #1913. I already tho did following things after installtion
1. created Atuin Public server account
2. imported my History

### What happened?

I Deleted my .cargo folder from my userData and reinstalled the Atuin. after Which I faced this issue

### Atuin doctor output

```yaml
C:\WINDOWS\system32> atuin doctor                                                
Error: migration 20210422143411 was previously applied but has been modified

Caused by:
    migration 20210422143411 was previously applied but has been modified

Location:
    atuin\src\command\client.rs:102:18
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
`C:\WINDOWS\system32>.`

While Atuin successfully builds and runs on Windows, we do not officially support it - it's not tested and may break at any time.

I suspect at some point you may have ran a build from `main`?

**Comment by uuc110** [comment]
Nope. I simply installed rustchain GNU toolbox and then ran Cargo install atuin, and second time when I installed, I used cargo install --path .

**Comment by uuc110** [comment]
I used the Master branch. downloaded the zip and then after extraction used the command "cargo install --path ."

**Comment by ellie** [comment]
For some extra context - migrations will always apply fine between stable releases. It is a bug if they do not.

They usually should while following `main` or weekly releases, but may not always. There may sometimes be manual intervention required. Running the bleeding edge can have issues.

**Comment by uuc110** [comment]
so after deleting should I again use the "cargo install atuin" rather then using the source code to install

**Comment by ellie** [comment]
That's right

**Comment by uuc110** [comment]
Hey I'm getting some issue in installing latest release of Atuin using cargo install. 
![image](https://github.com/atuinsh/atuin/assets/44457947/21f4cb0c-b2b2-41d8-abcb-c32868b9db97)
as you can see its installing 18.1.0, not the latest release

**Comment by ellie** [comment]
18.1.0 is the latest release

**Comment by uuc110** [comment]
did that issue got fixed yet? this one?
> Nushell will deprecate --redirect-stderr f
