### ISSUE TITLE
[Bug]: Inconsistent file naming in release

### ISSUE THREAD

**Issue by DarkPark** [atuinsh/atuin#1983]
### What did you expect to happen?

The same file naming convention applied to all release packages.

### What happened?

![image](https://github.com/atuinsh/atuin/assets/1189578/542502c1-9e4d-4736-ac7f-e073269ea284)

### Atuin doctor output

```yaml
irrelevant
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
It's annoying, but changing it at this point will likely break a bunch of downstream scripts/etc. I'd rather leave as-is, if the only issue is neatness or consistency.
