### ISSUE TITLE
Error: attempting to decrypt with incorrect key.

### ISSUE THREAD

**Issue by hegepr** [atuinsh/atuin#2007]
Seems, I messed it up totally: I started `atuin server start `on machine _A_, registered user _me_ on machine _A_, copied `~/.local/share/atuin/key `from machine _A_ to `~/.local/share/atuin/key` on machine _B_. Then i logged in on both machines as user _me_. On machine _A_ I could `atuin sync -f` without error - on _machine B_ sync got the error. Could anyone help me?

**Comment by ellie** [comment]
> copied ~/.local/share/atuin/key

Please follow the guide [here](https://docs.atuin.sh/guide/sync/#login). Please don't copy around internal files as often there's associated processes that need to run.

Closing as this is not using the issue template.
