### ISSUE TITLE
Feature: Build .deb packages for ARM

### ISSUE THREAD

**Issue by pktiuk** [atuinsh/atuin#2023]
It would be good to also provide some ARM build on tour release page.   

GitHub doesn't provide ARM runners yet (But it may [change soon](https://github.com/orgs/community/discussions/19197), [link 2](https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/) ), but it may be done in the same way, as `atuin-vxxx0-aarch64-unknown-linux-gnu.tar.gz ` builds are prepared.

**Comment by xvello** [comment]
Instead of building more deb & rpm packages in GitHub Actions, I encourage you to take a look at https://build.opensuse.org/. Although it's maintained by openSUSE, they also support building and publishing packages for Fedora, Debian & Ubuntu, on several architectures.

Here's a demo of packaging a Rust program with it: https://www.youtube.com/watch?v=J__6pqGbR3o

**Comment by pktiuk** [comment]
WOW this is a great tool. I will certailny check it out.

**Comment by ellie** [comment]
Looks like OBS has an atuin package! https://build.opensuse.org/package/show/utilities/atuin?rev=47

Although I faced several 500 errors and weird issues logging in

**Comment by xvello** [comment]
This seems to be the official [atuin package in openSUSE](https://software.opensuse.org/search?baseproject=openSUSE%3AFactory&q=atuin), as `utilities` is an official project for the distro. I like how they ship the shell integrations in separate packages BTW.

Maybe someone could reach out to the person committing there and ask for help about reusing this work for other RPM distros.

**Comment by ellie** [comment]
I've given this some thought, and going forwards we will no longer build distro-specific install files. If package maintainers on those platforms wish to maintain Atuin for their distro then they can, but I don't think we should concern ourselves with how different distros wish to have things packaged. We now use [cargo-dist](https://github.com/axodotdev/cargo-dist)

We can build binaries for as many platforms as we can, and provide an easy way to install them. Beyond that is out of our hands.

I think it would be better to focus on building binaries for more platforms, vs wrapping things up for different package managers

**Comment by philclifford** [comment]
@ellie I took from this and the assets attached to the latest release that you don't plan to continue building .deb assets. (hence the "deprecation" above) If I'm wrong please let me know.
If no further .deb assets are to be built then apologies in advance for poorly-worded "deprecation" messages we may put out to users who have installed `atuin` using `deb-get`: we love and value `atuin` immensely and I will try to direct those users to the best installation and upgrade path going forward.

**Comment by ruperthair** [comment]
As my Google search for an atuin Debian package brought me here, I thought I would add how I made one with Docker, in case it's of use to others:

```
$ docker run -it --name atuin rust bash
# apt-get update && apt-get install protobuf-compiler
...
# git clone https://github.com/atuinsh/atuin.git
# cd atuin/
# git checkout v18.3.0
...
# cargo deb -p atuin
...
...
...
# exit
$ docker cp atuin:/atuin/target/debian/atuin_18.3.0-1_arm64.deb .
$ sudo dpkg -i atuin_18.3.0-1_arm64.deb
...
$ atuin -V
atuin 18.3.0
$ dpkg -L atuin
/usr
/usr/share
/usr/share/doc
/usr/share/doc/atuin
/usr/share/doc/atuin/README.md
/usr/share/doc/atuin/copyright
/usr/bin
/usr/bin/atuin
$
```
