### ISSUE TITLE
[Bug]: no disable

### ISSUE THREAD

**Issue by iconoclasthero** [atuinsh/atuin#2049]
### What did you expect to happen?

i want this it stop. i tried atuin disable and atuin off
either one of those should work to stop something I installed by clicking a url that installed something automatically via curl.
no answer here:

$ atuin help
atuin 18.2.0
Ellie Huxtable <e@elm.sh>
Magical shell history

Usage:
  atuin <COMMAND>

Commands:
  history          Manipulate shell history
  import           Import shell history from file
  stats            Calculate statistics for your history
  search           Interactive history search
  sync             Sync with the configured server
  login            Login to the configured server
  logout           Log out
  register         Register with the configured server
  key              Print the encryption key for transfer to another machine
  status           Display the sync status
  account          Manage your sync account
  kv               Get or set small key-value pairs
  store            Manage the atuin data store
  dotfiles         Manage your dotfiles with Atuin
  init             Print Atuin's shell init script
  info             Information about dotfiles locations and ENV vars
  doctor           Run the doctor to check for common issues
  default-config   Print example configuration
  server           Start an atuin server
  uuid             Generate a UUID
  contributors     
  gen-completions  Generate shell completions
  help             Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help
  -V, --version  Print version

### What happened?

i installed it.

https://docs.atuin.sh/uninstall/
doesn't tell me how to remove it in linux.

### Atuin doctor output

```yaml
no.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iconoclasthero** [comment]
also, this is a problem in my ~/.bashrc:
```
. "$HOME/.googlerc"

#. "$HOME/.cargo/env"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"




[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
eval "$(atuin init bash)"
```

**Comment by iconoclasthero** [comment]
WRT to your code of conduct, i consider it a violation of the code of conduct for a developer to have a curl line like that.  Also, not to have a way to stop something like atuin which dramatically changes how i interact with my shell after install.  Also, not to have a clear way to uninstall something like this.  

I have no idea if it's useful or something I want to use long-term, but you have got to add a way to stop the function of it that can be executed from looking at --help.

**Comment by ellie** [comment]
> I installed by clicking a url that installed something automatically via curl.

Could you explain some more about this? It's really concerning if your system will install a package or run a command purely by clicking a link

> WRT to your code of conduct, i consider it a violation of the code of conduct for a developer to have a curl line like that.

I'm not really sure how this makes sense.

>  doesn't tell me how to remove it in linux.

The uninstall page says that we use your system package manager wherever possible

> Wherever possible, our install script will use your system package manager.

It also says that you need to remove the "atuin init" line from your shell config, that you've included in a comment here. If you do that, Atuin will stop working.

If you'd included the `atuin doctor` output then I'd be able to advise you. The output of the install script also tells you how the install proceeded, so you can reverse the steps.

Due to the lack of doctor output, I'll be closing this issue.
