### ISSUE TITLE
serde_yaml is deprecated

### ISSUE THREAD

**Issue by ellie** [atuinsh/atuin#2081]
As of the latest release, serde_yaml is deprecated. We need to find a replacement, and swap it out

**Comment by xvello** [comment]
Seems to be only used in the doctor output, let's rip it out and use either the pretty-print debug formatter with `println!("{:#?}", dump);`, or `serde_json::to_string_pretty`?

The output will be a bit longer, but who cares.

**Comment by hesampakdaman** [comment]
Did a very small PR, just replaced the call with the suggested `serde_json::to_string_pretty` and removed `serde_yaml`.
