### ISSUE TITLE
Atuin-daemon build failure in Fedora COPR chroot

### ISSUE THREAD

**Issue by cyqsimon** [atuinsh/atuin#2113]
I noticed that v18.3.0 now requires `protobuf-compiler` during build. But after adding the build dependency, I got a `protoc` failure:

```
error: failed to run custom build command for `atuin-daemon v0.2.0 (/builddir/build/BUILD/atuin-18.3.0/crates/atuin-daemon)`

Caused by:
  process didn't exit successfully: `/builddir/build/BUILD/atuin-18.3.0/target/release/build/atuin-daemon-f497d7538312abf4/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=./proto/history.proto
  cargo:rerun-if-changed=./proto

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: google/protobuf/timestamp.proto: File not found.\nhistory.proto:4:1: Import \"google/protobuf/timestamp.proto\" was not found or had errors.\n" }
```

I have little to no experience with protobuf so I really don't know where to go from here.

**Comment by ellie** [comment]
I have no experience with fedora or COPR, but which package did you install?

Something I just read suggested `protobuf-devel` instead of `protobuf-compiler`

**Comment by cyqsimon** [comment]
I installed `protobuf-compiler` because the first error I ran into was "`protoc` not found" or something like that. I suspect I actually need both.

Will try and get back to you in a bit.

**Comment by cyqsimon** [comment]
Yep that's it. Had to declare both because the way RH packaged protobuf. `protobuf-compiler` provides `protoc` and `protobuf-devel` (or `pkgconfig(protobuf)`) provides the libraries.

For any and all future readers doing RPM packaging, just add this to your spec file:
```
BuildRequires:  pkgconfig(protobuf) protobuf-compiler
```

---

Also, can you please consider feature-gating the daemon? This would allow packaging on older distros that don't ship protobuf3 (e.g. EL7).

**Comment by LecrisUT** [comment]
EL7 is out of support, and you would have many other issues over there. Btw what are you building atuin on copr for? Might be worth discussing it over at https://github.com/SriRamanujam/atuin-rpmspec since we are preparing to submit for Fedora next week

**Comment by ellie** [comment]
Looks like this is resolved! 😄 

Otherwise heads up - the daemon is eventually going to become default behaviour, and we're also likely to use protobufs in more places - vs the manual an error-prone serialization we've been doing so far. The build environment will therefore need proto3 available

**Comment by cyqsimon** [comment]
> EL7 is out of support, and you would have many other issues over there.

I mean, technically EL7 is not EOL just yet, but yes I get your point.

> Btw what are you building atuin on copr for?

I build and maintain a small collection of Rust CLI tools for RHEL [here](https://copr.fedorainfracloud.org/coprs/cyqsimon/el-rust-pkgs/) for my various servers. Admittedly right now most of them are on EL9 with a couple on EL8 and none on EL7 anymore, but AFAIK a few of my friends are still using this repo on EL7 (because corporate legacy tech-debt certification blah blah blah). Anyways, yeah I do need think about what to do after EL7 goes EOL.

> Might be worth discussing it over at https://github.com/SriRamanujam/atuin-rpmspec since we are preparing to submit for Fedora next week

That's great to hear! Please ping me if there is anything I can help with.

**Comment by LecrisUT** [comment]
No worries, I think it's good to have these various approaches in case we pick up on some edge case behavior. E.g. right now I am investigating a bug with sqlx-sqlite behaving differently with system and bundled sqlite, which has gone under the radar all this time because nobody packaged sqlx till now. (I think I've found the root cause btw)

> But FYI, my packaging job is pretty crude and is very different from how Fedora prefers things to be done.

Indeed and it is a pain to maintain, but there are distro-related reasoning for doing it. I don't recommend or expect upstream to support it. But the guidelines do specify another vendoring approach and that is basically what is done over there and in your copr.

Still thanks for the reference it's assuring to see that it works for EL9 and EL8 since I intend to package for EL9 as well, but haven't run any tests there. What's interesting though is that your tests run successfully even without setting up a postgres server :thinking:

**Comment by cyqsimon** [comment]
> What's interesting though is that your tests run successfully even without setting up a postgres server 🤔

Oh yeah I know exactly what you're talking about.

Short answer is those tests are actually skipped because I ran `cargo test` with `--lib`. If you take a look at the blame of [the source file](https://github.com/cyqsimon/el-rust-pkgs-spec/blame/master/specs/atuin.spec) you'll see.

Long answer is I ran into this same issue back when 16.0 was released. I was asking COPR maintainers on their IRC channel (they've since moved to Matrix I believe) about setting up a Postgres server in the chroot. Forgot why but basically I couldn't use systemd to start a service. Someone told me about some Postgres RPM macro and I experimented with it on and off for a day or two. In the end I couldn't get it to work, so I just did [what Arch did](https://gitlab.archlinux.org/archlinux/packaging/packages/atuin/-/blob/main/PKGBUILD).

**Comment by LecrisUT** [comment]
For Fedora and "Fedora-lite" we have another option: https://github.com/SriRamanujam/atuin-rpmspec/pull/11/files#diff-5c59fd392dd00e050a1cdeee425f932d5988c7a4ef6a859ca6c789b4022ac2e1R77-R84 :wink:

**Comment by cyqsimon** [comment]
Ah yes yes. That's exactly what they pointed me to. Might not work on EL chroots though, watch out for that.

**Comment by ellie** [comment]
Since #2119 that is no longer the case, we bundle everything required to build

**Comment by Kyshman** [comment]
Understood. Would have wondered how 3 different machines all using the install script `cargo install atuin` failed at the same exact point with their only commonality being RHEL based distros :smiley:

**Comment by georgemarselis-nvi** [comment]
Sorry to necropost:

Just confirming that in Fedora 41 I had the same problem and `dnf install protobuf-devel` did the trick.
