### ISSUE TITLE
manual/info: atuin kv/uuid not documented on the website

### ISSUE THREAD

**Issue by Jiehong** [atuinsh/atuin#2114]
Hello,

While looking at `atuin help`, I saw some subcommands that aren't documented on the atuin website, such as `atuin kv` (and 'atuin uuid`).

It would be nice if those would be documented.

For example, I have a few questions:

- `atuin kv` seems like a nano redis-like store. What are example usecases this is good for?
- `atuin uuid` does not say which type of uuid is created, and does not allow choosing other versions of uuid. Also, what is the usecase for it?

Both commands _seem_ potentially useful, but it would help their discoveries if they both were documented with potential usecases on the website.

`atuin info`: `version: 18.3.0`

**Comment by ellie** [comment]
> seems like a nano redis-like store

Yep! It was part of the sync v2 testing and needs some UX adjustment before we advertise wider use

> does not say which type of uuid is created, and does not allow choosing other versions of uuid. Also, what is the usecase for it?

It's used by our shell integration, and not intended for you to use. It may change at any time. 

>  but it would help their discoveries if they both were documented with potential usecases on the website.

That's exactly why they _aren't_ documented :D Both are fine to use if you poke around, but aren't something I want to advertise the use of. That may change for the KV, but not yet
