### ISSUE TITLE
[Bug]: atuin history empty

### ISSUE THREAD

**Issue by bobblkabb** [atuinsh/atuin#2115]
### What did you expect to happen?

Running atuin 0.12 on latest SLES 15.5. Got eval "$(atuin init bash)" in my .bashrc.
It should show the past commands in the atuin shell.

### What happened?

History is empty and doesn't fill up.

### Atuin doctor output

```yaml
Not available (v < v18.1.0)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
Hey! Could you please update to the latest version and reopen if this still occurs. v12 is from 2022.
