### ISSUE TITLE
Feature Request: Add self upgrade option for atuin cli

### ISSUE THREAD

**Issue by mjcc30** [atuinsh/atuin#2121]
Add self upgrade option for atuin cli to upgrades outdated tool versions
without the need to wait for new os package release

Like others tools like mise as an exemple: https://github.com/jdx/mise

Usage:
  atuin COMMAND

Commands:
upgrade   Upgrades outdated tool versions [aliases: up]

**Comment by ellie** [comment]
We have it with 18.3!

If you use the installer listed here: https://github.com/atuinsh/atuin/releases/tag/v18.3.0

You'll have `atuin-update  alongside `atuin`, which will perform the update.

Currently our installer will use the system package manager where available (and this installer where it isn't), however once we've confirmed that the new script works as expected across platforms then it will become the default behaviour

**Comment by mjcc30** [comment]
Ok sorry my bad, i was on 18.2
just change to script install and it works perfectly!
thank you !
