### ISSUE TITLE
Locking issues with NFS home directory

### ISSUE THREAD

**Issue by mbhall88** [atuinsh/atuin#2125]
### What did you expect to happen?

Use `atuin` as usual

### What happened?

I was using atuin v17, then I started randomly getting errors saying 

```
Error: error returned from database: (code: 5) database is locked

Caused by:
    (code: 5) database is locked
```

anytime I did anything in the terminal.

So I upgraded to the latest atuin (v18.3.0) and now anytime I do anything in the terminal I get the following

```
 Error: pool timed out while waiting for an open connection

Location:
    crates/atuin/src/command/client.rs:126:18
Error: pool timed out while waiting for an open connection

Location:
    crates/atuin/src/command/client.rs:126:18
```

I made a backup of my atuin history.db (and associated) files.

I basically can't use my shell at the moment as a result.

I don't use sync or anything like that - just store it all locally. The disk has plenty of storage space still available too.

### Atuin doctor output

```yaml
$ ATUIN_LOG=debug atuin doctor
Error: pool timed out while waiting for an open connection

Location:
    crates/atuin/src/command/client/history.rs:564:18
2024-06-13T04:57:11.568769Z DEBUG atuin_client::database: opening sqlite database at "/home/mihall/.local/share/atuin/history.db"
Error: pool timed out while waiting for an open connection

Location:
    crates/atuin/src/command/client.rs:126:18
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
Are you using ZFS?

**Comment by mbhall88** [comment]
Yeah, I removed the init from my shell setup. (Gosh it has made me realise how much I rely on and love atuin.)

I don't know if I am using ZFS, this is on my university computing server (and so don't have `sudo` access) and I don't know how to check if it's ZFS...As I said, it has been working fine with v17 for ages, then just started getting the 'database is locked' errors. So I upgraded, got the timed out errors. I even tried deleting my database (have backed it up in case I can retrieve it) and reverting back to v17 but still get the database is locked errors. 

I'm at a bit of a loss...

**Comment by ellie** [comment]
> (Gosh it has made me realise how much I rely on and love atuin.)

<3 

> I don't know if I am using ZFS, this is on my university computing server (and so don't have sudo access) and I don't know how to check if it's ZFS...

You can run `df -T` to check, assuming that it's linux. Can you tell me as much as you can about the system otherwise? What OS, what version, which shell you're using, etc etc.

Are you able to try this? https://docs.atuin.sh/reference/daemon/

**Comment by ellie** [comment]
Oh you could also try setting `local_timeout = 60` in  ~/.config/atuin/config.toml`

Instead of timing out with an error, it will just wait - this was the behaviour in <v18

**Comment by mbhall88** [comment]
> You can run df -T to check, assuming that it's linux. Can you tell me as much as you can about the system otherwise? What OS, what version, which shell you're using, etc etc.

From that `df -T` command, the directory where the atuin files are stored is NFS.

OS is RHEL 9.3 (Plow). My shell is zsh.

> Oh you could also try setting local_timeout = 60 in ~/.config/atuin/config.toml

> Instead of timing out with an error, it will just wait - this was the behaviour in <v18

I did this and get the following

```
Error: error returned from database: (code: 5) database is locked

Caused by:
    (code: 5) database is locked

Location:
    crates/atuin/src/command/client.rs:126:18
Error: error returned from database: (code: 5) database is locked

Caused by:
    (code: 5) database is locked

Location:
    crates/atuin/src/command/client.rs:126:18
```

**Comment by xvello** [comment]
@sedlund please open a separate issue instead of piggy-backing on a similar one, as the root cause is different

@mbhall88 ouch! Atuin uses sqlite, that does not officially support NFS filesystems [due to the locking issue you are encountering](https://sqlite.org/faq.html#q5). Reworking Atuin to safely operate on NFS is probably not in @ellie's roadmap, as it's a pretty rare use case. You'll probably have to hack something on your end.

One direction I would investigate if I was in your shoes is to look for a non-NFS location I can write to (maybe a tmpfs such as `/run/user/$uid` or `/tmp`) and change the `db_path` accordingly. You'll still need to sync the DB file from NFS on login (command in .zshrc to rsync it if not present?) and back to NFS on logout (might be tricky depending on your setup).

**Comment by mbhall88** [comment]
Oh that is a shame. I do now see there is a note about this in the known issues on the docs. Thanks for bringing this to my attention @xvello.

The home directory on our computing server is where we are supposed to store all user software related files and that is NFS. So I've moved the history DB to a GPFS filesystem where we stored project-related files and it seems to be working again!! 🎉 

Though this is all very weird as I had been using atuin without issue for a good 6 months on the NFS filesystem. Anyway, glad there was a work around. Work has been so frustrating without atuin the last week. So glad to have it back.

**Comment by xvello** [comment]
@mbhall88 good news, although I found no information about how sqlite performs on GPFS. We cannot be sure that it won't break in the future, but you can cross that bridge when that happens.

@sedlund no need to open a separate issue for your case it is already acknowledged in the [known issues page](https://docs.atuin.sh/known-issues/), with a link to a tracking issue for it.

**Comment by mbhall88** [comment]
Urgh, issue has popped up again on GPFS too. I guess I'm going to have to say goodbye to atuin then? 😢 Can't really think of any other way around this... Would setting up a sync service make a difference?
