### ISSUE TITLE
[Bug]: completion files are missing from 18.3.0 GitHub release

### ISSUE THREAD

**Issue by agateau** [atuinsh/atuin#2137]
### What did you expect to happen?

I package Atuin for [Clyde](https://github.com/agateau/clyde). Release 18.3.0 failed to automatically update because the Clyde package expected to find shell completion files in Atuin release asset but they are no longer there.

### What happened?

The completion files (completions/_atuin, completions/atuin.bash, completions/atuin.fish) are not included in the 18.3.0 assets.

### Atuin doctor output

```yaml
Not relevant here I think.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
We changed the release process with v18.3, and no longer bundle extra assets

You can use the following to generate completions: https://docs.atuin.sh/reference/gen-completions/

For example, Homebrew does the following: https://github.com/Homebrew/homebrew-core/blob/8c1cad8e067d70947ab610265030aaa9a6cd4b37/Formula/a/atuin.rb#L24

**Comment by agateau** [comment]
Ah that's too bad. Clyde can't do that. At least not yet.
