### ISSUE TITLE
[Bug]: Debian upgrade to 18.3.0

### ISSUE THREAD

**Issue by mateuscomh** [atuinsh/atuin#2145]
### What did you expect to happen?

When i use ``` bash <(curl https://raw.githubusercontent.com/atuinsh/atuin/main/install.sh)```  on Debian 12, the update version to 18.3.0  not happend

### What happened?

I had to upload the file that was downloaded in /home/{USER}/.atuin/bin/atuin and manually replace it in /usr/bin/atuin to solve it.

_Its work for me, but im open this issue to help some one, im not sure about the change on code_

### Atuin doctor output

```yaml
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mateuscomh** [comment]
When i comparate Debian and MacOs atuin, i see another thing on `atuin status` the _history count_ and _deleted history count_ not show on Debian 12

```Atuin v18.3.0 - Build rev 9be49e434e549d6b13928b530139b66fef6171f1

[Local]
Sync frequency: 1h
Last sync: 2024-06-21 16:55:02.693622249 +00:00:00
[Remote]
Address: https://api.atuin.sh
Username: 3mhenrique
```

Here my `atuin doctor`
``` Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues

{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "2024-06-21 16:55:02.693622249 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "bash",
    "default": "bash",
    "plugins": [
      "atuin",
      "bash-preexec"
    ],
    "preexec": "bash-preexec"
  },
  "system": {
    "os": "Debian GNU/Linux",
    "arch": "x86_64",
    "version": "12",
    "disks": [
      {
        "name": "/dev/mapper/debian-barra",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/mapper/debian-boot",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/mapper/debian-home",
        "filesystem": "ext4"
      },
      {
        "name": "/dev/sda1",
        "filesystem": "fuseblk"
      },
      {
        "name": "/dev/sdb1",
        "filesystem": "fuseblk"
      }
    ]
  }
}
```

**Comment by ellie** [comment]
> i see another thing on atuin status the history count and deleted history count not show on Debian 12

This is due to the migration to sync v2. We no longer count things heavily while syncing, so no longer display that information
