### ISSUE TITLE
Move systemd_socket config to command line argument

### ISSUE THREAD

**Issue by heftig** [atuinsh/atuin#2152]
Whether the daemon takes sockets from systemd or opens its own should be controlled via a command line argument (e.g. `atuin daemon --systemd`). Atuin's own config file is the wrong place for this.

This way starting the daemon using systemd can just work without having to manually edit Atuin's config first.

**Comment by ellie** [comment]
You could use the env setting, like this

`ATUIN_DAEMON__SYSTEMD_SOCKET=true atuin daemon`

All config fields have an env equivalent, for this sort of reason
