### ISSUE TITLE
[feature request] auto execute `atuin sync --force` after `atuin login`

### ISSUE THREAD

**Issue by luochen1990** [atuinsh/atuin#2245]
It is weird to find out lacking data after login, perhaps auto execute `atuin sync -f` after `atuin login` success is a good idea.

And, I think `--force` always means some dangerous operation, but obviously sync data is not, maybe we can rename `--force` to `--all`

**Comment by ellie** [comment]
Force is no longer required with sync v2 and will be deprecated - it actually does nothing

Please ensure all machines have

```
[sync]
records = true
```

at the bottom of the config file, and you'll have a much better experience
