### ISSUE TITLE
Prost and tonic updates

### ISSUE THREAD

**Issue by LecrisUT** [atuinsh/atuin#2248]
Heads up about `prost 0.13` and `tonic 0.12` updates are introducing breaking changes.

Looking at the [tonic blame](https://github.com/hyperium/tonic/blame/master/examples/src/uds/client.rs#L26) and the affected code, it doesn't seem too difficult a transition:
https://github.com/atuinsh/atuin/blob/e45979c9af1c15f3ae4bdb69325eafef55dcfb02/crates/atuin-daemon/src/client.rs#L25-L29

I have tried to adapt the example code there, but I don't have enough rust knowledge to make `move` and `async` work together there.

**Comment by ellie** [comment]
Thanks for the heads up! Will get to it soon

**Comment by LecrisUT** [comment]
Thanks.

It looks like `prost-types` was not updated in sync with `prost`:
https://github.com/atuinsh/atuin/blob/8d9f677c4e9ccfcc6dc9297864dc49446fb5ee59/crates/atuin-daemon/Cargo.toml#L32-L33

**Comment by ellie** [comment]
Sorted!

While I appreciate the issue, in future it's not required - dependabot runs every monday and alerts us to updates

**Comment by LecrisUT** [comment]
Oh, ok. I thought dependabot has a maximum of 5 PRs. But yeah it would be sorted eventually.

**Comment by ellie** [comment]
Either way, we'll be notified within a week or two of the release. Unless the update fixes a CVE or has a major performance/bug fix that affects us, I'd rather avoid the noise.

Otherwise we'll have people opening issues when any dependency is updated, which feels a little superfluous to me
