### ISSUE TITLE
[Bug]: history not synced between two Macs 🤔

### ISSUE THREAD

**Issue by davinkevin** [atuinsh/atuin#2254]
### What did you expect to happen?

I maybe missed something, but I expect my `fish` history to be synced between both Macs I have. 

The recent history is different. I can't say for old entries. 

### What happened?

I currently use 2 Macs side by side, and I would like to access history of one from another using `atuin`. 

In my case, I use my own `atuin` backend, self hosted in my local network with a [pretty simple configuration](https://gitlab.com/davinkevin.fr/home-server/-/blob/main/atuin/base/atuin.yaml?ref_type=heads)

<img width="1119" alt="image" src="https://github.com/atuinsh/atuin/assets/1970922/85b18c50-5416-4cf1-98cb-a77b0e60fb02">

In both computers, I have a totally different history, even after two `atuin sync`. 
An interesting point is the list of entries is different on both (`79587` vs `80382`).

I've even forced the sync with `sync_frequency = 0` on both laptops, without success. 

On the backend side, and especially database, I have this: 

```
$ select count(*) from users;
> 1
$ select count(*) from history;
> 80581
```

Did I miss something? 

### Atuin doctor output

MacBook 1 (at the top in the previous picture):

```
Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues


{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-07-10 19:29:49.874649 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "arm64",
    "version": "14.5",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

Mac 2 (the one at the bottom):

```
Atuin Doctor
Checking for diagnostics


Please include the output below with any bug reports or issues


{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": false,
      "records": false,
      "auto_sync": true,
      "last_sync": "2024-07-10 19:29:57.467699 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "fish",
    "default": "fish",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "Darwin",
    "arch": "x86_64",
    "version": "14.5",
    "disks": [
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      },
      {
        "name": "Macintosh HD",
        "filesystem": "apfs"
      }
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
Hey!

Could you enable record sync please, on both machines, and let me know if that solves it for you? Add this to your config file

```
[sync]
records = true
```

**Comment by davinkevin** [comment]
Way better! 

<img width="1107" alt="image" src="https://github.com/atuinsh/atuin/assets/1970922/aa6a3f99-1eb5-4d77-b4d5-35479e9cf194">

I had to sync twice the second one… but now it looks correct. 

I close it and I'll reopen if anything new happens.
