### ISSUE TITLE
[Bug]: Deleting account with username or email and password

### ISSUE THREAD

**Issue by Marin-Kitagawa** [atuinsh/atuin#2293]
### What did you expect to happen?

I want to delete an account with either username or email and password. I lost the key. So, I want to delete the old account and create a new account with the same username

### What happened?

I am unable to find an option to do the above.

### Atuin doctor output

```yaml
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
> I lost the key

You can login with your username and password, and then run

```
atuin account delete
```

You can leave the key field blank. It will fail to sync, but you can login OK and delete the account
