### ISSUE TITLE
[Feature Request]: Allow to save locally command history having secrets but have an ooption to prevent from sending it over the server

### ISSUE THREAD

**Issue by benjaminch** [atuinsh/atuin#2342]
Hello Team !

### Context
As of today, Atuin doesn't store commands having explicit sercrets such as AWS credentials for example.
There is an option `secrets_filter` allowing to by pass this behavior allowing it to store commands with secrets.
There are already filters to allow / block some secrets from being tracked or not. This feature would be to add a bit more flexibility allowing secrets to be tracked locally eventually and not necessarily sent to the server.
While it's ok to have secrets locally, sometimes I prefer not to expose those even if it's secure to the backend, just in case.

An idea of option can be:
```
secrets_filter_remote: []
secrets_filter_local: []
```
**Couple examples:**
1. if you want to allow to track any secrets locally but none remotely, you will have the following:
```
secrets_filter_remote: []
secrets_filter_local: ['*']
```
2. if you want to allow to track AWS secrets locally but none remotely, you will have the following:
```
secrets_filter_remote: []
secrets_filter_local: ['AWS_*']
```
3. if you want to allow to track AWS secrets remotely you will have the following:
```
secrets_filter_remote: ['AWS_*']
secrets_filter_local: [] 
```

As you can see on example 3, `secrets_filter_local` will inherit options set in `secrets_filter_remote` because IMO it doesn't make sense to allow to track something remotely but not locally (but maybe there is a use case?).

### Current behavior
With `secrets_filter=false`
```
$ AWS_ACCESS_KEY_ID=xxxxx aws cmd 
```
=> command will be tracked and sent to the backend.

With `secrets_filter=true`
```
$ AWS_ACCESS_KEY_ID=xxxxx aws cmd 
```
=> command won't be tracked and sent to the backend neither locally, this won't be in the history.

### Future expected behavior
With 
```
secrets_filter_remote: []
secrets_filter_local: ['AWS_*']
```
```
$ AWS_ACCESS_KEY_ID=xxxxx aws cmd 
```
=> command will be tracked locally and not sent to the backend.

With
```
secrets_filter_remote: ['AWS_*']
secrets_filter_local: []
```
```
$ AWS_ACCESS_KEY_ID=xxxxx aws cmd 
```
=> command will be tracked both remotely and locally.

Happy to add more information and help you think / implement it if it makes sense to some of you.

Cheers !

**Comment by ellie** [comment]
Hey! Thanks for the suggestion.

I see how this could be useful, but this sort of feature would lead to significantly more complex syncing logic + would still lead to production secrets being stored in shell history. I'd rather not compromise there.

I could potentially see the value in being able to store secrets separately. Ie, the shell history references a value stored elsewhere, and we can apply different logic on top of that. But that's pretty out of scope for the time being

**Comment by huyz** [comment]
@ellie would it make sense to automatically mask secrets, e.g. `*****` (as is often done with logging) anything that matches standard and user-configurable regex patterns? That way, we don't have to rely on sync vs not-sync logic/config nor have to delete history entries (which can be considered too late anyway)
