### ISSUE TITLE
[Bug]: build fails with `atuin` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.

### ISSUE THREAD

**Issue by ajkessel** [atuinsh/atuin#2373]
### What did you expect to happen?

I'm trying to run atuin on an i686 system. 

`curl --proto '=https' --tlsv1.2 -LsSf https://github.com/atuinsh/atuin/releases/download/v18.3.0/atuin-installer.sh | sh`
returns:
```
ERROR: there isn't a package for i686-unknown-linux-gnu
```

`git clone` followed by `cargo build` returns:
```
error: failed to select a version for `env_logger`.
    ... required by package `atuin v18.4.0-beta.3 (/backups/home/adam/src/atuin/crates/atuin)`
versions that meet the requirements `^0.11.5` (locked to 0.11.5) are: 0.11.5

the package `atuin` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.


failed to select a version for `env_logger` which could resolve this conflict
```
Is there some way to get this working on my VM?

### What happened?

Failed to build

### Atuin doctor output

```yaml
Can't build
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ajkessel** [comment]
Upgrading from Debian stable (1.63.0+dfsg1-2) rust/cargo to rustc 1.81.0-beta.6 seems to solve this problem. If it's not useful to anyone, feel free to close.

**Comment by KishorSarswatSam** [comment]
Thanks, it was useful.

**Comment by ellie** [comment]
This is expected - many of our dependencies rely on a version of Rust much newer than 1.63, which was released 2 years ago now

Please follow one of the install steps from the documentation

https://docs.atuin.sh/guide/installation/#manual-installation

Copying our section on building from source:

> Atuin builds on the latest stable version of Rust, and we make no promises regarding older versions. We recommend using [rustup](https://rustup.rs/).

```
git clone https://github.com/atuinsh/atuin.git
cd atuin/crates/atuin
cargo install --path .
```
