### ISSUE TITLE
Feature-request: LDAP user-authentication

### ISSUE THREAD

**Issue by cosgroveb** [atuinsh/atuin#2387]
LDAP user-authentication would be a nicer fit for my environment/self-hosted atuin instance rather than password auth. Would this be a reasonable feature for atuin?

**Comment by ellie** [comment]
I appreciate why this would be useful, but it's definitely out of scope :)

I'd be open to considering it if an org wished to sponsor it, however the maintenance + work required is too much

**Comment by cosgroveb** [comment]
Oh, it's possible we misunderstood each other here. I definitely understand not wanting to do the work for this niche feature. 

I wanted to take a stab at it myself and am willing to do it if I had a "patches welcome" reply :)

I can see that even with the implementation done maintenance would be an annoying cost. So, feel free to reopen the issue if you're open to a patch and do leave it closed if you feel the future maintenance to be icky.

**Comment by shymega** [comment]
I'm hoping to suggest Atuin as an infrastructure request to my employer, as a lot of us use Atuin internally. However, I imagine the infra team would want LDAP auth, or a IMAP backend.

I'm not privy if my employer would want to sponsor Atuin, but if we could do a quick call to discuss how authentication currently works, I could maintain this in my free time as a 'thank you' for such a great tool. That would be a personal project on my own time to be clear on that.

My thinking was to make Atuin's user authentication somewhat 'pluggable', if not already, and to pass a bind DN and LDAP search DN into that.
