### ISSUE TITLE
[Bug]: history -c affected atuin

### ISSUE THREAD

**Issue by dougg0k** [atuinsh/atuin#2399]
### What did you expect to happen?

Clear bash only and not affect atuin.

### What happened?

By typing `history -c`, everything was wiped, including anything from atuin.

### Atuin doctor output

```yaml
No need.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
I'm afraid I cannot reproduce this. There is also absolutely 0 reason that it would be the case, as history -c does nothing with Atuin.

Without your atuin doctor output, there's nothing else I can do

**Comment by dougg0k** [comment]
Exactly, that's why I did it. Then it was gone from atuin as well.

```
{
  "atuin": {
    "version": "18.3.0",
    "sync": {
      "cloud": true,
      "records": true,
      "auto_sync": true,
      "last_sync": "1970-01-01 0:00:00.0 +00:00:00"
    },
    "sqlite_version": "3.44.0"
  },
  "shell": {
    "name": "nu",
    "default": "nu",
    "plugins": [
      "atuin"
    ],
    "preexec": "built-in"
  },
  "system": {
    "os": "CachyOS Linux",
    "arch": "x86_64",
    "version": "rolling",
    "disks": [
     ...many disks
    ]
  }
}
```
