### ISSUE TITLE
Feature request: syncing other kinds of history

### ISSUE THREAD

**Issue by cosgroveb** [atuinsh/atuin#2447]
This would be a big change and I'm super not sure if it would fit because in most cases, the TUI wouldn't be relevant but it would be neat if atuin sync could sync more than just shell history, but maybe any kind of history backed by a text file e.g.:

1. psql_history (this is my biggest one)
2. REPL history (e.g. irb_history)

Not sure _how_ it should work but hoping to spark a discussion about that. Discussed briefly with @calebhearth here https://lobste.rs/s/jznaq7/search_sync_your_shell_history_with_atuin#c_b1l3ry

**Comment by calebhearth** [comment]
https://github.com/atuinsh/atuin/issues/608 is the issue I alluded to having seen before, though I remember it being more explicit about wanting to store history for non-shell programs. Maybe I imagined that or read more into what @conradludgate [said about readline](https://github.com/atuinsh/atuin/issues/608#issuecomment-1440463562).

https://github.com/atuinsh/atuin/issues/2179 is semi-related in my mind.

**Comment by cosgroveb** [comment]
Ah thank you for reminding me of #608. I am inclined to close this as a duplicate of that because the implementation details proposed on that thread could accomplish what I'm picturing, I think.
