### ISSUE TITLE
[Feature Request] Use SemVer In Container Image Tags

### ISSUE THREAD

**Issue by rfpludwick** [atuinsh/atuin#2461]
### What did you expect to happen?

I'm setting up Renovate and want to have it automatically uptake the latest version of the Atuin server container image.

### What happened?

It cannot determine newer versions of the Atuin server container image because hashes are used.

### Atuin doctor output

```yaml
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ellie** [comment]
We don't follow semver to the letter, but do tag images with major/minor/patch. We also push an image for every single tag.

You'll see the latest available at docker pull ghcr.io/atuinsh/atuin:18.3.0, and also at docker pull ghcr.io/atuinsh/atuin:v18.3.0
