### ISSUE TITLE
[Feature Request] Edit a history entry

### ISSUE THREAD

**Issue by ad-on-is** [atuinsh/atuin#2468]
It would be nice, if a history entry could be edited.

# Usecase

`sudo mkfs.vfat -F 32 -s 8 /dev/sdf1`

Now, while I want to preserve that command in the history, I also want to prevent stupid-me to execute it accidentally in the future. Hence, I'd like to rename it to `echo "sudo mkfs.vfat -F 32 -s 8 /dev/sdf1"`

**Comment by ellie** [comment]
History hasn't really been designed to be editable, BUT you can always run the correct command and delete the old one

If you really would prefer to be able to edit then perhaps we could add another sync operation to allow editing :)

**Comment by ad-on-is** [comment]
Actually, I can live with the workaround by running a second command and deleting the previous one
