### ISSUE TITLE
atuin ignores nobind after widget usage

### ISSUE THREAD

**Issue by deathtrip** [atuinsh/atuin#276]
I have set:
ATUIN_NOBIND=true
bindkey '^r' `_atuin_search_widget

And initially the up arrow key is not bound, but after i use the widget it gets rebound.
I use zsh 5.8.1 and atuin 0.8.0 on arch linux.

**Comment by ellie** [comment]
I think this should be resolved now, and is a pretty old issue. If anyone runs into it again, please open another issue
