### ISSUE TITLE
Fresh MacOS 12.3.1 w/ bash install failed to find ATUIN_SESSION

### ISSUE THREAD

**Issue by numbers1thru9** [atuinsh/atuin#349]
I have bash set as my default terminal shell with a fresh script install. First issue was the auto import did not auto detect bash but did import when bash was specified (see Issue #168). The other issue is that after import I am not able to search at all and I get the following error:

`thread 'main' panicked at 'failed to find ATUIN_SESSION - check your shell setup: NotPresent', atuin-client/src/database.rs:30:35`

**Comment by conradludgate** [comment]
So the auto import should be fairly simple to update (see https://github.com/ellie/atuin/blob/main/src/command/client/import.rs#L47-L56)

Although I recall there being a reason we didn't add it. Do you remember @ellie? Was it because not all bash setups use BASH_HISTORY?
Either way, 2 outcomes:

1. Document the list of auto imports and why some are not yet auto
2. Add bash to the auto setup

**Comment by conradludgate** [comment]
> The other issue is that after import I am not able to search at all and I get the following error

Can you confirm that you've followed the necessary bash setup: https://github.com/ellie/atuin#bash

Importantly, that `atuin init bash` is being executed. You might need to `source` your bashrc file for it to take effect

**Comment by numbers1thru9** [comment]
@conradludgate yes I ran those commands after import just to be sure the script install didnt error with them or something by chance. I know I had restarted my terminal as well and thought I had sourced .bashrc but apparently looking at my history (ironic I know 🤣 ) I managed to source .bash_profile. Seems it was a case of brain not matching fingers. My apologies.

**Comment by ellie** [comment]
> Although I recall there being a reason we didn't add it. Do you remember @ellie? Was it because not all bash setups use BASH_HISTORY?

I don't remember exactly, though iirc we used to have some checks to see if it was in use + configured

**Comment by wallagib** [comment]
Had this error too, fixed it with the init script for zsh.
