### ISSUE TITLE
Add option to include commands that start with `#` in history

### ISSUE THREAD

**Issue by norpol** [atuinsh/atuin#467]
A common use-case for me is to

* write a command
* go to the beginning of the line
* add a `#`
* then doing some other command first to retrieve some data
* go into the shell history, select the commented out command, paste the extracted data, remove the `#`

Very basic example to illustrated what I'm doing also recorded on [asciinema](https://asciinema.org/a/jJ2ANfkVVqSegQIBMv5WUxsZc)

This appears not to be compatible with atuin right now, as adding a `#` is the equivalent of adding a ` ` at the beginning of the line.

**Comment by conradludgate** [comment]
`#` prefix seems to work for me 🤔.

<img width="202" alt="Screenshot 2022-06-29 at 14 02 49" src="https://user-images.githubusercontent.com/6625462/176442816-9da548b5-95f3-4126-8eee-41db7c84b249.png">

**Comment by norpol** [comment]
Really weird, if I'm just using the standard zsh history search it shows up but not in `atuin search -i`

![image](https://user-images.githubusercontent.com/2230917/176444870-a769dce0-f36e-497a-b697-bf80db41eea9.png)
![image](https://user-images.githubusercontent.com/2230917/176444953-8d7fdab7-dcb0-47ad-8ece-50f0e74e2d9b.png)

**Comment by norpol** [comment]
No it still doesn't show up

**Comment by millette** [comment]
Using bash and #ed commands aren't showing up for me either. I use them for temporary commands I'll be rewriting.

In bash (I don't know about other shells), we can skip history by preceding a command with a space (if it contains a password for example).

Sort of related: #70 and #350.

**Comment by ellie** [comment]
I can't replicate this, no matter what I try. It seems like other people can't replicate it either. We also don't have anything specific that would ignore a `#` prefix.

I'm going to close this for now, but happy to reopen should it occur + have a replication case we can work with!

**Comment by norpol** [comment]
@ellie Do you have `setopt interactivecomments` activated? Otherwise `#` is not detect as a comment by zsh. I just started with an empty `.zshrc` entered `setopt interactivecomments` and the issue is still there. Previous zsh-histdb would still store this in the history, same as zsh's built in history.
