### ISSUE TITLE
performance issues on initial command listing in interactive mode

### ISSUE THREAD

**Issue by Byron** [atuinsh/atuin#475]
Atuin is a fantastic tool and it changed my workflow to the better! Thanks for that :)!
Now that I use it all the time it's easy to notice even relatively minor issues, so here I go. Note that further down there is also a workaround for the issue mentioned here, even though I am unable to provide a proper solution at this time.

### How to reproduce

- tested on f946644cebb94bb62646cce6fcf3900fe71e2bea, on MacOS with history of 24k items
- the initial load of `atuin` takes about 100ms
- when typing, then erasing to clear the search, the listing is slow with about 100ms duration, but in bad cases it can take up to 800ms, which makes the experience sluggish and frustrating given how often I use it

#### Profile 

Profiling it showed the database is slow, here is a particularly slow case with ~830ms listing time, with drawing taking no considerable time: 

<img width="1025" alt="Screen Shot 2022-07-08 at 09 38 55" src="https://user-images.githubusercontent.com/63622/177900425-32c8c73e-803b-4693-b55a-e2874cf4dfc5.png">

<img width="584" alt="Screen Shot 2022-07-08 at 09 39 05" src="https://user-images.githubusercontent.com/63622/177900455-7c4797c4-f72a-4dba-b511-cbadb6e25b3f.png">

#### Workaround

Out of a whim I applied this patch as `unique` constraints can be slow due to their potential for exponential runoffs. With it `atuin` became as snappy as never before for the workflow described in _How to reproduce_.

```patch
diff --git a/src/command/client/search.rs b/src/command/client/search.rs
index c50c492c..8ad1ea93 100644
--- a/src/command/client/search.rs
+++ b/src/command/client/search.rs
@@ -262,7 +262,7 @@ async fn query_results(
 ) -> Result<()> {
     let results = match app.input.as_str() {
         "" => {
-            db.list(app.filter_mode, &app.context, Some(200), true)
+            db.list(app.filter_mode, &app.context, Some(200), false)
                 .await?
         }
         i => {
```

#### Possible next steps

Unfortunately I don't have the experience to find a way to make `unique` fast even on relatively large databases, but hoped a more suitable index could do the trick, or a different way of writing the SQL statement.

For those interested, here is [the unique constraint](https://github.com/ellie/atuin/blob/1d030b9d32f539fd38f5ff3335234c5111c3303f/atuin-client/src/database.rs#L231-L236) and here is the [database's index configuration](https://github.com/ellie/atuin/blob/4f16e8411e24891b140690798c47747f5c9bb91e/atuin-client/migrations/20210422143411_create_history.sql#L15-L16).

**Comment by conradludgate** [comment]
Thanks for the really great detail!

If it makes a huge difference, we could either have a custom index for unique commands, or we can have some custom data structure that performs the unique checks on the fly for the interactive list rendering

**Comment by Byron** [comment]
Just now I thought that maybe there could also be an option to turn unique commands off with a configuration flag of sorts, as I personally don't need the initial listing most of the time, except for it to be fast.

If there is no way of reliably speed it up even with 50k entries, maybe the above is a good starting point for more options on how to deal with it. Maybe it would be enough to only deduplicate the most recent N commands anyway.

**Comment by chrysn** [comment]
Noticing the startup delay myself (on a 1M commands thereof 250k unique history imported from zsh, ^R takes several seconds to show), it might also be practical to decouple the GUI setup from database loading.

The effect of slow startup might be less noticable if (maybe in the course of #471) keystrokes that are already entered were reliably preserved. Then starting to type `^Rexport PYTHONP<Return>` might still take some time to display, but it would do the right thing.

**Comment by Byron** [comment]
> Noticing the startup delay myself (on a 1M commands thereof 250k unique history imported from zsh, ^R takes several seconds to show), it might also be practical to decouple the GUI setup from database loading.

From my measurements, it seemed like the GUI always costs only a couple of milliseconds, and it looked like it displays only 200 lines at a time on first load, too.

> The effect of slow startup might be less noticable if (maybe in the course of https://github.com/ellie/atuin/issues/471) keystrokes that are already entered were reliably preserved.

I love that idea, this could help tremendously especially if at some point greater performance gains aren't possible anymore at some point.

**Comment by ellie** [comment]
Closing this one for now. It was originally opened when we used a totally different set of queries, and did not have the indices we do now. Happy to revisit if we re-profile or replicate with a more recent build!
