### ISSUE TITLE
press C-j accept-line

### ISSUE THREAD

**Issue by gitduk** [atuinsh/atuin#587]
accept command history line when press '^j'

`bindkey | grep '\^J'`

output: 
``` output
"^J" history-search-forward
```

shell: zsh

**Comment by patricksjackson** [comment]
Can you clarify what you are asking about/for? Atuin doesn't modify the C-j shortcut in zsh, see: https://github.com/ellie/atuin/blob/f93da455a354f019213315d93bd204a87245b928/src/shell/atuin.zsh#L54-L58

**Comment by ellie** [comment]
I'm not really sure what's being requested or what is broken here! Happy to reopen should anything be clarified
