### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by tfkhdyt** [atuinsh/atuin#755]
I always failed to register. I didn't change any config

![Screenshot_20230303_094954](https://user-images.githubusercontent.com/47195537/222619297-030bd32b-90eb-43ee-bcfe-fec0b2a2116f.png)

**Comment by ellie** [comment]
Hey! I think registrations were broken briefly after a deploy around then. It should be sorted now if you retry?

**Comment by tfkhdyt** [comment]
It's still not working

![Screenshot_20230321_060710](https://user-images.githubusercontent.com/47195537/226484839-d3d13ded-b7c1-4e94-8832-7412c9ac01d0.png)

**Comment by Write** [comment]
Not working here, either on macOS with brew, or on Debian 11. 
Same error, same line on both OS

Debian's output

```bash
Error: failed to register user: failed to add user

Location:
    /home/runner/work/atuin/atuin/atuin-client/src/api_client.rs:63:9
```

macOS
```bash
Error: failed to register user: failed to add user

Location:
    /private/tmp/atuin-20230228-5854-ice2iz/atuin-13.0.1/atuin-client/src/api_client.rs:63:9
```

_@tfkhdyt btw, this is largerly out of scope of this thread but what do you use to show your git branch ? Thanks._

**Comment by tfkhdyt** [comment]
> _@tfkhdyt btw, this is largerly out of scope of this thread but what do you use to show your git branch ? Thanks._

It's [starship](https://starship.rs/) prompt.

**Comment by ellie** [comment]
> EDIT : After digging a little it just seems that it's blocking custom domain ? Using an icloud address make it work, using a custom domain throw this error. Hm..

We actually don't even verify that it's an email 😅 

@tfkhdyt I just checked the email in your screenshot, and you already have an account - can you try logging in?

**Comment by tfkhdyt** [comment]
> @tfkhdyt I just checked the email in your screenshot, and you already have an account - can you try logging in?

Unfortunately, still not working
![image](https://user-images.githubusercontent.com/47195537/232378474-77ba1553-0ed7-4ca8-85e6-d732fb53a273.png)

**Comment by soderluk** [comment]
I had this exact same issue when I setup atuin on my self-hosted server. It was driving me nuts when I couldn't register. After a while I found out that the `sync_address` URL in the client config file had a forward slash at the end. 
Try removing the slash, save, and try to register again. If your config says `sync_address = "https://atuin.domain.com/"` try `https://atuin.domain.com` instead.

**Comment by loongtex** [comment]
I always failed to register. I didn't change any config：

Error: failed to register user: failed to add user

<img width="737" alt="image" src="https://github.com/atuinsh/atuin/assets/30718342/cb2419a0-4d12-4e05-a260-7c33c97a0829">

**Comment by bhavika** [comment]
I'm facing the same issue: 

```
Error: failed to register user: failed to add user

Location:
    /private/tmp/atuin-20240226-5245-z9ks0z/atuin-18.0.2/atuin-client/src/api_client.rs:71:9
```

<img width="697" alt="Screenshot 2024-02-27 at 10 31 46 AM" src="https://github.com/atuinsh/atuin/assets/4955119/de228b17-5535-4aa8-9f54-1f33be27caa4">

**Comment by ellie** [comment]
@bhavika could you open a new issue detailing your setup please?

1. Are you self hosted or using the main server?
2. Have you changed any config? 
3. What OS?
4. What shell?

I'm going to close this one because it's difficult to follow without the setup of each person involved.

**Comment by ellie** [comment]
@bhavika I just checked, and you already have an account - signed up last month. The error message should probably be improved for an already-existing email.

**Comment by bhavika** [comment]
> @bhavika I just checked, and you already have an account - signed up last month. The error message should probably be improved for an already-existing email.

Thanks for the quick follow-up @ellie! It does not seem like I can reset my password if I've forgotten it. I'll create a new account instead.

**Comment by bhavika** [comment]
> @bhavika could you open a new issue detailing your setup please?

> 1. Are you self hosted or using the main server?
I was using the main server. 
> 2. Have you changed any config?
Nope. 
> 3. What OS?
MacOS Sonoma 14.3.1 
> 4. What shell?
Zsh 

> I'm going to close this one because it's difficult to follow without the setup of each person involved.

Fair!

**Comment by ellie** [comment]
> Thanks for the quick follow-up @ellie! **It does not seem like I can reset my password if I've forgotten it. I'll create a new account instead.**

Not presently - we don't verify emails yet, which would be required for reset requests
