### ISSUE TITLE
Using Ctrl-r breaking other up and down arrow key bindings

### ISSUE THREAD

**Issue by aravindhp** [atuinsh/atuin#787]
I initialize atuin using `eval "$(atuin init bash --disable-up-arrow)"` in my `.bashrc`. Whenever I use the `Ctrl-r` shortcut to bring up the UI and quit, the other up and down arrow keybindings defined in `/etc/intputrc` stop working, namely:
```
## arrow up
"\e[A":history-search-backward
## arrow down
"\e[B":history-search-forward
```
Expected behavior is for these keybindings to continue working.

**Operating system:** Fedora 37

**Comment by ellie** [comment]
I think this would have been resoled by #1170, as that is the cause of this kind of complaint - sometimes Atuin would change the input mode and not set it back correctly. We no longer need to change the input mode at all, so this should no longer be an issue

**Comment by aravindhp** [comment]
I confirm that I no longer see the issue with v17.0.0. Thank you!
