### ISSUE TITLE
Install script does not support Arch Linux

### ISSUE THREAD

**Issue by J4NS-R** [atuinsh/atuin#796]
When running the default server install script, it incorrectly detects my system as ubuntu, and promptly fails on the first `apt` command.

Contents of my `/etc/os-release`:

```plaintext
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
VERSION_ID=TEMPLATE_VERSION_ID
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

**Comment by conradludgate** [comment]
Weird! We use os-release and grep for the ID line, which we have a case for `arch`.

In this csse you can use pacman directly to install atuin

**Comment by ellie** [comment]
This should be resolved, happy to reopen should it occur again
