### ISSUE TITLE
Improve error message when server/clients versions mismatch

### ISSUE THREAD

**Issue by pdecat** [atuinsh/atuin#834]
Hi @ellie & @conradludgate!

When self hosted atuin server is running v13.0.1, and one client is a a custom build from current main branch, sync is broken for all clients.

The custom client gets:
```
# atuin sync
Error: failed to get status (are you logged in?)

Location:
    /home/patrick/workspaces/rust/atuin/atuin-client/src/api_client.rs:149:13
```

And the other v13.0.1 clients get:
```
# atuin sync
thread 'main' panicked at 'failed to decrypt history! check your key: array had incorrect length, expected 8

Location:
    atuin-client/src/encryption.rs:101:19', /home/runner/work/atuin/atuin/atuin-client/src/api_client.rs:167:45
```

Upgrading server and all clients to the custom build from main resolves the issue.

As it took me quite some time to understand what was going on, I believe the error message could be improved.

I guess it has to do with recent deletion changes.
Maybe introducing client / server versions checks, or versioning the protocol could help.

**Comment by ellie** [comment]
This is sorted as of v17 - clients will error if servers are running an older major version
