### ISSUE TITLE
Deleted commands still show up in stats

### ISSUE THREAD

**Issue by majutsushi** [atuinsh/atuin#838]
This is pretty minor, but I thought it was worth mentioning. After upgrading to v14 I deleted all instances of a common command at my old job, but it still shows up as an empty string in the `atuin stats` output:

```
$ atuin stats
[▮▮▮▮▮▮▮▮▮▮] 46963 l
[▮▮▮▮▮▮    ] 31191 cd
[▮▮▮▮      ] 22310 vi
[▮▮▮▮      ] 19522 
[▮▮        ] 13372 tig
[▮▮        ] 12391 a
[▮▮        ] 10105 git d
[▮▮        ]  9681 rm
[▮         ]  9383 git st
[▮         ]  8056 less
Total commands:   377043
Unique commands:  101144
```

Since I currently don't have any syncing set up I manually fixed this by just deleting all the relevant rows directly in the DB, but it would probably be better if deleted commands were skipped in the stats.
I haven't looked at how stats are implemented, but I could imagine that if you delete several unrelated commands they could end up together in the stats since they might look like the same command.

**Comment by brudnak** [comment]
+1 seeing this empty stat too. Seeing on atuin 15.0.0, also saw on 14. 

![2023-08-03_11-14-15](https://github.com/atuinsh/atuin/assets/40877149/be6bc87a-5aab-4e86-9a5d-3a7bac9bca9e)

**Comment by ellie** [comment]
#913 was released in Atuin v16 which should resolve this
