### ISSUE TITLE
Feature request: Make exit-on-down-arrow behavior optional

### ISSUE THREAD

**Issue by ajhall** [atuinsh/atuin#922]
If I scroll to the bottom of the results list and press down, Atuin closes (as implemented in #659). This would make perfect sense if I was using the up-arrow binding to seed the search with what I already typed at the prompt, but I disabled Atuin's up-arrow binding in favor of the one built into my shell.

In my case, I've pressed CTRL+R and typed a search, then scrolled up and down in the list and accidentally exited Atuin and lost my search.

Could this behavior be made optional, or maybe not trigger based on what method was used to activate Atuin?

**Comment by jnovinger** [comment]
Seeing this as well, it's frustrating having to continually close/re-open shells to work around it.

OS: 

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
```

Terminal:

```
$ gnome-terminal --version
# GNOME Terminal 3.38.1 using VTE 0.62.3 +BIDI +GNUTLS +ICU +SYSTEMD
```

Bash:

```
$ bash --version
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Config: using stock configuration
