### ISSUE TITLE
Nushell init does not support undefined `config.hooks.pre_execution` and `config.hooks.pre_prompt`

### ISSUE THREAD

**Issue by acidghost** [atuinsh/atuin#928]
If the array for any of the hooks in the title is not defined (does not have to be), the script produced by `atuin init nu` does not work.

I think this is the same as #841 (I get the same error).

A solution is to first assign empty arrays for those hooks and then adding elements to them:
```
let-env config = (
    $env.config | upsert hooks (
        $env.config.hooks
        | upsert pre_execution ($env.config.hooks | get -i pre_execution | default [] | append $_atuin_pre_execution)
        | upsert pre_prompt ($env.config.hooks | get -i pre_prompt | default [] | append $_atuin_pre_prompt)
    )
)
```

**Comment by tlvenn** [comment]
I am encountering a very similar issue with `$env.config.hooks` being undefined on a new system so in a similar fashion, we should do the following:

```
let-env config = (
    $env.config | upsert hooks (
        $env.config | get -i hooks | default {}
        | upsert pre_execution ($env.config.hooks | get -i pre_execution | default [] | append $_atuin_pre_execution)
        | upsert pre_prompt ($env.config.hooks | get -i pre_prompt | default [] | append $_atuin_pre_prompt)
    )
)
```

**Comment by tlvenn** [comment]
@acidghost can you update your PR ?

**Comment by tlvenn** [comment]
Actually given you are reading again $env.config.hooks in those 2 upsert commands we probably should define `$env.config.hooks` with an empty record so that those 2 commands can work...

**Comment by acidghost** [comment]
> Actually given you are reading again $env.config.hooks in those 2 upsert commands we probably should define `$env.config.hooks` with an empty record so that those 2 commands can work...

I'm not sure I understand this last comment. I updated the PR with your initial suggestion.

**Comment by tlvenn** [comment]
I meant to say that both lines that are doing upsert try to lookup the `$env.config.hooks` as well and given it could be not defined even if we fixed the initial lookup, it will fail there next.

We should probably set `$env.config.hooks` to an empty record but I am not sure how within the flow of that snippet but the following should be working:
```
let-env config = (
    $env.config | upsert hooks (
        $env.config | get -i hooks | default {}
        | upsert pre_execution ($env.config | get -i hooks | default {} | get -i pre_execution | default [] | append $_atuin_pre_execution)
        | upsert pre_prompt ($env.config | get -i hooks | default {} | get -i pre_prompt | default [] | append $_atuin_pre_prompt)
    )
)
```

**Comment by acidghost** [comment]
I think your previous snippet is the correct one.

Are you able to test the PR?

**Comment by acidghost** [comment]
You're right, actually. I'm working on a fix.

**Comment by acidghost** [comment]
@tlvenn it should be fixed now.

**Comment by LeoniePhiline** [comment]
@tlvenn Could you review #1138? (It's @acidghost's solution, but rebased. Just need to make sure my rebase is sound.)
