### ISSUE TITLE
Configurable Key bindings in UI

### ISSUE THREAD

**Issue by gengel** [atuinsh/atuin#935]
👋 Hi! Love Atuin, and I've been using it for months.

One minor key issue drives me nuts, though -- as both an Emacs user and macos user, I am very, very accustomed to Ctrl-K deleting the line after the point where the cursor is. Atuin's closest analog, the clear line command, is bound to Ctrl-U. 

I would love for UI keybindings to be configurable so that I could swap Ctrl-K and Ctrl-U (or something else.) AFAICT, there's no way of doing this currently. I think this would be great!

**Comment by conradludgate** [comment]
I need to finish off the UI refactor in #775, but after that configuration should be pretty easy to add (and something we had already planned)

**Comment by ellie** [comment]
Closed in favour of #193
