### ISSUE TITLE
clobbering inputrc after search UI

### ISSUE THREAD

**Issue by fowles** [atuinsh/atuin#987]
In a fresh terminal on my machine

```
[sonmi]~$ cat ~/.inputrc
# ipython like up and down keys
"\e[A": history-search-backward
"\e[B": history-search-forward

# word based navigation for ctrl+arrow
"\e[1;5C": forward-word
"\e[1;5D": backward-word
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word
[sonmi]~$ echo hi there
hi there
[sonmi]~$ cat <up arrow>
[sonmi]~$ cat ~/.inputrc
```

note in the last step the way that up arrow completed to  `cat ~/.inputrc`.  Now I can continue my session

1.  `<ctrl-r>` (successfully brings up atuin graphical search pretty)
2.  `<esc>` (successfully drops me back to a terminal)

```
[sonmi]~$ echo oh no
oh no
[sonmi]~$ cat <up arrow>
[sonmi]~$ echo oh no
```

I would like the last step above to complete to `cat ~/.inputrc` not `echo oh no`.

I am running atuin with the following startup sequence:

```
[sonmi]~$ tail -1 ~/.bashrc
eval "$(atuin init bash --disable-up-arrow)
```

**Comment by fowles** [comment]
This appears related to the `tpuc rmkx/smkx` in `__atuin_history`, as I can reproduce the failure directly be running `tput smkx` and I can restore the correct behavior by running `tput rmkx` explicitly

**Comment by fowles** [comment]
Thanks for fixing this!!

**Comment by joeds13** [comment]
I’m still seeing this issue after updating to 17.0.0 this morning using `bash`?

```shell
joe in ENG-Mac-569 in ~
❯ atuin --version
atuin 17.0.0
joe in ENG-Mac-569 in ~
❯ bash --version
GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Any help is appreciated and happy to test anything!

**Comment by joeds13** [comment]
> I’m still seeing this issue after updating to 17.0.0 this morning using `bash`?
> 
> ```shell
> joe in ENG-Mac-569 in ~
> ❯ atuin --version
> atuin 17.0.0
> joe in ENG-Mac-569 in ~
> ❯ bash --version
> GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0)
> Copyright (C) 2022 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> 
> This is free software; you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> ```
> 
> Any help is appreciated and happy to test anything!

I realised I wasn’t using `--disable-up-arrow` for my `atuin init`, sorry for the noise
