### ISSUE TITLE
[Enhancement] Import with arbitrary user/host

### ISSUE THREAD

**Issue by dotsam** [atuinsh/atuin#988]
I've found some old shell history files, and although I could import them by setting `HISTFILE`, they would be imported with the current host/user where I run the import, and that's not where these files originate from.

I would like to see support for optionally specifying a file, hostname, and username with the `import` command

**Comment by benjaminwood** [comment]
@dotsam I had this same challenge.

Turns out you can simply specify `ATUIN_HOST_NAME` & `ATUIN_HOST_USER` as env-vars before import:

https://github.com/atuinsh/atuin/blob/613218f0d80e7dd9bd688d6a30d06d33fd83d0c4/atuin-client/src/api_client.rs#L157-L163

**Comment by dotsam** [comment]
Ah, looks like that's new since I opened the issue. Closing this as fixed by #1041 and released in v16
