### ISSUE TITLE
Incomplete history on 3 different machines

### ISSUE THREAD

**Issue by dotsam** [atuinsh/atuin#989]
I currently have Atuin set up and syncing with three different machines. While each machine has approximately the same total number of history entries as the sync server, that total is made up of a varying number of entries from each. Possibly related to #226 

All machine's histories were imported from a .bash_history file (and all of the bash_history line counts contain timestamps, so line counts / 2 for actual lines of history). All of these stats are after a `atuin sync --force`

Here are some relevant details, gathered within 30 minutes of each other, so counts don't quite line up perfectly everywhere.

<details>

<summary><strong>Host 1</strong></summary>

```sh
sam@host1 ~
$ atuin history list --format "{host}" | sort | uniq -c
  74257 host1
   1584 host2
    729 host3

sam@host1 ~
$ wc -l .bash_history
10663 .bash_history # I seem to have lost some history here, probably spawned a shell with a different history limit at some point

sam@host1 ~
$ atuin status
[Local]
Sync frequency: 1h
Last sync: 2023-05-19 21:31:31.248881 UTC
History count: 76583

[Remote]
Address: https://api.atuin.sh
Username: dotsam
History count: 76660

sam@host1 ~
$ sqlite3 .local/share/atuin/history.db 'SELECT hostname, COUNT(*) FROM history GROUP BY hostname;'
host1:Unknown|1
host1:root|1
host1:sam|74269
host2:sam|1584
host3:sam|729
```

</details>

<details>

<summary><strong>Host 2</strong></summary>

```sh
sam@host2 ~
$ atuin history list --format "{host}" | sort | uniq -c
  24477 host1
  51527 host2
    727 host3

sam@host2 ~
$ wc -l .bash_history
100166 .bash_history

sam@host2 ~
$ atuin status
[Local]
Sync frequency: 1h
Last sync: 2023-05-19 21:40:32.854764160 UTC
History count: 76734

[Remote]
Address: https://api.atuin.sh
Username: dotsam
History count: 76660

sam@host2 ~
$ sqlite3 .local/share/atuin/history.db 'SELECT hostname, COUNT(*) FROM history GROUP BY hostname;'
host1:sam|24477
host2:sam|51536
host3:sam|727
```

</details>

<details>

<summary><strong>Host 3</strong></summary>

```sh
sam@host3 ~
$ atuin history list --format "{host}" | sort | uniq -c
  68868 host1
   1368 host2
   6429 host3

sam@host3 ~
$ wc -l .bash_history
13550 .bash_history

sam@host3 ~
$ atuin status
[Local]
Sync frequency: 1h
Last sync: 2023-05-19 21:37:40.568510141 UTC
History count: 76668

[Remote]
Address: https://api.atuin.sh
Username: dotsam
History count: 76660

sam@host3 ~
$ sqlite3 .local/share/atuin/history.db 'SELECT hostname, COUNT(*) FROM history GROUP BY hostname;'
host1:Unknown|1
host1:sam|68867
host2:sam|1368
host3:sam|6433
```

</details>

**Comment by jgroboredo** [comment]
Hi there! I have the exact same problem and it started to happen when I setup my third machine and imported its `zsh` history. 

I also tried to host a server and the same problem happened. On the server logs I kept seeing this warning after triggering a sync:

```
atuin_server::database: history too long
```

Not sure if these are related, haven't had much time to explore this deeper.

**Comment by alerque** [comment]
Any relation to #486?

**Comment by dotsam** [comment]
Seems possible. I know that @ellie is working on some [big sync changes](https://hachyderm.io/@ellie/110566682000942595) that might hopefully fix sync edge cases like this

**Comment by dotsam** [comment]
[Upgrading to sync v2](https://forum.atuin.sh/t/sync-v2-testing/124/14?u=dotsam) seem to have everything working great now!
