### ISSUE TITLE
`atuin sync` command hanging, `atuin status` last sync at 1970-01-01 00:00:00 UTC 

### ISSUE THREAD

**Issue by aallrd** [atuinsh/atuin#997]
Hello,

The `atuin sync` command I run on the servers where I install/configure the `atuin` client is hanging indefinitely.

The `atuin status` command shows the below weird output:
```
[Local]
Sync frequency: 20s
Last sync: 1970-01-01 00:00:00 UTC
History count: 134

[Remote]
Address: https://atuin.foo.com
Username: bar
History count: 695
```

I am able to `curl` the `atuin` server and I am logged in:
```
$ curl https://atuin.foo.com
{"homage":"\"Through the fathomless deeps of space swims the star turtle Great A'Tuin, bearing on its back the four giant elephants who carry on their shoulders the mass of the Discworld.\" -- Sir Terry Pratchett","version":"14.0.1"}
$ atuin login
You are already logged in! Please run 'atuin logout' if you wish to login again
````

`atuin` server (self-hosted): 14.0.1 (https://atuin.foo.com)
`atuin` client 14.0.1.
`atuin` client config `~/.config/atuin/config.toml`:
```
update_check = false
sync_address = "https://atuin.foo.com"
sync_frequency = "20s"
style = "compact"
filter_mode = "host"
```

I don't know how to troubleshoot/debug further this issue, do you have any idea?

Thank you.

**Comment by dcarosone** [comment]
Did you resolve this? Can you try with the current release on both client and server?

Steps to try:
* Remove the 20s sync frequency, for now.
* try `atuin sync --force`

**Comment by ellie** [comment]
If you could try the new sync here: https://forum.atuin.sh/t/sync-v2-testing/124

That would be great! So far it seems to have performed far better than the old one

**Comment by koalalorenzo** [comment]
> https://forum.atuin.sh/t/sync-v2-testing/124

I tried even with that sync v2 and I still have the last sycn to epoc 0

<img width="522" alt="Screenshot 2024-05-20 at 10 09 59" src="https://github.com/atuinsh/atuin/assets/33528/1a228c17-a3ab-4b73-93ea-e3bca4bec177">

**Comment by ellie** [comment]
@koalalorenzo could you open your own issue please? This one is pretty old

I suspect you may need to update your atuin
